#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer ai_1() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M506 153q6 7 6 16t-5 16L277 501q-8 11-21 11t-21-11L5 185q-5-7-4.5-16T6 153L121 9q8-9 20-9h230q13 0 20 9zm-53 17L359 53H"
                    "154L60 170l196 270zm-51-3q-20-3-34-12t-23-20.5-13.5-24T325 88q-1-2-2.5-2t-2.5 2q-3 21-12 35t-20.5 23-"
                    "23.5 13.5-22 6.5q-2 1-2 2.5t2 2.5q20 3 34 12t22.5 20.5 13.5 24 7 22.5q1 2 2.5 2t2.5-2q3-21 12-34.5t20"
                    ".5-22.5 23.5-14 22-7q2-1 2-2.5t-2-2.5z",
            }()
        );
    }
}
