#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer ai_2() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M506.227 153q5 7 5.5 16t-4.5 16l-230 316q-8 11-21 11t-21-11l-230-316q-5-7-5-16t6-16l114-144q8-9 21-9h230q13 0 20 9zm-10"
                    "4 19q2-1 1.5-2.5t-2.5-2.5q-20-3-34-12t-22.5-20.5-13.5-24-7-22.5q-1-2-2.5-2t-1.5 2q-4 21-13 35t-20 23-"
                    "23.5 13.5-22.5 6.5q-5 2 0 5 21 3 34.5 12t22.5 20.5 14 24 7 22.5q0 2 2 2t2-2q3-21 12-34.5t20.5-22.5 24"
                    "-14 22.5-7z",
            }()
        );
    }
}
