#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer auto_layout() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M26 512q-11 0-18.5-7T0 487V359q0-11 7.5-18.5T26 333h179q11 0 18 7.5t7 18.5v128q0 11-7 18t-18 7H26zm281 0q-11 0-18.5-7t-"
                    "7.5-18V256q0-11 7.5-18t18.5-7h179q11 0 18.5 7t7.5 18v231q0 11-7.5 18t-18.5 7H307zM26 282q-11 0-18-7.5"
                    "T1 256V26Q1 15 8 7.5T26 0h179q11 0 18.5 7.5T231 26v230q0 11-7.5 18.5T205 282H26zm282-103q-11 0-18.5-7"
                    "t-7.5-18V26q0-11 7.5-18.5T308 0h179q11 0 18 7.5t7 18.5v128q0 11-7 18t-18 7H308z",
            }()
        );
    }
}
