#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer block() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M90 378l153 69V227L90 158v220zm37-260l142 64 142-64-142-64zm321 260V158l-154 69v220zm51-261v277q0 16-15 24l-204 92q-3 1"
                    "-5.5 1.5t-5.5.5q-4 0-10-2L54 418q-15-8-15-24V118q0-4 2-10 0-1 1-2 0-1 2.5-4t3.5-3q1-2 6-4L259 3q10-5 "
                    "21 0l204 92q4 2 6 4 1 0 3.5 3t2.5 4 .5 1 .5 2q2 4 2 8z",
            }()
        );
    }
}
