#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer boolean() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M503 467q8 8 8 18.5t-8 18.5q-9 7-18 7t-18-7l-84-84-83 84q-9 7-18 7t-18-7q-7-8-7-18.5t7-18.5l84-83-84-83q-7-8-7-18t7-18q"
                    "8-8 18-8t18 8l83 84 84-84q8-8 18-8t18 8 8 18-8 18l-84 83zM324 11q8 7 9 17.5T326 47L141 255q-7 9-19 9-"
                    "11 0-19-9L10 151q-7-8-6.5-18.5T12 115q7-7 16-7 11 0 20 9l74 83L289 13q8-9 18-9 8 0 17 7z",
            }()
        );
    }
}
