#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer bound_validation_rule() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M284.5 342h-114v114h114V342zm0-170h-114v113h114V172zm-256 284q-11 0-21-8-7-11-7-21v-57q0-28 28-28 14 0 21 8 8 5 8 20v57"
                    "q0 13-8 21t-21 8zm21-276q8 5 8 20v57q0 13-8 21-9 7-21 7-28 0-28-28v-57q0-28 28-28 14 0 21 8zm454-57q8"
                    " 5 8 20v341q0 13-8 20-6 6-14 7h-353q-10-2-16.5-9.5t-6.5-17.5V143q0-14 8-20 8-8 21-8h340q14 0 21 8zM25"
                    "5.5 1q14 0 21 8 8 7 8 21 0 13-8 21-9 7-21 7h-56q-10 0-21-7-8-10-8-21 0-13 8-21t21-8h56zm171 0q15 0 20"
                    " 8 8 7 8 21 0 28-28 28h-57q-28 0-28-28 0-12 7-21 8-8 21-8h57z",
            }()
        );
    }
}
