#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer build_work_zone() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M238.03 296q-11-30-2-60t46-44q7-3 14-4t13-1q26 0 45 18t27 47q1 5 5.5 7t9.5 0q3-2 5-5.5t0-7.5l-37-101q-2-8-.5-14.5t3.5-1"
                    "1.5q10-20 28-31t40-11q11 0 26 5 30 11 43.5 40t2.5 59l-73 201q-7 19-29 36t-51 17-52.5-13.5-32.5-38.5zm"
                    "-232-115q-11-30 2.5-59t43.5-40q15-5 27-5 23 0 43 14t28 37l73 201q5 15 4 30t-7 28.5-17 24-26 15.5-26 5"
                    "q-24 0-43.5-14t-28.5-37z",
            }()
        );
    }
}
