#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer build_process_automation() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M370.5 327q-19 6-24-17l-23-99q-2-7-9.5-6.5t-7.5 8.5v145q0 32-22 54.5t-54 22.5-54.5-22.5-22.5-54.5V205q0-27 10-50t27.5-4"
                    "0.5T231.5 87t50-10h49q27 0 50.5 10t41.5 27.5 28 40.5 10 50q0 43-25.5 76t-64.5 46z",
            }()
        );
    }
}
