#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer business_application_studio() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M211 150l-48-29-152 76v7l-5 50zm66 307v55L3 358l50-25zm-40-319v-6l1-29V81l193 122-50 25zm2-83V0l267 167-52 25zM20 324L0"
                    " 335l4-48v-7l228-116 49 30zm492-139l-2 48-1 7-6 4-223 111-49-27zM277 377v55L77 321l53-27zm231-112l-2 "
                    "48v7l-151 77-52-28z",
            }()
        );
    }
}
