#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer business_service() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M278.385 360l33 100h106l32-100-86-63zm209-211q8 16 4 35t-21 29l-21 17-44-28q3-4 6-7.5t8-6.5l21-16-17-35-1-1-31 13q-9 3-"
                    "18 3t-16-3-12-5l-42-25q-12-8-17-16t-8-16l-8-36h-37l-8 34q-2 6-8 17.5t-19 17.5l-41 24q-5 2-11.5 5t-16."
                    "5 3q-8 0-17-3l-32-13-18 36 23 17q20 15 20 41v51q0 28-21 42l-21 16 17 35 1 1 30-12q9-4 20-4 9 0 15.5 3"
                    "t11.5 5l20 12-24 46-23-14-31 12q-9 3-19 3-31 0-46-26l-19-38q-8-16-4-35t21-29l21-17v-51l-23-19q-14-11-"
                    "18.5-28t3.5-34l18-35q5-14 18-22t28-8q11 0 20 4l31 14 43-27 2-4 7-31q5-18 18-29t32-11h36q20 0 33.5 11t"
                    "17.5 30l8 32 1 1 43 26 31-12q9-3 19-3 14 0 26 6.5t20 20.5zm-124 88q4 0 8 2l131 96q9 5 5 14l-51 154q-2"
                    " 8-11 8h-162q-10 0-12-8l-50-154q-3-8 4-14l132-96q4-2 6-2z",
            }()
        );
    }
}
