#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer business_capability() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M135.056 436h245l76-234-199-144-198 144zm263 50h-282q-17 0-24-17l-87-269q-2-8 0-15.5t9-12.5l228-166q8-5 15-5 8 0 15 5l2"
                    "28 166q7 5 9.5 12.5t.5 15.5l-88 269q-5 17-24 17z",
            }()
        );
    }
}
