#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer clear_all_mapping() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M473.5 276h-435q-16 0-27-11t-11-27 11-27.5 27-11.5h435q16 0 27 11.5t11 27.5-11 27-27 11zm0-174h-435q-16 0-27-11T.5 64t1"
                    "1-27 27-11h435q16 0 27 11t11 27-11 27-27 11zm-149 410q-11 0-18-8-8-8-8-18t8-18l53-52-53-53q-8-7-8-17."
                    "5t8-18.5 18-8q11 0 19 8l52 53 52-53q8-8 18-8 12 0 18 8 8 8 8 18t-8 18l-52 53 52 52q8 8 8 18t-8 18q-3 "
                    "5-7.5 6.5t-9.5 1.5q-12 0-19-8l-52-52-52 52q-7 8-19 8zm-106-64h-180q-16 0-27-11.5T.5 410q0-17 11-28t27"
                    "-11h180q17 0 28 11t11 28q0 15-11 26.5t-28 11.5z",
            }()
        );
    }
}
