#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer composition() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M199 512H60q-24 0-40.5-16.5T3 455V316q0-24 16.5-40.5T60 259h139q2 0 4.5.5t4.5.5L417 51h-89q-10 0-17.5-7.5T303 25t7.5-18"
                    "T328 0h158q11 0 18 7t7 18v157q0 11-7 18t-18 7-18.5-7-7.5-18V79L249 290q3 6 5 12t2 14v139q0 24-16.5 40"
                    ".5T199 512z",
            }()
        );
    }
}
