#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer data_input_arrow() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M441 253L263 127v75H50v103h213v74zm60-21q10 6 10 21 0 14-10 21L256 447q-8 5-15 5h-3q-11 0-18.5-7.5T212 426v-70H24q-10 0"
                    "-17.5-7.5T-1 330V176q0-10 7.5-17.5T24 151h188V80q0-11 7.5-18.5T238 54q5 0 10 1.5t8 4.5z",
            }()
        );
    }
}
