#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer dependency() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M486 208q-11 0-18-7t-7-18V79L309 232q-7 7-18 7t-18-7q-8-8-8-18t8-18L417 50h-88q-11 0-18.5-7T303 25t7.5-18T329 0h157q11 "
                    "0 18 7t7 18v158q0 11-7 18t-18 7zM27 506q-11 0-18-7t-7-17.5T9 464l177-177q8-8 18-8t18 8 8 18-8 18L45 4"
                    "99q-7 7-18 7z",
            }()
        );
    }
}
