#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer error_end_event() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 511q-53 0-99.5-20T75 436.5t-55-81T0 256t20-100 55-81.5T156.5 20 256 0t99.5 20T437 74.5t55 81.5 20 100-20 99.5-55 8"
                    "1-81.5 54.5-99.5 20zm0-422q-35 0-65.5 13t-53 35.5-35.5 53T89 256t13 65 35.5 52.5 53 35.5 65.5 13 65.5"
                    "-13 53-35.5 35-52.5 12.5-65-12.5-65.5-35-53-53-35.5T256 89zm85 84l-57 132q-3 6-9 6t-10-4l-25-38-50 55"
                    "q-4 4-8 4-11 0-11-12 0-2 1-3l56-132q5-7 9-7 6 0 10 6l23 37 53-56q2-3 6-3 7 0 9.5 4.5T341 173zm-54 70l"
                    "1-2h-2q1 1 1 2z",
            }()
        );
    }
}
