#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer escalation_end_event() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 89q-35 0-65.5 13t-53 35.5-35.5 53T89 256t13 65 35.5 52.5 53 35.5 65.5 13 65.5-13 53-35.5 35-52.5 12.5-65-12.5-65.5"
                    "-35-53-53-35.5T256 89zm96 257q0 4-2 5h-4l-90-60-90 60q-3 2-4 0-2-2-2-5l92-185q2-2 4-2l4 2zm-96 165q-5"
                    "3 0-99.5-20T75 436.5t-55-81T0 256t20-100 55-81.5T156.5 20 256 0t99.5 20T437 74.5t55 81.5 20 100-20 99"
                    ".5-55 81-81.5 54.5-99.5 20z",
            }()
        );
    }
}
