#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer flow() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M188.5 309q10 5 14 14.5t-1 19.5q-41 91-88 91h-87q-11 0-18-7.5t-7-18.5 7-18 18-7h87q3-1 15.5-15t26.5-46q4-10 13.5-13.5t1"
                    "9.5.5zm314 81q8 8 8 18t-8 18l-76 76q-7 7-18 7t-17-7q-8-8-8-18t8-18l33-32h-89q-34 0-62-29t-45-80l-40-1"
                    "21q-12-36-29-55t-31-19h-98q-11 0-18.5-7t-7.5-18T12 87t18.5-7h98q34 0 62 29t45 80l40 120q13 37 30 55.5"
                    "t30 18.5h89l-33-33q-8-8-8-17.5t8-17.5q6-8 17-8 10 0 18 8zm-245-213q-9-5-11-15.5t3-19.5q7-11 14.5-22t1"
                    "8-20 23.5-14.5 31-5.5h88l-32-33q-8-7-8-17.5t8-17.5q8-8 18-8t18 8l76 75q7 8 7 18t-7 18l-76 76q-7 7-18 "
                    "7t-18-7q-8-8-8-18t8-18l32-33h-88q-14 0-22 9t-22 30q-7 12-21 12-6 0-14-4z",
            }()
        );
    }
}
