#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer gateway() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M258.5 63q-12 0-20 8l-170 170q-8 8-8 19 0 9 8 19l170 170q10 8 19 8t19-8l170-170q9-9 9-19 0-12-9-19l-170-170q-7-8-18-8zm"
                    "0 449q-34 0-58-24l-170-170q-25-24-25-57.5t25-58.5l170-170q24-24 58-24 15 0 30 6t27 18l170 170q25 25 2"
                    "5 58.5t-25 57.5l-170 170q-24 24-57 24z",
            }()
        );
    }
}
