#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer hub() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M102 301q0-11-7-18.5T77 275t-18.5 7.5T51 301v102q0 11 7.5 19t18.5 8 18-8 7-19V301zm90 0q0-11-7.5-18.5T166 275t-18 7.5-7"
                    " 18.5v102q0 11 7 19t18 8 18.5-8 7.5-19V301zm89 0q0-11-7-18.5t-18-7.5-18.5 7.5T230 301v102q0 11 7.5 19"
                    "t18.5 8 18-8 7-19V301zm90 0q0-11-7-18.5t-18-7.5-18.5 7.5T320 301v102q0 11 7.5 19t18.5 8 18-8 7-19V301"
                    "zm90 0q0-11-7.5-18.5T435 275t-18 7.5-7 18.5v102q0 11 7 19t18 8 18.5-8 7.5-19V301zM115 146q4 2 12 2h25"
                    "9q7 0 11-2V81q-4-2-11-2H127q-8 0-12 2v65zm295 79q43 0 72.5 25t29.5 62v81q0 37-29.5 62T410 480H102q-43"
                    " 0-72.5-25T0 393v-81q0-37 29.5-62t72.5-25h308zm-283-26q-28 0-46-12.5T63 154V74q0-20 18-33t46-13h259q2"
                    "6 0 44 13t18 33v80q0 20-18 32.5T386 199H127z",
            }()
        );
    }
}
