#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer interface() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M52 345q0 12 20 24l184 86 186-88q8-3 13-9.5t5-12.5V166q0-8-7.5-14.5T440 143L256 56 70 143q-8 4-13 10t-5 13v179zm204 165"
                    "q-5 0-11-3L48 415Q0 389 0 345V166q0-23 13.5-42T49 96L245 4q11-6 22 0l197 92q48 26 48 70v179q0 23-13.5"
                    " 42T463 415l-196 92q-6 3-11 3zm-45-151v-15h30V167h-30v-15h90v15h-30v177h30v15h-90z",
            }()
        );
    }
}
