#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer internal_block_diagram() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M64.5 165l22 33 71-32-16-32zm100 156l-78-34-23 34 95 48zm109-79l-81-35-81 35 81 36zm-46-77l72 33 21-33-77-31zm95 158l-2"
                    "3-37-75 34 19 50zm163-119q11 0 18.5 7.5t7.5 18.5v51q0 11-7.5 18t-18.5 7h-51q-11 0-18-7t-7-18h-54l25 3"
                    "7q2 4 3 9t-1 10q-2 11-11 16l-19 12 42 43h40q11 0 18.5 7.5t7.5 18.5v51q0 11-7.5 18t-18.5 7h-51q-11 0-1"
                    "8-7t-7-18v-41l-38-40q-1 0-3 2l-115 51q-6 2-10 2t-10-2l-116-51q-14-6-14-23v-10l-37-19q-11-5-14-16t4-21"
                    "l47-70v-10l-47-70q-7-12-4-22 3-11 16-16l127-51q10-4 19 0t13 13l16 30 16-30q5-9 13.5-13t18.5 0l75 30 4"
                    "3-43V26q0-11 7-18.5t18-7.5h51q11 0 18.5 7.5t7.5 18.5v51q0 11-7.5 18t-18.5 7h-40l-27 27q12 5 15 16 5 1"
                    "1-2 22l-41 63h70q0-11 7-18.5t18-7.5h51z",
            }()
        );
    }
}
