#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer integer() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M128.5 430q11 0 18.5 7t7.5 18-7.5 18-18.5 7h-103q-11 0-18-7t-7-18 7-18 18-7h27V123h-27q-11 0-18-7.5T.5 97t7-18.5 18-7.5"
                    "h52q11 0 18 7.5t7 18.5v333h26zm179-359q11 0 18 7.5t7 18.5v179q0 11-7 18t-18 7h-77v129h77q11 0 18 7t7 "
                    "18-7 18-18 7h-102q-11 0-18.5-7t-7.5-18V276q0-11 7.5-18.5t18.5-7.5h76V123h-76q-11 0-18.5-7.5T179.5 97t"
                    "7.5-18.5 18.5-7.5h102zm179 0q11 0 18 7.5t7 18.5v358q0 11-7 18t-18 7h-90q-11 0-18-7t-7-18 7-18 18-7h65"
                    "V301h-65q-11 0-18-7t-7-18 7-18.5 18-7.5h65V123h-65q-11 0-18-7.5t-7-18.5 7-18.5 18-7.5h90z",
            }()
        );
    }
}
