#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer marquee() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M83 512q-35 0-59-24T0 429q0-11 7.5-18t18.5-7 18 7 7 18q0 13 9.5 22.5T83 461q11 0 18.5 7.5T109 487t-7.5 18-18.5 7zm346 0"
                    "q-11 0-18.5-7t-7.5-18 7.5-18.5T429 461q13 0 22.5-9.5T461 429q0-11 7.5-18t18.5-7 18 7 7 18q0 35-24 59t"
                    "-59 24zM26 339q-11 0-18.5-7T0 314V199q0-11 7.5-18.5T26 173t18 7.5 7 18.5v115q0 11-7 18t-18 7zm461 0q-"
                    "11 0-18.5-7t-7.5-18V199q0-11 7.5-18.5T487 173t18 7.5 7 18.5v115q0 11-7 18t-18 7zM26 109q-11 0-18.5-7T"
                    "0 84q0-18 6.5-33t18-26.5T51 6.5 83 0q11 0 18.5 7.5T109 26t-7.5 18T83 51q-13 0-22.5 9.5T51 84q0 11-7 1"
                    "8t-18 7zm288-58H199q-11 0-18.5-7T173 26t7.5-18.5T199 0h115q11 0 18 7.5t7 18.5-7 18-18 7zm173 58q-11 0"
                    "-18.5-7T461 84q0-14-9.5-23.5T429 51q-11 0-18.5-7T403 26t7.5-18.5T429 0q17 0 32.5 6.5t26.5 18T505.5 51"
                    "t6.5 33q0 11-7 18t-18 7zM314 512H199q-11 0-18.5-7t-7.5-18 7.5-18.5T199 461h115q11 0 18 7.5t7 18.5-7 1"
                    "8-18 7z",
            }()
        );
    }
}
