#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer navigate_source_code() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M170 426q-11 0-18-7t-7-18 7-18.5 18-7.5h176q11 0 18.5 7.5T372 401t-7.5 18-18.5 7H170zm0-96q-11 0-18-7.5t-7-18.5 7-18 18"
                    "-7h176q11 0 18.5 7t7.5 18-7.5 18.5T346 330H170zm0-191q-11 0-18-7.5t-7-18.5 7-18 18-7h176q11 0 18.5 7t"
                    "7.5 18-7.5 18.5T346 139H170zm0 94q-11 0-18-7.5t-7-18.5 7-18 18-7h176q11 0 18.5 7t7.5 18-7.5 18.5T346 "
                    "233H170zm335 150q7 9 7 18 0 10-7 17l-54 53q-7 7-17 7-11 0-18-7-7-8-7-18t7-17l36-35-36-35q-7-7-7-17t7-"
                    "18q7-7 18-7 10 0 17 7zM7 131q-7-9-7-18 0-10 7-17l54-53q9-7 17-7 10 0 18 8 7 8 7 17.5T96 79l-36 34 36 "
                    "35q7 8 7 18t-7 17q-8 8-18 8-8 0-17-7z",
            }()
        );
    }
}
