#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer note_connection() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M32.5 512q-11 0-18-7-7-8-7-18t7-18l50-50q8-8 18-8 11 0 17 8 8 8 8 18t-8 18l-50 50q-7 7-17 7zm102-110q-11 0-18-7-8-8-8-1"
                    "8t8-18l50-50q8-8 18-8t18 8q7 8 7 18t-7 18l-51 50q-6 7-17 7zm100-100q-10 0-18-8-8-7-8-17t8-18l50-49q8-"
                    "8 18-8 9 0 17 8 8 7 8 17t-8 17l-49 50q-8 8-18 8zm100-100q-11 0-18-7-8-8-8-18t8-18l50-50q7-7 18-7t17 7"
                    "q8 8 8 18t-8 18l-50 50q-7 7-17 7zm99-100q-10 0-17-7-8-8-8-18t8-18l50-49q8-8 18-8 9 0 17 8t8 17.5-8 17"
                    ".5l-50 50q-6 7-18 7z",
            }()
        );
    }
}
