#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer o_data() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M77 256h358v-77H77v77zm384 76q21 0 36 15.5t15 36.5-15 36-36 15q-29 0-44-26h-58q-11 0-18.5-7.5T333 384v-77h-51v109q11 7 "
                    "18 18.5t7 25.5q0 21-14.5 36T256 511q-21 0-36-15t-15-36q0-29 26-44V307h-52v77q0 10-7 17.5t-18 7.5H95q-"
                    "13 26-44 26-21 0-36-15T0 384t15-36.5T51 332q14 0 26 7.5T95 358h33v-51H77q-22 0-36.5-15T26 256v-77q0-2"
                    "1 14.5-36T77 128h256v-26q0-2 .5-3.5t.5-3.5q-12-6-19.5-18T307 51q0-21 15-36t37-15q21 0 36 15t15 36q0 3"
                    "1-28 44 2 6 2 7v26h51q22 0 37 15t15 36v77q0 21-15 36t-37 15h-51v51h33q7-11 18.5-18.5T461 332z",
            }()
        );
    }
}
