#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer parallel_gateway() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M261 504q-32 0-58-24L36 312q-24-23-24-56t24-57L203 32q12-12 27-18t30-6q33 0 57 24l167 167q24 24 24 57t-24 56L317 480q-2"
                    "4 24-56 24zm0-442q-10 0-20 8L75 237q-9 7-9 19 0 10 9 19l166 166q10 8 19 8 11 0 19-8l167-166q9-9 9-19 "
                    "0-12-9-19L279 70q-8-8-18-8zm80 221h-54v54q0 11-7.5 18.5T261 363q-12 0-20-7.5t-8-18.5v-54h-54q-11 0-19"
                    "-8.5t-8-19.5 8-19 19-8h54v-53q0-11 8-19t20-8q11 0 18.5 8t7.5 19v53h54q11 0 19 8t8 19-8 19.5-19 8.5z",
            }()
        );
    }
}
