#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer port() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M53 458h406V53H53v405zm158-77q-11 0-19-8L87 267q-8-8-8-18.5t8-18.5l105-106q10-8 19-8 11 0 19 8t8 18.5-8 18.5l-87 88 87 "
                    "87q8 8 8 18.5t-8 18.5-19 8zm274 130H27q-11 0-19-7.5T0 485V26Q0 15 8 7.5T27 0h458q11 0 19 7.5t8 18.5v4"
                    "59q0 11-8 18.5t-19 7.5zM303 381q-11 0-18-8-8-8-8-18.5t8-18.5l87-87-87-88q-8-8-8-18.5t8-18.5q10-8 19-8"
                    " 10 0 18 8l107 106q8 7 8 18.5t-8 18.5L322 373q-8 8-19 8z",
            }()
        );
    }
}
