#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer progress_group() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M53 458h406V53H53v405zm108-133h158q3 0 5-2l44-67-44-68q-2-2-5-2H161l37 55q10 14 0 29zm158 54H111q-14 0-23-14-7-13 1-28l"
                    "55-81-55-82q-8-13-1-28 9-14 23-14h208q32 0 49 27l54 82q11 14 0 29l-54 82q-17 27-49 27zm166 132H27q-11"
                    " 0-19-7.5T0 485V26Q0 15 8 7.5T27 0h458q11 0 19 7.5t8 18.5v459q0 11-8 18.5t-19 7.5z",
            }()
        );
    }
}
