#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer realization() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M486 207q-15 0-22-15l-58-57-96 95q-7 7-18 7t-18-7q-8-7-8-17t8-18l96-96-50-50q-14-6-14-23 0-10 7-17t18-7h155q11 0 18 7t7"
                    " 17v156q0 11-7 18t-18 7zM28 510q-10 0-18-8-7-8-7-17.5t7-17.5l161-161q8-8 18-8 11 0 17 8 8 8 8 18t-8 1"
                    "7L45 502q-8 8-17 8zm433-391V51h-67z",
            }()
        );
    }
}
