#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer receptions() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M255.5 512q-7 0-11-2l-196-93q-48-28-48-70V167q0-23 13.5-42.5T49.5 96l195-92q12-7 23 0l48 23q11 5 14.5 15t-1.5 20q-7 15-"
                    "24 15-6 0-12-3l-37-17-184 87q-17 7-17 23v180q0 9 7 15.5t12 8.5l182 86 185-87q17-9 17-23V167q0-11 8-19"
                    "t19-8 19 8 8 19v180q0 23-13.5 42t-35.5 29l-195 92q-6 2-12 2zm97-223h-115q-11 0-18.5-7.5t-7.5-18.5V152"
                    "q0-11 7.5-18.5t18.5-7.5q12 0 20 7.5t8 18.5v48l182-178q8-8 19-8 10 0 18 8t8 18.5-8 18.5l-181 178h49q11"
                    " 0 18.5 7.5t7.5 18.5-7.5 18.5-18.5 7.5z",
            }()
        );
    }
}
