#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer receive_task() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M77.5 123q-7 0-13 3h1l176 110q5 4 13 4t13-4l177-110q1 0 2-1-3-1-5.5-1.5t-6.5-.5h-357zm177 169q-21 0-41-13l-161-100v224q"
                    "0 11 7 19t18 8h357q11 0 19-8t8-19V177l-166 102q-9 5-19.5 9t-21.5 4zm180 188h-357q-32 0-54.5-22.5T.5 4"
                    "03V148q0-32 22.5-54.5T77.5 71h357q32 0 54.5 22.5t22.5 54.5v255q0 32-22.5 54.5T434.5 480z",
            }()
        );
    }
}
