#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer references() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M461 409H359v51h102v-51zm26-51q11 0 18 7.5t7 18.5v102q0 11-7 18t-18 7H333q-11 0-18.5-7t-7.5-18v-26h-25q-22 0-36.5-15T23"
                    "1 409V102h-26v26q0 11-7.5 18t-18.5 7H26q-11 0-18.5-7T0 128V26Q0 15 7.5 7.5T26 0h153q11 0 18.5 7.5T205"
                    " 26v25h26q21 0 36 15t15 36v307h25v-25q0-11 7.5-18.5T333 358h154z",
            }()
        );
    }
}
