#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer router() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M102 301q0-11-7-18t-18-7-18 7-7 18v102q0 11 7 19t18 8 18-8 7-19V301zm90 0q0-11-7-18t-18-7-18.5 7-7.5 18v102q0 11 7.5 19"
                    "t18.5 8 18-8 7-19V301zm90 0q0-11-7.5-18t-18.5-7-18 7-7 18v102q0 11 7 19t18 8 18.5-8 7.5-19V301zm89 0q"
                    "0-11-7-18t-18-7-18 7-7 18v102q0 11 7 19t18 8 18-8 7-19V301zm90 0q0-11-7.5-18t-18.5-7-18 7-7 18v102q0 "
                    "11 7 19t18 8 18.5-8 7.5-19V301zm-51-77q44 0 73 25.5t29 62.5v81q0 37-29 62t-73 25H102q-43 0-72.5-25T0 "
                    "393v-81q0-37 29.5-62.5T102 224V96q0-11 7.5-18.5T128 70t18.5 7.5T154 96v128h205V96q0-11 7.5-18.5T385 7"
                    "0t18 7.5 7 18.5v128z",
            }()
        );
    }
}
