#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer script_task() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M30.5 371q-10 0-20-8-8-9-8-20.5t8-19.5l65-65-65-65q-8-9-8-20.5t8-19.5 20-8q13 0 20 8l85 84q8 8 8 20.5t-8 20.5l-85 85q-1"
                    "0 8-20 8zm453 28h-227q-11 0-19.5-8.5t-8.5-19.5 8.5-20 19.5-9h227q11 0 19.5 9t8.5 20-8.5 19.5-19.5 8.5"
                    "zm0-339h-453q-12 0-20-8.5T2.5 31q0-11 8-19.5t20-8.5h453q11 0 19.5 8.5t8.5 19.5q0 12-8.5 20.5T483.5 60"
                    "zm0 113h-227q-11 0-19.5-8.5t-8.5-20.5q0-11 8.5-19.5t19.5-8.5h227q11 0 19.5 8.5t8.5 19.5q0 12-8.5 20.5"
                    "t-19.5 8.5zm0 113h-227q-11 0-19.5-8.5t-8.5-19.5q0-12 8.5-20t19.5-8h227q11 0 19.5 8t8.5 20q0 11-8.5 19"
                    ".5t-19.5 8.5zm0 226h-453q-12 0-20-8t-8-20 8-20 20-8h453q11 0 19.5 8t8.5 20-8.5 20-19.5 8z",
            }()
        );
    }
}
