#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer solution_not_licensed() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M461 409h-1q-35 47-88 74.5T256 511q-53 0-99.5-20T75 436.5t-55-81T0 256t20-100 55-81.5T156.5 20 256 0q63 0 116 27.5t88 7"
                    "4.5h1q24 32 37.5 71t13.5 83q0 43-13.5 82T461 409zM256 51q-42 0-79.5 16T111 111t-44 65.5T51 256t16 79."
                    "5 44 65 65.5 43.5 79.5 16V51zm135 358h-7v7l3.5-3.5z",
            }()
        );
    }
}
