#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer start_timer_event() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M262 51q-45 0-84 16t-67.5 44T66 176.5 50 256t16 79.5 44.5 65T178 444t84 16q41 0 77-16t63-43.5 43-65 16-79.5-16-79.5-43-"
                    "65.5-63-44-77-16zm0 120q-19 0-35.5 6.5t-29 18T178 222t-7 32 7 32 19.5 26.5 29 18T262 337q15 0 29-6.5t"
                    "25.5-18T335 286t7-32-7-32-18.5-26.5-25.5-18-29-6.5zm0 340q-57 0-105-20t-83-54.5-54.5-81T0 256t19.5-10"
                    "0T74 74.5 157 20 262 0q53 0 98.5 20t79 54.5 53 81.5T512 256t-19.5 99.5-53 81-79 54.5-98.5 20zm0-135q-"
                    "27 0-50.5-9.5t-41.5-26-28.5-39T131 254t10.5-47.5 28.5-39 41.5-26T262 132q22 0 43.5 9.5t38 26 27 39T38"
                    "1 254t-10.5 47.5-27 39-38 26T262 376zm29-96h-29q-16 0-18.5-5.5T241 260v-51q0-8 2.5-13t18.5-5q7 0 8 5t"
                    "1 13v33h20q8 0 14 5t6 13q0 9-6 14.5t-14 5.5z",
            }()
        );
    }
}
