#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer status_suspended() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M218 165q0-16-11-27t-27-11-27.5 11-11.5 27v179q0 17 11.5 28t27.5 11 27-11 11-28V165zm141 0q0-16-11.5-27T320 127t-27 11-"
                    "11 27v179q0 17 11 28t27 11 27.5-11 11.5-28V165zM461-1q21 0 36 15t15 36v410q0 21-15 36t-36 15H51q-21 0"
                    "-36-15T0 460V50q0-21 15-36T51-1h410z",
            }()
        );
    }
}
