#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer string() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M102 249V140q0-8-2-13t-4-6l-41 1q1 0-1 5t-2 13v109h50zm180 78q0-11-7-18.5t-18-7.5h-26v129h26q11 0 18-8t7-19v-76zm0-180q"
                    "0-11-7-18t-18-7h-26v127h25q11 0 18.5-7.5T282 223v-76zM98 70q23 0 39.5 20.5T154 140v340h-52V300H52v180"
                    "H0V140q0-29 16-49.5T55 70h43zm159 0q32 0 54 22.5t22 54.5v76q0 30-19 52 19 21 19 52v76q0 32-22 54.5T25"
                    "7 480h-78V70h78zm230 128q-11 0-18.5-7t-7.5-18v-40q0-11-12-11h-28q-11 0-11 11v284q0 13 11 13h28q12 0 1"
                    "2-13v-39q0-11 7.5-18t18.5-7 18 7 7 18v39q0 26-18.5 44.5T449 480h-28q-26 0-44-18.5T359 417V133q0-26 18"
                    "-44.5T421 70h28q26 0 44.5 18.5T512 133v40q0 11-7 18t-18 7z",
            }()
        );
    }
}
