#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer sub_content() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M77 71q-11 0-18.5 7T51 96v307q0 11 7.5 18.5T77 429h358q11 0 18.5-7.5T461 403V148q0-11-7.5-18.5T435 122H256q-12 0-18-8l-"
                    "44-43H77zm152 320H78q-1 0-1-2V289q0-1 1-1h151q1 0 1 1v100q0 2-1 2zm0-128H78l-1-1V161q0-1 1-1h151l1 1v"
                    "101q0 1-1 1zm206 217H77q-32 0-54.5-22.5T0 403V96q0-32 22.5-54.5T77 19h127q11 0 19 8l43 44h169q32 0 54"
                    ".5 22.5T512 148v255q0 32-22.5 54.5T435 480zm-1-89H283q-2 0-2-2V289q0-1 2-1h151q1 0 1 1v100zm0-128H283"
                    "l-2-1V161q1-1 2-1h151l1 1v101z",
            }()
        );
    }
}
