#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer sub_process_marker() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M485 511H27q-11 0-19-7.5T0 485V26Q0 15 8 7.5T27 0h458q11 0 19 7.5t8 18.5v459q0 11-8 18.5t-19 7.5zM53 458h406V53H53v405z"
                    "m283-174h-54v53q0 11-7.5 19t-18.5 8-19-8-8-19v-53h-53q-11 0-18.5-7.5T150 258t7.5-18.5T176 232h53v-53q"
                    "0-11 8-19t19-8 18.5 8 7.5 19v53h54q11 0 18.5 7.5T362 258t-7.5 18.5T336 284z",
            }()
        );
    }
}
