#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer switch_() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M103 302q0-11-7.5-18.5T77 276t-18.5 7.5T51 302v101q0 11 7.5 18.5T77 429t18.5-7.5T103 403V302zm89 0q0-11-7.5-18.5T167 27"
                    "6q-11 0-18.5 7.5T141 302v101q0 11 7.5 18.5T167 429q10 0 17.5-7.5T192 403V302zm89 0q0-11-7-18.5t-18-7."
                    "5-18.5 7.5T230 302v101q0 11 7.5 18.5T256 429t18-7.5 7-18.5V302zm90 0q0-11-7.5-18.5T345 276t-18 7.5-7 "
                    "18.5v101q0 11 7 18.5t18 7.5 18.5-7.5T371 403V302zm90 0q0-11-7.5-18.5T435 276t-18.5 7.5T409 302v101q0 "
                    "11 7.5 18.5T435 429t18.5-7.5T461 403V302zm-52-77q44 0 73.5 25t29.5 62v82q0 18-8 33.5T482 455t-32.5 18"
                    ".5T409 480H103q-22 0-40.5-6.5T30 455 8 427.5 0 394v-82q0-25 14-45t37-31v-50q0-11 7.5-18t18.5-7 18.5 7"
                    " 7.5 18v39h51V117H77q-11 0-18.5-7T51 92t7.5-18.5T77 66h101q9 0 16 6t9 14q2 6 2 11v128h102V97q0-2 .5-2"
                    ".5t.5-1.5v-1q0-11 7-18.5t18-7.5h101q11 0 18.5 7.5T460 92t-7.5 18-18.5 7h-76v108h51z",
            }()
        );
    }
}
