#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer systemtracks() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M460.5 274q0-5-5-5h-99q-11 0-18.5-7t-7.5-18q0-8 4.5-14t10.5-9v-49q0-5-5-5h-99q-11 0-18-7.5t-7-18.5q0-16 15-23V55q0-4-3-"
                    "4h-172q-4 0-4 4v172q0 3 4 3h46q0-11 7-18t18-7 18.5 7 7.5 18v124q0 5 5 5h58v-1q0-11 7.5-18.5t18.5-7.5 "
                    "18 7.5 7 18.5v98q0 5 5 5h183q5 0 5-5V274zm-5-56q23 0 39.5 16.5t16.5 39.5v182q0 23-16.5 39.5T455.5 512"
                    "h-183q-23 0-39.5-16.5T216.5 456v-46h-58q-23 0-39.5-16.5T102.5 354v-73h-46q-23 0-39-15.5T1.5 227V55q0-"
                    "23 16-39t39-16h172q23 0 38.5 16t15.5 39v61h58q23 0 39.5 16.5t16.5 39.5v46h59zm-39 96q8 0 13.5 5t5.5 1"
                    "3v79q0 8-5.5 13.5t-13.5 5.5h-83q-8 0-13.5-5.5t-5.5-13.5 5.5-13.5 13.5-5.5h43l-279-279q-5-5-5-13.5t5-1"
                    "3.5 14-5 14 5l272 272v-26q0-8 5.5-13t13.5-5z",
            }()
        );
    }
}
