#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer systemrecommendations() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M151.5 512h-75q-32 0-54-23.5T.5 430V90q0-34 22-58t54-24h353q31 0 53 24t22 58v85q0 11-7 18t-18 7-18-7-7-18V90q0-13-7-22."
                    "5t-18-9.5h-353q-11 0-18.5 9.5T50.5 90v340q0 14 7.5 23t18.5 9h75q11 0 18.5 7.5t7.5 18.5q0 10-7.5 17t-1"
                    "8.5 7zm285 0q-6 0-12-3l-71-37-71 37q-13 6-26-2-12-9-10-25l14-78-57-54q-11-12-6-26 3-15 20-17l78-12 35"
                    "-70q7-13 23-13 7 0 13.5 3t9.5 10l35 70 78 12q15 1 20 17 6 14-6 26l-57 54 14 78q3 15-10 25-7 5-14 5z",
            }()
        );
    }
}
