#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer system() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M485 512H22q-1-1-3-1-6-2-10-5v-1q-2 0-2-2l-2-2-3-5q-1-2-1-2.5T0 491V27q0-4 2-10 0-1 1-2 0-1 2-3v-1q2-3 8-7h1l2-2h2l1-1h"
                    "4q1-1 2-1h462q1 0 2 .5t3 .5l4 2q1 0 2 1h1q2 1 2 2 1 0 2 1l1 1q1 1 2 3h1l1 2 2 4v1l1 1v3q0 1 .5 1t.5 1"
                    "v462q0 3-1 5v2q-1 1-1 3-1 1-1 1.5t-1 1.5q0 1-.5 1t-.5 1l-1 1-1 2-2 2q-1 0-2 1l-1 1h-1l-1 1h-1q-1 1-3 "
                    "2-2 0-3 1h-6zM53 459h406V53H53v406z",
            }()
        );
    }
}
