#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer task() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M52.897 355.306h405.208V92.819H52.897v262.487zm431.158 52.897H25.949q-10.978 0-18.464-7.486T0 382.253V65.871q0-10.978 7"
                    ".485-18.464t18.464-7.485h458.106q10.978 0 19.462 7.485T512 65.871v316.382q0 10.979-8.483 18.464t-19.4"
                    "62 7.486z",
            }()
        );
    }
}
