#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer technicalscenario() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M102 409l-25-15-26 15v30l26 14 25-14v-30zm359 0l-26-15-25 15v30l25 14 26-14v-30zM231 104l25 15 26-15V74l-26-14-25 14v30"
                    "zm281 275v89l-77 44-76-44v-89l51-29v-37q0-4-1-5l-1-1H103q0 1-.5 2t-.5 4v37l52 29v89l-77 44-77-44v-89l"
                    "51-29v-37q0-24 15-40.5t36-16.5h129v-93l-52-30V44l77-44 77 44v89l-51 30v93h128q21 0 36 16.5t15 40.5v37"
                    "z",
            }()
        );
    }
}
