#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer technicalinstance() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M194 402l-34-58H93l-34 58 34 59h67zm0-292l-34-59H93l-34 59 34 59h67zm-4 183l63 109-63 110H64L0 402l64-109h126zm0-293l63"
                    " 110-63 110H64L0 110 64 0h126zm322 256l-63 110H322l-63-110 63-110h127z",
            }()
        );
    }
}
