#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer use_case_extension_point() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M459 232H52q-1 1-1 4 0 39 19.5 67t50 47 66.5 28 69 9q35 0 71-9.5t66-28.5 49-48 19-69h-2zM256 91q-63 0-113.5 25T68 180h3"
                    "76q-24-39-74.5-64T256 91zm-53 210q0 11-7 18.5t-18 7.5-18.5-7.5T152 301t7.5-18 18.5-7 18 7 7 18zm77 0q"
                    "0 11-7.5 18.5T254 327q-10 0-17.5-7.5T229 301t7.5-18 17.5-7q11 0 18.5 7t7.5 18zm-24 137q-54 0-100.5-15"
                    ".5t-81-42T20 318 0 240t20-78.5T74.5 98t81-42.5T256 40t101 15.5T438.5 98t54 63.5T512 240t-19.5 78-54 6"
                    "2.5-81.5 42T256 438zm101-137q0 11-7 18.5t-18 7.5-19-7.5-8-18.5 8-18 19-7 18 7 7 18z",
            }()
        );
    }
}
