#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Tnt
{
    inline Nui::ElementRenderer value_flow() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M355.5 428h-329q-15 0-22-13-7-15 1-27l93-138-93-139q-8-12-1-27 7-13 22-13h329q42 0 65 34l86 130q10 14 0 29l-86 130q-23 "
                    "34-65 34zm-281-51h281q14 0 23-12l77-115-77-116q-9-12-23-12h-281l76 113q10 14 0 29zm192-51h-48q-8 0-13"
                    ".5-5.5t-5.5-13.5q0-19 19-19h48q3 0 6-3t3-7-3-6.5-6-2.5h-20q-19 0-33-14t-14-34q0-17 11-30.5t27-16.5v-2"
                    "0q0-19 19-19t19 19v19h19q8 0 13.5 5.5t5.5 13.5q0 19-19 19h-48q-3 0-6 3t-3 7 3 6.5 6 2.5h20q19 0 33 14"
                    "t14 34-14 34-33 14z",
            }()
        );
    }
}
