#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer accidental_leave() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M391 480H122q-38 0-64-26t-26-64V121q0-37 26-63t64-26h269q37 0 63 26t26 63v269q0 38-26 64t-63 26zM122 83q-17 0-28 11t-11"
                    " 27v269q0 17 11 28t28 11h269q16 0 27-11t11-28V121q0-16-11-27t-27-11H122zm175 301h-82q-11 0-18.5-7.5T1"
                    "89 358v-36h-36q-11 0-18-7t-7-18v-82q0-11 7-18.5t18-7.5h36v-36q0-11 7.5-18t18.5-7h82q11 0 18 7t7 18v36"
                    "h36q11 0 18.5 7.5T384 215v82q0 11-7.5 18t-18.5 7h-36v36q0 11-7 18.5t-18 7.5zm-57-51h31v-36q0-11 7.5-1"
                    "8.5T297 271h36v-31h-36q-11 0-18.5-7t-7.5-18v-36h-31v36q0 11-7 18t-18 7h-36v31h36q11 0 18 7.5t7 18.5v3"
                    "6z",
            }()
        );
    }
}
