#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer activity_assigned_to_goal() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M166 461q11 0 18.5 7t7.5 18-7.5 18.5T166 512H90q-24 0-41-17t-17-41V122q0-24 17-41t41-17h38v-6q0-24 17-41t41-17h76q24 0 "
                    "41 17t17 41v6h38q24 0 41 17t17 41v44q0 11-7.5 18.5T390 192t-18-7.5-7-18.5v-44q0-7-7-7h-39q-5 20-20.5 "
                    "32.5T262 160h-76q-21 0-36.5-12.5T130 115H90q-7 0-7 7v332q0 7 7 7h76zm13-359q0 7 7 7h76q7 0 7-7V58q0-7"
                    "-7-7h-76q-7 0-7 7v44zm173 154q27 0 50 10t40.5 27.5T470 334t10 50-10 50-27.5 40.5T402 502t-50 10-50-10"
                    "-40.5-27.5T234 434t-10-50 10-50 27.5-40.5T302 266t50-10zm0 205q32 0 54.5-22.5T429 384t-22.5-54.5T352 "
                    "307t-54.5 22.5T275 384t22.5 54.5T352 461zm0-109q14 0 23 9t9 23-9 23-23 9-23-9-9-23 9-23 23-9z",
            }()
        );
    }
}
