#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer add_activity_2() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M181 71q7-7 17-7 11 0 18.5 7.5T224 90q0 10-8 18L101 217q-6 7-17 7t-18-7L8 162q-8-8-8-19t7.5-18 18.5-7q10 0 17 7l41 38zm"
                    "305 153q11 0 18.5 7.5T512 250t-7.5 18-18.5 7h-60v61q0 11-7.5 18.5T400 362t-18.5-7.5T374 336v-61h-60q-"
                    "11 0-18.5-7t-7.5-18 7.5-18.5T314 224h60v-61q0-11 7.5-18t18.5-7 18.5 7 7.5 18v61h60zm-305 71q7-7 17-7 "
                    "11 0 18.5 7.5T224 314q0 10-8 18L101 441q-6 7-17 7t-18-7L8 386q-8-8-8-19t7.5-18 18.5-7q10 0 17 7l41 38"
                    "z",
            }()
        );
    }
}
