#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer attachment_html() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M400 198q0 11-7.5 18.5T374 224t-18-7.5-7-18.5V51H196l-20 24v66q0 21-15 36t-36 15H75l-8 9v260h83q11 0 18.5 7t7.5 18-7.5 "
                    "18.5T150 512H42q-11 0-18.5-7.5T16 486V192q0-10 6-17L165 9q6-9 19-9h190q11 0 18.5 7.5T400 26v172zm88 1"
                    "83q8 8 8 19t-8 19l-58 54q-7 7-17 7-11 0-18.5-7.5T387 454q0-10 8-18l38-36-38-36q-8-8-8-18 0-11 7.5-18."
                    "5T413 320q10 0 17 7zm-197-61q11 0 18.5 7.5T317 346q0 10-8 18l-38 36 38 36q8 8 8 18 0 11-7.5 18.5T291 "
                    "480q-10 0-17-7l-58-54q-8-8-8-19t8-19l58-54q7-7 17-7z",
            }()
        );
    }
}
