#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer back_to_top() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M26 51q-11 0-18.5-7T0 26 7.5 7.5 26 0h460q11 0 18.5 7.5T512 26t-7.5 18-18.5 7H26zm363 200q8 8 8 18 0 11-7.5 18t-18.5 7-"
                    "18-7l-71-72v271q0 11-7.5 18.5T256 512t-18.5-7.5T230 486V215l-71 72q-7 7-18 7t-18.5-7-7.5-18q0-10 8-18"
                    "l115-116q9-7 18-7t18 7z",
            }()
        );
    }
}
