#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer bar_chart() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M454 32q11 0 18.5 7.5T480 58v396q0 11-7.5 18.5T454 480h-12q-11 0-18.5-7.5T416 454V58q0-11 7.5-18.5T442 32h12zM198 160q1"
                    "1 0 18.5 7.5T224 186v268q0 11-7.5 18.5T198 480h-12q-11 0-18.5-7.5T160 454V186q0-11 7.5-18.5T186 160h1"
                    "2zm128 64q11 0 18.5 7.5T352 250v204q0 11-7.5 18.5T326 480h-12q-11 0-18.5-7.5T288 454V250q0-11 7.5-18."
                    "5T314 224h12zM70 352q11 0 18.5 7.5T96 378v76q0 11-7.5 18.5T70 480H58q-11 0-18.5-7.5T32 454v-76q0-11 7"
                    ".5-18.5T58 352h12z",
            }()
        );
    }
}
