#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer basket() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M454 192q24 0 41 17t17 40q0 9-3 18l-54 173q-6 18-21 29t-34 11H115q-19 0-34-11t-21-29L3 268q-3-9-3-18 0-24 17-41t41-17h7"
                    "2L236 43q8-11 21-11t21 11l107 149h69zm-261 0h129l-65-90zm268 57q0-6-7-6H58q-7 0-7 6l58 175q0 5 6 5h28"
                    "5q4 0 6-5zm-204 39q20 0 34 14t14 34-14 34-34 14-34-14-14-34 14-34 34-14z",
            }()
        );
    }
}
