#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer browse_folder() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M166 429q11 0 18.5 7t7.5 18-7.5 18.5T166 480H90q-38 0-64-26T0 390V122q0-38 26-64t64-26h115q9 0 18 7l44 38h155q38 0 64 2"
                    "6t26 63v96q0 11-7.5 18.5T486 288t-18-7.5-7-18.5v-96q0-16-11-27t-28-11H256q-9 0-18-7l-44-38H90q-17 0-2"
                    "8 11t-11 28v268q0 17 11 28t28 11h76zm339 39q7 7 7 18t-7.5 18.5T486 512t-18-7L363 399q-28 17-59 17-22 "
                    "0-42.5-9t-36-24.5-24.5-36-9-42.5q0-23 9-43.5t24-35.5 35.5-24 43.5-9 43.5 9 35.5 24 24 35.5 9 43.5q0 3"
                    "1-17 59zM304 365q24 0 42.5-18t18.5-43q0-23-17.5-42T304 243t-43 19-17 42q0 25 18 43t42 18z",
            }()
        );
    }
}
