#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer bubble_chart() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M454 480H58q-11 0-18.5-7.5T32 454V58q0-11 7.5-18.5T58 32t18 7.5T83 58v371h371q11 0 18.5 7t7.5 18-7.5 18.5T454 480zM224 "
                    "96q-14 0-23-9t-9-23 9-23 23-9 23 9 9 23-9 23-23 9zm176 64q-20 0-34-14t-14-34 14-34 34-14 34 14 14 34-"
                    "14 34-34 14zm-246 64q-11 0-18.5-7.5T128 198t7.5-18 18.5-7 18 7 7 18-7 18.5-18 7.5zm134 32q-14 0-23-9t"
                    "-9-23 9-23 23-9 23 9 9 23-9 23-23 9zm128 64q-14 0-23-9t-9-23 9-23 23-9 23 9 9 23-9 23-23 9zm-262 63q-"
                    "11 0-18.5-7t-7.5-18 7.5-18.5T154 332t18 7.5 7 18.5-7 18-18 7zm160 1q-11 0-18.5-7t-7.5-18 7.5-18.5T314"
                    " 333t18 7.5 7 18.5-7 18-18 7z",
            }()
        );
    }
}
