#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer bullet_text() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M486 115H154q-11 0-18.5-7T128 90t7.5-18.5T154 64h332q11 0 18.5 7.5T512 90t-7.5 18-18.5 7zM32 128q-14 0-23-9T0 96q0-13 9"
                    "-22.5T32 64t23 9.5T64 96q0 14-9 23t-23 9zm0 160q-14 0-23-9t-9-23 9-23 23-9 23 9 9 23-9 23-23 9zm454 0"
                    "H154q-11 0-18.5-7.5T128 262t7.5-18 18.5-7h332q11 0 18.5 7t7.5 18-7.5 18.5T486 288zM32 448q-14 0-23-9t"
                    "-9-23 9-23 23-9 23 9 9 23-9 23-23 9zm454 0H154q-11 0-18.5-7.5T128 422t7.5-18 18.5-7h332q11 0 18.5 7t7"
                    ".5 18-7.5 18.5T486 448z",
            }()
        );
    }
}
