#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer business_objects_experience() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M368 214q-1 17-13.5 29.5T324 256q-16 0-28.5-10.5T281 219l-81-70q-10 5-20 5-2 0-4.5-.5t-4.5-.5L86 264q2 8 2 12 0 18-13 3"
                    "1t-31 13-31-13-13-31 13-31 31-13h1l92-118v-4q-2-18 11.5-31T180 66q17 0 29 10.5t14 25.5l83 70q10-4 18-"
                    "4 9 0 15 3l86-87q0-20 10-36t33-16q18 0 31 13t13 31-13 31-31 13q-4 0-6-1zm106 10q11 0 18 7.5t7 18.5v20"
                    "4q0 11-7 18.5t-18 7.5-18.5-7.5T448 454V250q0-11 7.5-18.5T474 224zm-288 32q11 0 18 7.5t7 18.5v172q0 11"
                    "-7 18.5t-18 7.5-18.5-7.5T160 454V282q0-11 7.5-18.5T186 256zm140 64q11 0 18.5 7.5T352 346v108q0 11-7.5"
                    " 18.5T326 480t-18-7.5-7-18.5V346q0-11 7-18.5t18-7.5zM26 384q11 0 18 7.5t7 18.5v44q0 11-7 18.5T26 480t"
                    "-18.5-7.5T0 454v-44q0-11 7.5-18.5T26 384z",
            }()
        );
    }
}
