#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer card() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M390 32q38 0 64 26t26 64v268q0 38-26 64t-64 26H122q-38 0-64-26t-26-64V122q0-38 26-64t64-26h268zm39 90q0-17-11-28t-28-11"
                    "H122q-17 0-28 11t-11 28v268q0 17 11 28t28 11h268q17 0 28-11t11-28V122zM328 224q-17 0-28.5-11.5T288 18"
                    "4t11.5-28.5T328 144t28.5 11.5T368 184t-11.5 28.5T328 224zm53 123q3 4 3 11 0 11-7.5 18.5T358 384H154q-"
                    "11 0-18.5-7.5T128 358q0-4 1-6l25-108q2-9 9.5-14.5T179 224q6 0 12 3t9 8l56 85 66-29q3-1 6.5-2t6.5-1q15"
                    " 0 23 14z",
            }()
        );
    }
}
