#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer cart_4() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M358 70q11 0 18.5 7.5T384 96t-7.5 18.5T358 122h-44v44q0 11-7.5 18.5T288 192t-18.5-7.5T262 166v-44h-44q-11 0-18.5-7.5T19"
                    "2 96t7.5-18.5T218 70h44V26q0-11 7.5-18.5T288 0t18.5 7.5T314 26v44h44zM194 288l-27 45h256q11 0 18.5 7."
                    "5T449 359t-7.5 18-18.5 7H122q-11 0-18.5-7T96 359q0-8 4-13l49-83L58 83H26q-11 0-18.5-7T0 58t7.5-18.5T2"
                    "6 32h48q17 0 23 14l96 191h196l75-128q4-7 10-10t12-3q11 0 18.5 7.5T512 122q0 6-4 13l-83 140q-6 13-22 1"
                    "3H194zm-50 128q20 0 34 14t14 34-14 34-34 14-34-14-14-34 14-34 34-14zm256 0q20 0 34 14t14 34-14 34-34 "
                    "14-34-14-14-34 14-34 34-14z",
            }()
        );
    }
}
