#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer chain_link() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M286 357q-50 0-86-36l-5-5q-7-7-7-18t7.5-18 17.5-7q12 0 19 7l4 5q20 20 50 20 28 0 50-20l72-73q21-21 21-49 0-29-21-50l-9-"
                    "9q-19-21-50-21-29 0-50 21l-10 10q-7 7-18 7t-18-7-7-18 7-18l10-10q36-36 86-36t86 36l9 9q36 36 36 86t-3"
                    "6 86l-72 72q-36 36-86 36zM163 480q-52 0-86-36l-10-9q-17-17-26-40t-9-46q0-49 35-86l73-72q36-36 86-36t8"
                    "6 36l4 4q8 8 8 19 0 10-7.5 17.5T298 239t-18-7l-4-5q-23-21-50-21-29 0-50 21l-72 73q-11 10-16 22.5T83 3"
                    "49q0 29 21 50l9 9q21 21 50 21 28 0 49-21l5-4q8-8 18-8 11 0 18 7.5t7 18.5-7 18l-4 4q-36 36-86 36z",
            }()
        );
    }
}
