#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer clear_filter() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M358 0q11 0 18.5 7.5T384 26q0 8-5 15L256 199v105q0 13-11 21l-77 54q-7 5-14 5-11 0-18.5-7.5T128 358V199L5 41q-5-7-5-15Q0"
                    " 15 7.5 7.5T26 0h332zm-52 51H78l96 124q5 7 5 16v118l26-18V191q0-9 5-16zm199 417q7 7 7 18t-7.5 18.5T48"
                    "6 512t-18-7l-36-37-36 37q-7 7-18 7t-18.5-7.5T352 486q0-10 8-18l36-36-36-36q-8-8-8-18 0-11 7.5-18.5T37"
                    "8 352t18 7l36 37 36-37q7-7 18-7t18.5 7.5T512 378t-7 18l-37 36z",
            }()
        );
    }
}
