#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer close_command_field() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M230 416q-10 0-17-7L72 274q-8-6-8-18 0-11 8-19l141-134q7-7 17-7 11 0 18.5 7.5T256 122q0 10-8 18L127 256l121 116q8 8 8 1"
                    "8 0 11-7.5 18.5T230 416zm192 0q-10 0-17-7L264 274q-8-6-8-18 0-11 8-19l141-134q7-7 17-7 11 0 18.5 7.5T"
                    "448 122q0 10-8 18L319 256l121 116q8 8 8 18 0 11-7.5 18.5T422 416z",
            }()
        );
    }
}
