#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer collapse_all() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M314 115q-11 0-18.5-7T288 90t7.5-18.5T314 64h173q11 0 18 7.5t7 18.5-7 18-18 7H314zm-186 36v271q0 11-7 18.5t-18 7.5-18.5"
                    "-7.5T77 422V151l-33 33q-8 8-18 8-11 0-18.5-7.5T0 166q0-10 8-18l76-77q9-7 19-7 9 0 18 7l76 77q8 8 8 18"
                    " 0 11-7.5 18.5T179 192q-10 0-18-8z",
            }()
        );
    }
}
