#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer column_chart_dual_axis() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M390 480H122q-38 0-64-26t-26-64V58q0-11 7.5-18.5T58 32t18 7.5T83 58v332q0 17 11 28t28 11h268q17 0 28-11t11-28V58q0-11 7"
                    "-18.5t18-7.5 18.5 7.5T480 58v332q0 38-26 64t-64 26zm-140-96q-11 0-18.5-7.5T224 358V122q0-11 7.5-18.5T"
                    "250 96t18 7.5 7 18.5v236q0 11-7 18.5t-18 7.5zm108 0q-11 0-18-7.5t-7-18.5V186q0-11 7-18.5t18-7.5 18.5 "
                    "7.5T384 186v172q0 11-7.5 18.5T358 384zm-204 0q-11 0-18.5-7.5T128 358V250q0-11 7.5-18.5T154 224t18 7.5"
                    " 7 18.5v108q0 11-7 18.5t-18 7.5z",
            }()
        );
    }
}
