#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer compare_2() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M486 461q11 0 18.5 7t7.5 18-7.5 18.5T486 512H26q-11 0-18.5-7.5T0 486t7.5-18 18.5-7h205V122q-7-3-14-8l-79 26v42l5 11q6 1"
                    "3 14 34t16 43 13.5 42.5T192 346q0 27-23.5 48.5T112 416t-56.5-22T32 343q0-13 4.5-31T48 274t15.5-40T79 "
                    "198l8-19v-57q0-18 17-25l88-29v-4q0-26 19.5-45T257 0q35 0 53 29l82-28q3-1 8-1 11 0 18.5 7.5T426 26v59q"
                    "6 13 15 35.5t17.5 46.5 15 46 6.5 36q0 28-23.5 49.5T400 320t-56.5-21.5T320 250q0-14 5.5-34.5t13.5-43 1"
                    "6.5-43.5T370 94l5-11V61l-55 19q-4 14-14 25.5T282 123v338h204zm-62-237l-24-68-24 68h48zm-288 96l-24-68"
                    "-24 68h48z",
            }()
        );
    }
}
