#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer create_session() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M422 288q11 0 18.5 7.5T448 314v76q0 38-26 64t-64 26H90q-38 0-64-26T0 390V122q0-38 26-64t64-26h140q11 0 18.5 7.5T256 58t"
                    "-7.5 18-18.5 7H90q-17 0-28 11t-11 28v38h179q11 0 18.5 7.5T256 186t-7.5 18-18.5 7H51v179q0 17 11 28t28"
                    " 11h268q17 0 28-11t11-28v-76q0-11 7-18.5t18-7.5zm76-197q14 2 14 16 0 7-4 11l-35 37 8 53q0 16-16 16-2 "
                    "0-8-2l-41-24-41 24q-6 2-8 2-16 0-16-16l8-53-34-37q-5-4-5-11 0-14 14-16l48-7 19-43q5-9 15-9 11 0 15 9l"
                    "19 43z",
            }()
        );
    }
}
