#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer credit_card() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M454 64q24 0 41 17t17 41v268q0 24-17 41t-41 17H58q-24 0-41-17T0 390V122q0-24 17-41t41-17h396zM58 115q-7 0-7 7v38h410v-3"
                    "8q0-7-7-7H58zm396 282q7 0 7-7V224H51v166q0 7 7 7h396zM262 288q11 0 18.5 7.5T288 314t-7.5 18-18.5 7H12"
                    "2q-11 0-18.5-7T96 314t7.5-18.5T122 288h140z",
            }()
        );
    }
}
