#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer crossed_line_chart() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M70 192q-10 0-18-8L8 140q-8-8-8-18 0-11 7.5-18.5T26 96t18 7l45 45q7 7 7 18t-7.5 18.5T70 192zM26 384q-11 0-18.5-7.5T0 35"
                    "8q0-10 7-17l153-172q8-9 19-9t19 8l110 122 161-155q7-7 17-7 11 0 18.5 7.5T512 154q0 10-8 18L325 345q-7"
                    " 7-19 7-10 0-18-8L179 224 45 375q-7 9-19 9zm294-160q-14 0-23-9t-9-23 9-23 23-9 23 9 9 23-9 23-23 9zM1"
                    "92 352q-14 0-23-9t-9-23 9-23 23-9 23 9 9 23-9 23-23 9zm294 64q-10 0-18-8l-44-44q-8-8-8-18 0-11 7.5-18"
                    ".5T442 320t18 7l45 45q7 7 7 18t-7.5 18.5T486 416z",
            }()
        );
    }
}
