#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer curriculum() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M435 45q32 0 54.5 22t22.5 54v14q0 11-7.5 18.5T486 161t-18-7.5-7-18.5v-14q0-11-7.5-18T435 96H256q-9 0-17-6l-44-39H90q-17"
                    " 0-28 11T51 90v268q0 17 11 28t28 11h44q11 0 18.5 7t7.5 18-7.5 18.5T134 448H90q-38 0-64-26T0 358V90q0-"
                    "38 26-64T90 0h115q10 0 17 6l44 39h169zm60 167q17 5 17 24v218q0 11-7.5 18.5T486 480t-18-7.5-7-18.5V254"
                    "l-115-41-33 18 87 31q17 5 17 24v200q0 11-7.5 18.5T391 512q-5 0-8-1l-142-51q-17-5-17-24V236q0-15 14-23"
                    "l94-50q6-3 12-3t9 1zm-129 92l-91-32v146l91 32V304z",
            }()
        );
    }
}
