#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer decrease_line_height() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M193 103q7-7 18-7t18.5 7.5T237 122q0 10-8 18l-76 76q-8 8-19 8-10 0-18-8l-76-76q-8-8-8-18 0-11 7.5-18.5T58 96t18 7l33 34"
                    "V26q0-11 7-18.5T134 0t18.5 7.5T160 26v111zm89-20q-11 0-18.5-7T256 58t7.5-18.5T282 32h172q11 0 18.5 7."
                    "5T480 58t-7.5 18-18.5 7H282zm172 45q11 0 18.5 7.5T480 154t-7.5 18-18.5 7H346q-11 0-18.5-7t-7.5-18 7.5"
                    "-18.5T346 128h108zm0 109q11 0 18.5 7t7.5 18-7.5 18.5T454 288H282q-11 0-18.5-7.5T256 262t7.5-18 18.5-7"
                    "h172zM229 372q8 8 8 18 0 11-7.5 18.5T211 416q-10 0-18-8l-33-33v111q0 11-7.5 18.5T134 512t-18-7.5-7-18"
                    ".5V375l-33 33q-8 8-18 8-11 0-18.5-7.5T32 390q0-10 8-18l76-77q9-7 18-7 10 0 19 7zm225-39q11 0 18.5 7t7"
                    ".5 18-7.5 18.5T454 384H346q-11 0-18.5-7.5T320 358t7.5-18 18.5-7h108zm0 96q11 0 18.5 7t7.5 18-7.5 18.5"
                    "T454 480H282q-11 0-18.5-7.5T256 454t7.5-18 18.5-7h172z",
            }()
        );
    }
}
