#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer desktop_mobile() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M262 397q11 0 18.5 7t7.5 18-7.5 18.5T262 448H154q-11 0-18.5-7.5T128 422t7.5-18 18.5-7h38v-45H58q-24 0-41-17T0 294V90q0-"
                    "24 17-41t41-17h332q24 0 41 17t17 41v44q0 11-7.5 18.5T422 160t-18-7.5-7-18.5V90q0-7-7-7H58q-7 0-7 7v20"
                    "4q0 7 7 7h204q11 0 18.5 7t7.5 18-7.5 18.5T262 352h-19v45h19zm224-173q11 0 18.5 7.5T512 250v204q0 11-7"
                    ".5 18.5T486 480H378q-11 0-18.5-7.5T352 454V250q0-11 7.5-18.5T378 224h108zm-83 51v109h58V275h-58z",
            }()
        );
    }
}
