#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer discussion() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M0 390V90q0-38 26-64T90 0h204q38 0 64 26t26 64v128q0 37-26 63t-64 26H139L44 408q-8 8-18 8t-18-7-8-19zM90 51q-17 0-28 11"
                    "T51 90v236l58-62q8-8 19-8h166q17 0 28-11t11-27V90q0-17-11-28t-28-11H90zm378 453l-95-101H186q-11 0-18."
                    "5-7t-7.5-18 7.5-18.5T186 352h198q11 0 19 8l58 62V186q0-11 7-18.5t18-7.5 18.5 7.5T512 186v300q0 12-8 1"
                    "9t-18 7q-11 0-18-8z",
            }()
        );
    }
}
