#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer disconnected() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M230 320q-10 0-18-8l-43-43-11 11q-8 8-18 8t-18-8l-32-31q-26-26-26-64 0-36 24-61L7 44q-7-7-7-18T7.5 7.5 26 0t18 7l80 81q"
                    "26-24 61-24 38 0 64 26l31 32q8 8 8 18t-8 18l-10 11 43 43q8 8 8 19 0 10-7.5 17.5T295 256t-18-7l-44-44-"
                    "28 28 43 43q8 8 8 18 0 11-7.5 18.5T230 320zm-90-94l86-86-13-14q-13-11-28-11-16 0-27 11l-32 32q-11 11-"
                    "11 27 0 15 11 28zm364 242q8 8 8 18 0 11-7.5 18.5T486 512t-18-7l-80-81q-27 24-61 24-38 0-64-26l-32-32q"
                    "-7-7-7-18t7-18l123-123q7-7 18-7t18 7l32 32q26 28 26 64 0 34-24 61zm-177-71q17 0 27-12l31-31q12-12 12-"
                    "27 0-16-12-28l-13-13-86 86 13 13q12 12 28 12z",
            }()
        );
    }
}
