#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer doctor() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M342 223q48 23 77 67t29 100v64q0 11-7.5 18.5T422 480h-32q-11 0-18-7.5t-7-18.5 7-18 18-7h7v-39q0-28-10.5-52.5t-29-42.5-4"
                    "3-28.5T262 256h-12q-28 0-52.5 10.5t-43 28.5-29 42.5T115 390v39h7q11 0 18 7t7 18-7 18.5-18 7.5H90q-11 "
                    "0-18.5-7.5T64 454v-64q0-55 29-99.5t77-67.5q-42-39-42-95 0-27 10.5-50.5t28-41 40.5-27T256 0t49.5 10 41"
                    " 27.5 27.5 41 10 49.5-11 51-31 44zm-86-18q33 0 55-23t22-54q0-32-22.5-54.5T256 51t-54.5 22.5T179 128t2"
                    "2.5 54.5T256 205zm86 169q11 0 18.5 7.5T368 400t-7.5 18.5T342 426h-60v60q0 11-7.5 18.5T256 512t-18.5-7"
                    ".5T230 486v-60h-60q-11 0-18.5-7.5T144 400t7.5-18.5T170 374h60v-60q0-11 7.5-18.5T256 288t18.5 7.5T282 "
                    "314v60h60z",
            }()
        );
    }
}
