#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer draw_rectangle() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M512 256q0 13-6 23.5T490 297v126q10 7 16 17.5t6 23.5q0 20-14 34t-34 14q-26 0-39-21H295q-13 21-39 21t-39-21H87q-13 21-39"
                    " 21-20 0-34-14T0 464q0-13 6-23.5T22 423V297q-10-7-16-17.5T0 256t6-23.5T22 215V89Q12 82 6 71.5T0 48q0-"
                    "20 14-34T48 0q13 0 23.5 6T89 22h126q7-10 17.5-16T256 0t23.5 6T297 22h126q7-10 17.5-16T464 0q20 0 34 1"
                    "4t14 34q0 13-6 23.5T490 89v126q10 7 16 17.5t6 23.5zm-90 184q3-5 7-9t9-8V297q-10-7-16-17.5t-6-23.5 6-2"
                    "3.5 16-17.5V89q-9-6-15-15H297q-7 10-17.5 16T256 96t-23.5-6T215 74H89q-6 9-15 15v126q10 7 16 17.5t6 23"
                    ".5-6 23.5T74 297v126q5 4 9 8t7 9h124q7-11 17.5-17.5T256 416t24.5 6.5T298 440h124z",
            }()
        );
    }
}
