#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer drill_up() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 32q11 0 19 8l102 109q7 7 7 17 0 11-7.5 18.5T358 192q-10 0-18-8l-84-89-84 89q-8 8-18 8-11 0-18.5-7.5T128 166q0-10 7"
                    "-17L237 40q8-8 19-8zm0 144q11 0 19 8l102 109q7 7 7 17 0 11-7.5 18.5T358 336q-10 0-18-8l-84-89-84 89q-"
                    "8 8-18 8-11 0-18.5-7.5T128 310q0-10 7-17l102-109q8-8 19-8zm0 144q11 0 19 8l102 109q7 7 7 17 0 11-7.5 "
                    "18.5T358 480q-10 0-18-8l-84-89-84 89q-8 8-18 8-11 0-18.5-7.5T128 454q0-10 7-17l102-109q8-8 19-8z",
            }()
        );
    }
}
