#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer duplicate() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M58 384q-11 0-18.5-7.5T32 358V90q0-38 26-64t64-26h236q11 0 18.5 7.5T384 26t-7.5 18-18.5 7H122q-17 0-28 11T83 90v268q0 1"
                    "1-7 18.5T58 384zm332 128H218q-38 0-64-26t-26-64V186q0-38 26-64t64-26h172q38 0 64 26t26 64v236q0 38-26"
                    " 64t-64 26zM218 147q-17 0-28 11t-11 28v236q0 17 11 28t28 11h172q17 0 28-11t11-28V186q0-17-11-28t-28-1"
                    "1H218z",
            }()
        );
    }
}
