#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer e_care() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M466 64q17 0 26 15.5t13.5 36T511 156t1 29q0 59-14.5 112.5t-44 94T379 456t-107 24q-35 0-64-8t-55-22l-48 45q-19 17-42 17-"
                    "24 0-43.5-17.5T0 452q0-24 19-43l53-52q-5-12-6.5-25T64 310q0-43 21.5-77t54-57 72-35.5T287 128h40q20 0 "
                    "36-3.5t30-10.5 27-18 28-25q9-7 18-7zm-5 130q0-36-5-61-19 16-36 25t-34 13.5-36.5 6T306 179h-19q-25 0-5"
                    "5 8.5T176 212t-43.5 39-17.5 53v6.5l1 7.5q25-20 56.5-30t65.5-18q38-8 72-19.5t54-35.5q8-9 15-12.5t13-3."
                    "5q10 0 17 8t7 19q0 18-19.5 33.5t-46 27-53 19T257 316q-35 8-66.5 18T136 367l-81 78q-3 3-3 7 0 9 11 9 4"
                    " 0 7-3l63-60q8-6 17-6 5 0 9 1.5t12 7.5q17 12 43 20t58 8q50 0 85.5-19.5T416 358t34-75 11-89z",
            }()
        );
    }
}
