#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer education() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M486 32q11 0 18.5 7.5T512 58v295q0 9-6 16t-15 9q-30 5-56.5 12.5t-52.5 19-53 27.5-58 38q-8 5-15 5t-15-5q-30-22-57-38t-53"
                    ".5-27.5-53-19T21 378q-9-2-15-9t-6-16V58q0-11 7.5-18.5T26 32t18 7.5T51 58v273q48 10 90 28t89 47V147q0-"
                    "12 13.5-25t32-25T313 75.5 343 62q32-14 69-22t74-8zM106 256q-10 0-10-9V48q0-7 5-11.5t11-4.5q3 0 5 1l64"
                    " 21q11 3 11 15v178q0 9-10 9-4 0-10-6l-28-26-24 24q-8 8-14 8zM461 84q-47 5-95.5 24T282 158v248q47-29 8"
                    "9-47t90-28V84z",
            }()
        );
    }
}
