#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer email_read() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M457 82q25 10 40 32.5t15 49.5v258q0 38-26 64t-64 26H90q-38 0-64-26T0 422V164q0-27 15-49.5T55 82L246 2q6-2 10-2t10 2zM75"
                    " 129q-7 2-11.5 7T56 146l179 116q10 7 21 7 13 0 21-7l179-116q-6-12-19-17L256 53zm347 332q17 0 28-11t11"
                    "-28V204L305 305q-22 15-49 15-26 0-49-15L51 204v218q0 17 11 28t28 11h332z",
            }()
        );
    }
}
