#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer employee_approvals() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M369 324q0 11-7 19.5t-18 8.5q-8 0-15.5-6T316 326q-7-15-20-28t-28.5-22.5T234 261t-36-5h-12q-28 0-52.5 10.5t-43 28.5-29 4"
                    "2.5T51 390v7h179q11 0 18.5 7t7.5 18-7.5 18.5T230 448H26q-11 0-18.5-7.5T0 422v-32q0-56 29.5-100.5T107 "
                    "222q-10-6-18-17t-13.5-25-8.5-29-3-28q0-26 10.5-48T103 36t41-26.5T192 0q27 0 50 10.5T282.5 38 310 78t1"
                    "0 48q0 13-2.5 27.5t-8.5 28-14.5 24T274 221q12 5 28 17t31 26.5 25.5 30T369 324zM192 51q-32 0-54.5 22.5"
                    "T115 128t22.5 54.5T192 205t54.5-22.5T269 128t-22.5-54.5T192 51zm294 301q11 0 18.5 7.5T512 378q0 8-6 1"
                    "6l-94 109q-7 9-19 9-11 0-19-8l-47-52q-7-7-7-17 0-11 7.5-18.5T346 409q10 0 19 9l27 30 75-87q8-9 19-9z",
            }()
        );
    }
}
