#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer energy_saving_lightbulb() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M142 48q-14-6-14-22 0-11 7-18.5T153 0q6 0 12 3l205 102q14 8 14 23 0 11-7.5 18.5T358 154q-6 0-11-3zm0 103q-14-8-14-23 0-"
                    "11 7-18.5t18-7.5q6 0 12 3l205 102q14 9 14 23 0 11-7.5 18.5T358 256q-6 0-11-3zm228 159q14 7 14 23 0 14"
                    "-14 23l-38 18v80q0 24-16.5 41T275 512h-39q-23 0-40-17t-17-41v-80l-37-18q-14-8-14-23 0-11 7-18.5t18-7."
                    "5q6 0 12 3l51 25q14 8 14 23v26h51v-26q0-14 14-23l6-2-159-80q-14-6-14-23 0-11 7-18t18-7q4 0 12 2zm-95 "
                    "151q6 0 6-7v-19h-51v19q0 7 6 7h39z",
            }()
        );
    }
}
