#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer excel_attachment() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M374 461q11 0 18.5 7t7.5 18-7.5 18.5T374 512H42q-11 0-18.5-7.5T16 486V179q0-11 7-17L166 8q6-8 18-8h190q11 0 18.5 7.5T40"
                    "0 26v44q0 11-7.5 18.5T374 96t-18-7.5-7-18.5V51H195l-19 21v53q0 21-15 36t-36 15H80l-13 13v272h307zm96-"
                    "301q11 0 18.5 7.5T496 186v204q0 11-7.5 18.5T470 416H234q-11 0-18.5-7.5T208 390V186q0-11 7.5-18.5T234 "
                    "160h236zm-25 51h-67v51h67v-51zm-186 0v51h67v-51h-67zm0 154h67v-51h-67v51zm186 0v-51h-67v51h67z",
            }()
        );
    }
}
