#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer favorite_list() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M490 173q10 2 16 9t6 16q0 10-7 19l-33 31q-8 8-18 8-11 0-18-7.5t-7-18.5q0-8 4-13l-111-16q-14-3-20-15l-46-99-46 99q-2 6-7"
                    ".5 9.5T191 201L78 217l81 85q5 5 6 10.5t1 11.5l-20 115 72-39q6-3 12-3 11 0 18.5 7t7.5 18q0 15-13 23l-1"
                    "19 64q-6 3-12 3-11 0-18.5-7.5T86 486q0-1 .5-1.5t.5-2.5l26-154L7 216q-7-9-7-18t6.5-16 15.5-9l148-21 63"
                    "-137q7-15 23-15t23 15l64 137zm-36 115q11 0 18.5 7.5T480 314t-7.5 18-18.5 7H346q-11 0-18.5-7t-7.5-18 7"
                    ".5-18.5T346 288h108zm0 86q11 0 18.5 7.5T480 400t-7.5 18.5T454 426H346q-11 0-18.5-7.5T320 400t7.5-18.5"
                    "T346 374h108zm0 87q11 0 18.5 7t7.5 18-7.5 18.5T454 512H346q-11 0-18.5-7.5T320 486t7.5-18 18.5-7h108z",
            }()
        );
    }
}
