#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer filter_analytics() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M454 32q11 0 18.5 7.5T480 58v396q0 11-7.5 18.5T454 480t-18-7.5-7-18.5V58q0-11 7-18.5t18-7.5zM262 96q11 0 18.5 7.5T288 1"
                    "22v332q0 11-7.5 18.5T262 480t-18-7.5-7-18.5V122q0-11 7-18.5t18-7.5zm96 64q11 0 18.5 7.5T384 186v268q0"
                    " 11-7.5 18.5T358 480t-18-7.5-7-18.5V186q0-11 7-18.5t18-7.5zm-198 64q14 0 23 9t9 23-9 23-23 9-23-9-9-2"
                    "3 9-23 23-9zm-96 96q14 0 23 9t9 23-9 23-23 9-23-9-9-23 9-23 23-9zm96 0q14 0 23 9t9 23-9 23-23 9-23-9-"
                    "9-23 9-23 23-9zm-96 96q14 0 23 9t9 23-9 23-23 9-23-9-9-23 9-23 23-9zm96 0q14 0 23 9t9 23-9 23-23 9-23"
                    "-9-9-23 9-23 23-9z",
            }()
        );
    }
}
