#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer filter_facets() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M198 128q11 0 18.5 7.5T224 154t-7.5 18-18.5 7H58q-11 0-18.5-7T32 154t7.5-18.5T58 128h140zm116 51q-11 0-18.5-7t-7.5-18 7"
                    ".5-18.5T314 128h140q11 0 18.5 7.5T480 154t-7.5 18-18.5 7H314zm-116 58q11 0 18.5 7t7.5 18-7.5 18.5T198"
                    " 288H58q-11 0-18.5-7.5T32 262t7.5-18 18.5-7h140zm256 0q11 0 18.5 7t7.5 18-7.5 18.5T454 288H314q-11 0-"
                    "18.5-7.5T288 262t7.5-18 18.5-7h140zm-256 96q11 0 18.5 7t7.5 18-7.5 18.5T198 384H58q-11 0-18.5-7.5T32 "
                    "358t7.5-18 18.5-7h140zm256 0q11 0 18.5 7t7.5 18-7.5 18.5T454 384H314q-11 0-18.5-7.5T288 358t7.5-18 18"
                    ".5-7h140z",
            }()
        );
    }
}
