#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer form() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M390 512H122q-24 0-41-17t-17-41V58q0-24 17-41t41-17h268q24 0 41 17t17 41v396q0 24-17 41t-41 17zM122 51q-7 0-7 7v396q0 7"
                    " 7 7h268q7 0 7-7V58q0-7-7-7H122zm204 128h-44q-11 0-18.5-7t-7.5-18 7.5-18.5T282 128h44q11 0 18.5 7.5T3"
                    "52 154t-7.5 18-18.5 7zm-134 13q-13 0-22.5-9.5T160 160t9.5-22.5T192 128t22.5 9.5T224 160t-9.5 22.5T192"
                    " 192zm0 90q-13 0-22.5-9.5T160 250q0-14 9.5-23t22.5-9 22.5 9 9.5 23q0 13-9.5 22.5T192 282zm134-7h-44q-"
                    "11 0-18.5-7t-7.5-18 7.5-18.5T282 224h44q11 0 18.5 7.5T352 250t-7.5 18-18.5 7zM192 378q-13 0-22.5-9.5T"
                    "160 346q0-14 9.5-23t22.5-9 22.5 9 9.5 23q0 13-9.5 22.5T192 378zm134-7h-44q-11 0-18.5-7t-7.5-18 7.5-18"
                    ".5T282 320h44q11 0 18.5 7.5T352 346t-7.5 18-18.5 7z",
            }()
        );
    }
}
