#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer fx() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M440 32q30 0 51 21t21 51v272q0 30-21 51t-51 21h-63q-11 0-18-7.5t-7-18.5 7-18 18-7h63q9 0 15-6t6-15V192H51v184q0 9 6 15t"
                    "15 6q11 0 18 7t7 18-7 18.5-18 7.5q-30 0-51-21T0 376V104q0-30 21-51t51-21h368zm-61 109l-29-58h-69l29 5"
                    "8h69zm-126 0l-29-58h-71l29 58h71zm-202 0h74L96 83H72q-9 0-15 6t-6 15v37zm410 0v-37q0-9-6-15t-15-6h-33"
                    "l29 58h25zm-83 185q0 11-7.5 18.5T352 352t-18.5-7.5T326 326v-12h-12q-11 0-18.5-7.5T288 288t7.5-18.5T31"
                    "4 262h12v-12q0-11 7.5-18.5T352 224t18.5 7.5T378 250v12h12q11 0 18.5 7.5T416 288t-7.5 18.5T390 314h-12"
                    "v12zm-79 33q9 2 15 9t6 16-6 16-15 9l-41 8-9 42q-2 9-9 15t-16 6-16-6-9-15l-8-42-42-8q-9-2-15-9t-6-16 6"
                    "-16 15-9l42-9 8-41q2-9 9-15t16-6 16 6 9 15l9 41z",
            }()
        );
    }
}
