#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer headset() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M480 358q0 32-12 60t-33 49-49 33-60 12h-76q-11 0-18.5-7.5T224 486v-26q0-13 8-19t17-6q10 0 18 6.5t8 19.5h51q28 0 50.5-13"
                    "t36.5-35q-10 3-23 3h-44q-11 0-18.5-7.5T320 390V250q0-11 7.5-18.5T346 224h83q-1-36-15.5-67.5t-37.5-55-"
                    "54-37T256 51t-66 13.5-54 37-37 55T83 224h83q11 0 18.5 7.5T192 250v140q0 11-7.5 18.5T166 416h-44q-38 0"
                    "-64-26t-26-64v-96q0-47 17.5-88.5t47.5-73 71-50T256 0q48 0 89 18.5t71 50 47 73 17 88.5v128zm-339-83H83"
                    "v51q0 17 11 28t28 11h19v-90zm249 90q17 0 28-11t11-28v-51h-58v90h19z",
            }()
        );
    }
}
