#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer heart_2() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M354 32q33 0 61.5 12.5t50 34 34 50T512 190q0 32-12 61t-35 50L290 466q-14 14-34 14t-34-14L46 301q-23-22-34.5-50.5T0 191q"
                    "0-33 12.5-62t34-50.5 50-34T158 32q57 0 98 38 41-38 98-38zm76 232q16-14 23.5-33.5T461 190q0-22-8.5-41."
                    "5t-23-34-34-23T354 83q-29 0-48 13t-30 27l-20 27-20-27q-11-14-30-27t-48-13q-22 0-41.5 8.5t-34 23-23 34"
                    "T51 190q0 21 7.5 40.5T82 264l174 164z",
            }()
        );
    }
}
