#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer horizontal_bar_chart() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M487 461q11 0 18 7.5t7 18.5-7 18-18 7H26q-11 0-18.5-7T0 487V25Q0 14 7.5 7T26 0t18 7 7 18v436h436zM122 128q-11 0-18.5-7."
                    "5T96 102t7.5-18 18.5-7h300q11 0 18 7t7 18-7 18.5-18 7.5H122zm0 128q-11 0-18.5-7.5T96 230t7.5-18 18.5-"
                    "7h202q11 0 18 7t7 18-7 18.5-18 7.5H122zm0 128q-11 0-18.5-7.5T96 358t7.5-18 18.5-7h110q11 0 18 7t7 18-"
                    "7 18.5-18 7.5H122z",
            }()
        );
    }
}
