#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer iphone_2() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M0 346V166q0-29 22.5-49.5T77 96h358q32 0 54.5 20.5T512 166v180q0 29-22.5 49.5T435 416H77q-32 0-54.5-20.5T0 346zm461-180"
                    "q0-8-7.5-13.5T435 147H77q-11 0-18.5 5.5T51 166v180q0 8 7.5 13.5T77 365h358q11 0 18.5-5.5T461 346V166z",
            }()
        );
    }
}
