#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer kpi_managing_my_area() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M327 100q-7-7-7-17 0-11 7.5-18t18.5-7 18 8l28 30 75-87q8-9 20-9 10 0 17.5 7.5T512 25q0 9-6 17l-94 109q-7 9-19 9-11 0-19"
                    "-8zm-49 154q13 6 28.5 15.5T322 296q0 10-7 17t-17 7q-11 0-22-9-13-11-35.5-17t-42.5-6h-13q-28 0-52.5 10"
                    ".5T90 327t-28.5 42.5T51 422v7h147q11 0 18.5 7t7.5 18-7.5 18.5T198 480H26q-11 0-18.5-7.5T0 454v-32q0-5"
                    "5 29-99.5t77-67.5l-5-5q-37-37-37-90 0-27 10-50t27.5-40.5 41-27.5T192 32t49.5 10.5 41 28T310 111t10 49"
                    "-11 51-31 43zM192 83q-32 0-54.5 22.5T115 160t22.5 54.5T192 237t54.5-22.5T269 160t-22.5-54.5T192 83zm2"
                    "95 282q11 0 18 7t7 18-7 18.5-18 7.5H346q-11 0-18.5-7.5T320 390t7.5-18 18.5-7h141zm0 96q11 0 18 7.5t7 "
                    "18.5-7 18-18 7H346q-11 0-18.5-7t-7.5-18 7.5-18.5T346 461h141z",
            }()
        );
    }
}
