#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer laptop() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M486 396q11 0 18.5 7t7.5 18-7.5 19-18.5 8H26q-11 0-18.5-8T0 421t7.5-18 18.5-7h8q-2-10-2-17V131q0-28 19.5-47.5T100 64h31"
                    "2q29 0 48.5 19.5T480 131v248q0 7-2 17h8zM100 115q-7 0-12 5t-5 11v248q0 7 5 12t12 5h313q6 0 11-5t5-12V"
                    "131q0-6-5-11t-12-5H100z",
            }()
        );
    }
}
