#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer learning_assistant() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M371 32q12 0 35.5 4.5t47 12.5 41 20T512 96v102q0 11-7.5 18.5T486 224t-18-7.5-7-18.5v-88q-45-27-90-27-44 0-89 27v280q0 1"
                    "1-7.5 18.5T256 416q-4 0-8.5-1.5T235 407q-20-14-44.5-22t-49.5-8-49.5 8T47 407q-8 5-12.5 7t-8.5 2q-11 0"
                    "-18.5-7.5T0 390V96q0-15 17.5-27t41-20 47-12.5T141 32q59 0 115 34 56-34 115-34zM51 347q45-21 90-21 46 "
                    "0 89 21V110q-45-27-89-27-45 0-90 27v237zm365-91q20 0 34 14t14 34q0 5-1 8v3q-4 16-17 26.5T416 352q-20 "
                    "0-34-14t-14-34 14-34 34-14zm96 193q0 14-6.5 22.5T486 480H346q-12 0-19-9t-7-23q0-26 22-45t48-19h52q29 "
                    "0 49.5 20t20.5 45z",
            }()
        );
    }
}
