#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer light_mode() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 96q-11 0-18.5-7.5T230 70V25q0-11 7.5-18T256 0t18 7 7 18v45q0 11-7 18.5T256 96zm-155 32q-12 0-18-8L51 88q-8-6-8-18 "
                    "0-10 7.5-17.5T69 45t18 7l32 32q7 7 7 18t-7.5 18.5T101 128zm309 0q-11 0-18.5-7.5T384 102q0-10 8-18l32-"
                    "32q6-7 18-7 10 0 17.5 7.5T467 70q0 12-7 18l-32 32q-8 8-18 8zM256 384q-27 0-50-10t-40.5-27.5T138 306t-"
                    "10-50 10-50 27.5-40.5T206 138t50-10 50 10 40.5 27.5T374 206t10 50-10 50-27.5 40.5T306 374t-50 10zm0-2"
                    "05q-32 0-54.5 22.5T179 256t22.5 54.5T256 333t54.5-22.5T333 256t-22.5-54.5T256 179zM71 275H26q-11 0-18"
                    ".5-7.5T0 249t7.5-18 18.5-7h45q11 0 18 7t7 18-7 18.5-18 7.5zm416 0h-45q-11 0-18.5-7.5T416 249t7.5-18 1"
                    "8.5-7h45q11 0 18 7t7 18-7 18.5-18 7.5zm-45 192q-12 0-18-8l-32-32q-8-6-8-18 0-10 7.5-17.5T410 384t18 7"
                    "l32 32q7 7 7 18t-7.5 18.5T442 467zm-371 0q-11 0-18.5-7.5T45 441q0-10 8-18l32-32q6-7 18-7 10 0 17.5 7."
                    "5T128 409q0 12-7 18l-32 32q-8 8-18 8zm185 45q-11 0-18.5-7t-7.5-18v-46q0-11 7.5-18t18.5-7 18 7 7 18v46"
                    "q0 11-7 18t-18 7z",
            }()
        );
    }
}
