#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer map_fill() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 0q44 0 82 16t66 44 44 65.5 16 79.5q0 44-17 88t-44.5 83.5T341 449t-68 57q-5 4-9 5t-8 1-8-1-9-5q-34-24-68-57t-61.5-7"
                    "2.5T65 293t-17-88q0-42 16-79.5T108 60t66-44 82-16zm0 118q-40 0-66.5 26.5T163 211t26.5 66.5T256 304t66"
                    ".5-26.5T349 211t-26.5-66.5T256 118z",
            }()
        );
    }
}
