#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer map_3() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M486-1q11 0 18.5 7.5T512 25v403q0 18-16 24l-141 57q-3 2-9 2t-9-1l-169-61-132 60q-3 2-10 2-11 0-18.5-7T0 486V89q0-16 15-"
                    "23L156 2q5-3 10-3 3 0 9 2l169 60L476 2q5-3 10-3zM192 404l128 45V107L192 61v343zM51 446l90-41V65l-90 4"
                    "0v341zM461 65l-90 40v343l90-37V65z",
            }()
        );
    }
}
