#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer master_task_triangle_2() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M498 336q6 14 10 28t4 29q0 25-10 47t-26.5 38-39 25-46.5 9H122q-24 0-46.5-9.5t-39-25.5T10 439.5 0 394q0-16 4-30t11-28l14"
                    "-30 24 13q29 15 59 15 26 0 49-10t40-27 27-40 10-49q0-37-20-68t-54-47l-27-12 16-25q17-26 44.5-41T257 0"
                    "q34 0 63 16t43 46zm-386-48q-33 0-56.5-23.5T32 208t23.5-56.5T112 128t56.5 23.5T192 208t-23.5 56.5T112 "
                    "288z",
            }()
        );
    }
}
