#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer money_bills() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M484 96q11 0 19.5 8t8.5 19v266q0 11-8 19t-19 8h-23l-341 94q-10 2-15 2-19 0-34.5-11.5T51 469l-15-53h-9q-11 0-19-8t-8-19V"
                    "123q0-11 8-19t19-8h23L400 2q10-2 15-2 19 0 34.5 11.5T470 43zm-237 0h184l-10-40q-2-7-8-5zm-23 269v-13h"
                    "-6q-11 0-18.5-7.5T192 326t7.5-18 18.5-7h42q9 0 9-9v-3q0-9-9-9h-8q-25 0-42.5-17.5T192 220q0-21 12.5-37"
                    "t32.5-21v-15H91q-11 29-40 40v138q29 11 40 40h133zm197 0q11-29 40-40V187q-29-11-40-40H288v13h6q11 0 18"
                    ".5 7.5T320 186t-7.5 18-18.5 7h-42q-9 0-9 9t9 9h8q25 0 42.5 17.5T320 289v3q0 21-12.5 37T275 350v15h146"
                    "zm-30-141q13 0 19 8t6 18q0 9-6.5 17t-19.5 8-19-7.5-6-17.5 6-18 20-8zm-269 0q13 0 19 8t6 18q0 9-6.5 17"
                    "t-19.5 8-19-7.5-6-17.5 6-18 20-8zm148 192H89l11 40q2 5 8 5z",
            }()
        );
    }
}
