#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer move() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M505 238q7 7 7 18t-7 18l-77 77q-7 7-18 7t-18.5-7-7.5-18q0-10 8-18l33-33H282v143l33-34q7-7 18-7t18 7.5 7 18.5-7 18l-77 7"
                    "7q-7 7-18 7t-18-7l-77-77q-7-7-7-18t7-18.5 18-7.5 18 7l33 34V282H87l34 33q7 7 7 18t-7.5 18-18.5 7-18-7"
                    "L8 274q-8-8-8-18t8-18l76-77q7-7 18-7t18.5 7 7.5 18-7 18l-34 33h143V87l-33 33q-8 8-18 8-11 0-18-7.5t-7"
                    "-18.5 7-18l77-77q7-7 18-7t18 7l77 77q7 7 7 18t-7 18.5-18 7.5q-10 0-18-8l-33-33v143h143l-33-33q-8-8-8-"
                    "18 0-11 7.5-18t18.5-7 18 7z",
            }()
        );
    }
}
