#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer multiple_line_chart() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M93 114l-18 27h91q11 0 18.5 7t7.5 18-7.5 18.5T166 192H26q-11 0-18.5-7.5T0 166V26Q0 15 7.5 7.5T26 0t18 7.5T51 26v58l11-1"
                    "5q8-11 21-11 6 0 9 1l28 11 23-54q6-16 23-16 11 0 18.5 7.5T192 26q0 3-2 9l-32 77q-3 8-9.5 12t-14.5 4q-"
                    "3 0-9-2zm393 27q11 0 18.5 7t7.5 18-7.5 18.5T486 192H346q-11 0-18.5-7.5T320 166V26q0-11 7.5-18.5T346 0"
                    "t18 7.5 7 18.5v6h29q11 0 19 8l34 37h33q11 0 18.5 7t7.5 18-7.5 18.5T486 128h-44q-11 0-19-8l-34-37h-18v"
                    "58h115zM166 461q11 0 18.5 7t7.5 18-7.5 18.5T166 512H26q-11 0-18.5-7.5T0 486V346q0-11 7.5-18.5T26 320t"
                    "18 7.5 7 18.5v47l21-21q6-7 18-7h26l31-36q8-9 19-9t18.5 7.5T192 346q0 8-6 16l-39 45q-6 9-19 9h-28l-45 "
                    "45h111zm205-45v45h115q11 0 18.5 7t7.5 18-7.5 18.5T486 512H346q-11 0-18.5-7.5T320 486V346q0-11 7.5-18."
                    "5T346 320t18 7.5 7 18.5v19h15l38-38q7-7 18-7h3q12 2 19 13l45 76q3 7 3 13 0 11-7.5 18.5T486 448q-14 0-"
                    "22-13l-28-48-21 21q-8 8-18 8h-26z",
            }()
        );
    }
}
