#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer multiple_bar_chart() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M102 192q-11 0-18-7.5T77 166V26q0-11 7-18.5T102 0t18.5 7.5T128 26v140q0 11-7.5 18.5T102 192zm384 0q-11 0-18-7.5t-7-18.5"
                    "V26q0-11 7-18.5T486 0t18.5 7.5T512 26v140q0 11-7.5 18.5T486 192zm-300 0q-11 0-18.5-7.5T160 166V58q0-1"
                    "1 7.5-18.5T186 32t18 7.5 7 18.5v108q0 11-7 18.5t-18 7.5zm140 0q-11 0-18-7.5t-7-18.5V58q0-11 7-18.5t18"
                    "-7.5 18.5 7.5T352 58v108q0 11-7.5 18.5T326 192zm-300 0q-11 0-18.5-7.5T0 166v-44q0-11 7.5-18.5T26 96t1"
                    "8 7.5 7 18.5v44q0 11-7 18.5T26 192zm384 0q-11 0-18.5-7.5T384 166v-44q0-11 7.5-18.5T410 96t18 7.5 7 18"
                    ".5v44q0 11-7 18.5t-18 7.5zm0 320q-11 0-18.5-7.5T384 486V346q0-11 7.5-18.5T410 320t18 7.5 7 18.5v140q0"
                    " 11-7 18.5t-18 7.5zm-384 0q-11 0-18.5-7.5T0 486V346q0-11 7.5-18.5T26 320t18 7.5 7 18.5v140q0 11-7 18."
                    "5T26 512zm300 0q-11 0-18-7.5t-7-18.5V378q0-11 7-18.5t18-7.5 18.5 7.5T352 378v108q0 11-7.5 18.5T326 51"
                    "2zm-140 0q-11 0-18.5-7.5T160 486V378q0-11 7.5-18.5T186 352t18 7.5 7 18.5v108q0 11-7 18.5t-18 7.5zm300"
                    " 0q-11 0-18-7.5t-7-18.5v-44q0-11 7-18.5t18-7.5 18.5 7.5T512 442v44q0 11-7.5 18.5T486 512zm-384 0q-11 "
                    "0-18-7.5T77 486v-44q0-11 7-18.5t18-7.5 18.5 7.5T128 442v44q0 11-7.5 18.5T102 512z",
            }()
        );
    }
}
