#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer non_binary() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M280 258q45 8 74.5 43t29.5 83q0 26-10 49.5t-27.5 41T306 502t-50 10-50-10-40.5-27.5-27.5-41-10-49.5q0-46 28.5-81t72.5-44"
                    "v-84l-41 41q-8 8-18 8-12 0-19-7.5t-7-18.5q0-10 8-18l68-68-68-69q-8-8-8-18 0-11 7.5-18T170 0t18 7l68 6"
                    "9 68-69q7-7 18-7 12 0 19 7t7 18-7 18l-69 69 69 68q7 7 7 18 0 12-7.5 19t-18.5 7q-10 0-18-8l-44-44v86zm"
                    "-24 203q32 0 54.5-22.5T333 384t-22.5-54.5T256 307t-54.5 22.5T179 384t22.5 54.5T256 461z",
            }()
        );
    }
}
