#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer open_command_field() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M90 416q-11 0-18.5-7.5T64 390q0-10 8-18l121-116L72 140q-8-8-8-18 0-11 7.5-18.5T90 96q10 0 17 7l141 134q8 8 8 19 0 12-8 "
                    "18L107 409q-7 7-17 7zm192 0q-11 0-18.5-7.5T256 390q0-10 8-18l121-116-121-116q-8-8-8-18 0-11 7.5-18.5T"
                    "282 96q10 0 17 7l141 134q8 8 8 19 0 12-8 18L299 409q-7 7-17 7z",
            }()
        );
    }
}
