#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer overview_chart() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M486 192q11 0 18.5 7.5T512 218v76q0 11-7.5 18.5T486 320H378q-11 0-18.5-7.5T352 294v-22h-32v22q0 16-15 24l61 66h56q11 0 "
                    "18.5 7.5T448 410v76q0 11-7.5 18.5T422 512H314q-11 0-18.5-7.5T288 486v-76q0-11 7.5-18.5T314 384h9l-59-"
                    "64h-16l-59 64h9q11 0 18.5 7.5T224 410v76q0 11-7.5 18.5T198 512H90q-11 0-18.5-7.5T64 486v-76q0-11 7.5-"
                    "18.5T90 384h56l61-66q-15-8-15-24v-22h-32v22q0 11-7.5 18.5T134 320H26q-11 0-18.5-7.5T0 294v-76q0-11 7."
                    "5-18.5T26 192h108q11 0 18.5 7.5T160 218v22h32v-22q0-17 15-24l-60-66H90q-11 0-18.5-7.5T64 102V26q0-11 "
                    "7.5-18.5T90 0h108q11 0 18.5 7.5T224 26v76q0 11-7.5 18.5T198 128h-8l58 64h16l58-64h-8q-11 0-18.5-7.5T2"
                    "88 102V26q0-11 7.5-18.5T314 0h108q11 0 18.5 7.5T448 26v76q0 11-7.5 18.5T422 128h-57l-60 66q15 7 15 24"
                    "v22h32v-22q0-11 7.5-18.5T378 192h108zM339 77h58V51h-58v26zm-224 0h58V51h-58v26zm-6 166H51v26h58v-26zm"
                    "160 0h-26v26h26v-26zm192 0h-58v26h58v-26zM173 435h-58v26h58v-26zm224 0h-58v26h58v-26z",
            }()
        );
    }
}
