#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer phone() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M422 0q38 0 64 26t26 64v332q0 38-26 64t-64 26H90q-38 0-64-26T0 422v-14q0-11 7.5-18t18.5-7 18 7 7 18v14q0 17 11 28t28 11"
                    "h332q17 0 28-11t11-28V90q0-17-11-28t-28-11H218q-11 0-18.5-7T192 26t7.5-18.5T218 0h204zM58 320q-24 0-4"
                    "1-17T0 262V58q0-24 17-41T58 0h44q24 0 41 17t17 41v204q0 24-17 41t-41 17H58zm-7-58q0 7 7 7h44q7 0 7-7V"
                    "58q0-7-7-7H58q-7 0-7 7v204zm339-153q11 0 18.5 7t7.5 18-7.5 18.5T390 160H218q-11 0-18.5-7.5T192 134t7."
                    "5-18 18.5-7h172zm-60 121q0 26-25 26-26 0-26-26 0-25 26-25 25 0 25 25zm-112 26q-26 0-26-26 0-25 26-25 "
                    "25 0 25 25 0 26-25 26zm172-51q26 0 26 25 0 26-26 26-25 0-25-26 0-25 25-25zM218 336q-26 0-26-26 0-25 2"
                    "6-25 25 0 25 25 0 26-25 26zm87-51q25 0 25 25 0 26-25 26-26 0-26-26 0-25 26-25zm85 0q26 0 26 25 0 26-2"
                    "6 26-25 0-25-26 0-25 25-25zm-85 80q25 0 25 25 0 26-25 26-26 0-26-26 0-25 26-25zm-87 51q-26 0-26-26 0-"
                    "25 26-25 25 0 25 25 0 26-25 26zm172-51q26 0 26 25 0 26-26 26-25 0-25-26 0-25 25-25z",
            }()
        );
    }
}
