#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer pipeline_analysis() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M448 427q-2 9-9 15t-17 6H282q-10 0-16.5-6t-8.5-15L193 94q-1-1-1-4 0-11 7.5-18.5T218 64h268q13 0 19.5 9t6.5 21zM51 115v5"
                    "8h51q11 0 18.5 7t7.5 18-7.5 18.5T102 224H51v64h51q11 0 18.5 7.5T128 314t-7.5 18-18.5 7H51v58h51q11 0 "
                    "18.5 7t7.5 18-7.5 18.5T102 448H26q-11 0-18.5-7.5T0 422V90q0-11 7.5-18.5T26 64h76q11 0 18.5 7.5T128 90"
                    "t-7.5 18-18.5 7H51zm198 0l11 58h184l11-58H249zm33 173h140l13-64H270zm119 109l11-58H292l11 58h98z",
            }()
        );
    }
}
