#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer popup_window() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M486 0q11 0 18.5 7.5T512 26v204q0 11-7.5 18.5T486 256H218q-11 0-18.5-7.5T192 230V26q0-11 7.5-18.5T218 0h268zm-25 51H243"
                    "v154h218V51zm25 267q11 0 18.5 7.5T512 344v14q0 24-17 41t-41 17H282v45h108q11 0 18.5 7t7.5 18-7.5 18.5"
                    "T390 512H122q-11 0-18.5-7.5T96 486t7.5-18 18.5-7h108v-45H58q-24 0-41-17T0 358V122q0-24 17-41t41-17h45"
                    "q11 0 18 7.5t7 18.5-7 18-18 7H58q-7 0-7 7v236q0 7 7 7h396q7 0 7-7v-14q0-11 7-18.5t18-7.5z",
            }()
        );
    }
}
