#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer process() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M202 384q-11 0-18.5-7.5T176 358q0-10 8-18l89-84-89-84q-8-8-8-18 0-11 7.5-18.5T202 128q10 0 17 7l109 102q8 8 8 19t-8 19L"
                    "219 377q-7 7-17 7zm144 0q-11 0-18.5-7.5T320 358q0-10 8-18l89-84-89-84q-8-8-8-18 0-11 7.5-18.5T346 128"
                    "q10 0 17 7l109 102q8 8 8 19t-8 19L363 377q-7 7-17 7zm-288 0q-11 0-18.5-7.5T32 358q0-10 8-18l89-84-89-"
                    "84q-8-8-8-18 0-11 7.5-18.5T58 128q10 0 17 7l109 102q8 8 8 19t-8 19L75 377q-7 7-17 7z",
            }()
        );
    }
}
