#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer program_triangles() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M507 303q5 12 5 23 0 23-17 40.5T454 384h-66l23 44q6 12 6 26 0 23-16 40.5T359 512H154q-26 0-42-17.5T96 454q0-13 6-25l54-"
                    "109H58q-25 0-41.5-17.5T0 262q0-11 4-22L89 36q7-17 21.5-26.5T142 0t31.5 9T195 35l69 158q2 1 4.5 1t4.5 "
                    "2l40-96q7-17 21.5-26.5T366 64t31.5 9T419 99zm-326-34l22-45q2-5 5-8.5t6-7.5L148 55q-1-4-6-4t-6 4L52 26"
                    "0q-2 3 0 6t6 3h123zm273 63q10 0 6-9l-88-204q-1-4-6-4t-6 4l-48 117 50 96h92zm-95 129q10 0 6-10L260 247"
                    "q-1-3-6-3-3 0-5 3L148 452q-2 3 0 6t6 3h205z",
            }()
        );
    }
}
