#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer project_definition_triangle() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M473 387q7 14 7 29 0 26-18 45t-46 19H96q-28 0-46-19t-18-45q0-15 7-29L198 67q9-17 24.5-26t32.5-9 33 9 25 26zm-57 42q13 0"
                    " 13-13 0-2-2-6L267 90q-2-5-5.5-6t-6.5-1q-7 0-11 7L85 410q-2 4-2 6 0 13 13 13h320z",
            }()
        );
    }
}
