#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer projector() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M422 64q38 0 64 26t26 64v140q0 38-26 64t-64 26H90q-38 0-64-26T0 294V154q0-38 26-64t64-26h332zm39 90q0-17-11-28t-28-11H9"
                    "0q-17 0-28 11t-11 28v140q0 17 11 28t28 11h332q17 0 28-11t11-28V154zm-339 6q11 0 18 7.5t7 18.5v76q0 11"
                    "-7 18.5t-18 7.5-18.5-7.5T96 262v-76q0-11 7.5-18.5T122 160zm76 0q11 0 18.5 7.5T224 186v76q0 11-7.5 18."
                    "5T198 288t-18-7.5-7-18.5v-76q0-11 7-18.5t18-7.5zm154 0q26 0 45 19t19 45-19 45-45 19-45-19-19-45 19-45"
                    " 45-19zm0 77q13 0 13-13t-13-13-13 13 13 13zM166 397q11 0 18.5 7t7.5 18-7.5 18.5T166 448h-44q-11 0-18."
                    "5-7.5T96 422t7.5-18 18.5-7h44zm224 0q11 0 18.5 7t7.5 18-7.5 18.5T390 448h-44q-11 0-18.5-7.5T320 422t7"
                    ".5-18 18.5-7h44z",
            }()
        );
    }
}
