#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer question_mark() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 0q53 0 99.5 20T437 75t55 81.5 20 99.5-20 99.5-55 81.5-81.5 55-99.5 20-99.5-20T75 437t-55-81.5T0 256t20-99.5T75 75t"
                    "81.5-55T256 0zm0 461q42 0 79.5-16.5T401 400t44-65 16-79-16.5-79.5T400 111t-65-44-79-16-79.5 16.5T111 "
                    "112t-44 65-16 79 16.5 79.5T112 401t65 44 79 16zm0-365q40 0 68 28t28 68q0 33-20 58.5T282 284v10q0 11-7"
                    ".5 18.5T256 320t-18.5-7.5T230 294v-32q0-11 8-18t21-7q17 0 29.5-13t12.5-32-13-32-32-13-32 12.5-13 29.5"
                    "q0 13-7 21t-18 8-18.5-9-7.5-26 7.5-32.5T188 123t30.5-19.5T256 96zm0 256q14 0 23 9t9 23-9 23-23 9-23-9"
                    "-9-23 9-23 23-9z",
            }()
        );
    }
}
