#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer repost() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M486 160q11 0 18.5 7.5T512 186t-7 18l-77 76q-8 8-18 8-12 0-18-8l-77-76q-8-8-8-18 0-11 7.5-18.5T333 160t18 7l33 34V83H11"
                    "5v51q0 11-7 18.5T90 160t-18.5-7.5T64 134V58q0-11 7.5-18.5T90 32h320q11 0 18 7.5t7 18.5v143l33-34q7-7 "
                    "18-7zm-64 192q11 0 18.5 7.5T448 378v76q0 11-7.5 18.5T422 480H102q-11 0-18-7.5T77 454V311l-33 33q-8 8-"
                    "18 8-11 0-18.5-7.5T0 326q0-10 8-18l76-77q9-7 18-7 10 0 19 7l76 77q8 8 8 18 0 11-7.5 18.5T179 352q-10 "
                    "0-18-8l-33-33v118h269v-51q0-11 7-18.5t18-7.5z",
            }()
        );
    }
}
