#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer response() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M192 151q60 0 112.5 21t91.5 58.5 61.5 89T480 432v54q0 11-7.5 18.5T454 512t-18-7.5-7-18.5v-54q0-50-18.5-92.5t-50.5-73-75"
                    "-47.5-93-17h-74l105 107q7 7 7 18t-7.5 18.5T204 353q-10 0-18-8L39 194q-7-7-7-18 0-10 7-17L186 8q8-8 18"
                    "-8 11 0 18.5 7.5T230 26q0 10-7 17L118 151h74z",
            }()
        );
    }
}
