#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer retail_store_manager() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M390 128q38 0 64 26t26 64v204q0 38-26 64t-64 26H122q-38 0-64-26t-26-64V218q0-38 26-64t64-26h6V90q0-38 26-64t64-26h76q38"
                    " 0 64 26t26 64v38h6zm-211 0h154V90q0-17-11-28t-28-11h-76q-17 0-28 11t-11 28v38zm250 90q0-17-11-28t-28"
                    "-11H122q-17 0-28 11t-11 28v204q0 17 11 28t28 11h268q17 0 28-11t11-28V218zm-83 6q11 0 18 7.5t7 18.5v14"
                    "0q0 11-7 18.5t-18 7.5-18.5-7.5T320 390V250q0-11 7.5-18.5T346 224zm-91 64q11 0 18.5 7.5T281 314v76q0 1"
                    "1-7.5 18.5T255 416t-18-7.5-7-18.5v-76q0-11 7-18.5t18-7.5zm-89 32q11 0 18.5 7.5T192 346v44q0 11-7.5 18"
                    ".5T166 416t-18-7.5-7-18.5v-44q0-11 7-18.5t18-7.5z",
            }()
        );
    }
}
