#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer sales_notification() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M422 0q38 0 64 26t26 64v396q0 11-7.5 18.5T486 512q-9 0-18-7l-95-95H90q-38 0-64-26.5T0 320V90q0-38 26-64T90 0h332zM51 32"
                    "0q0 16 11 27t28 11h64v-51h-32q-11 0-18.5-7T96 282t7.5-18.5T122 256h70q5 0 9-4t4-9-4-9-9-4h-26q-26 0-4"
                    "5-19t-19-45q0-23 15-40t37-22V51H90q-17 0-28 11T51 90v230zM461 90q0-17-11-28t-28-11H205v51h25q11 0 18."
                    "5 7.5T256 128t-7.5 18.5T230 154h-64q-5 0-8.5 3.5T154 166t3.5 9 8.5 4h26q26 0 45 19t19 45q0 23-14.5 40"
                    ".5T205 306v52h179q10 0 18 8l59 59V90zm-71 6q11 0 18.5 7.5T416 122t-7.5 18-18.5 7h-44q-11 0-18.5-7t-7."
                    "5-18 7.5-18.5T346 96h44zm0 81q11 0 18.5 7t7.5 18-7.5 18.5T390 228h-44q-11 0-18.5-7.5T320 202t7.5-18 1"
                    "8.5-7h44zm0 64q11 0 18.5 7t7.5 18-7.5 18.5T390 292h-44q-11 0-18.5-7.5T320 266t7.5-18 18.5-7h44z",
            }()
        );
    }
}
