#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer sap_box() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M509 176q3 6 3 13v195q0 8-4 14.5t-12 9.5L243 509q-6 3-13 3-6 0-11-3L14 405q-14-6-14-23V122q0-19 17-24L279 2q2-2 8-2t12 "
                    "3l149 77q7 3 11 10zm-48 191V204l-31-16q-14-8-14-23v-44L286 53l-64 24 97 49q8 4 10 10l52 88q3 6 3 13v1"
                    "60zM302 240q-14-6-14-22v-51l-131-66-67 24 101 52q7 3 10 10l52 88q3 6 3 13v160l77-30V257zM51 366l154 7"
                    "9V306l-34-23q-11-8-11-21v-43L51 163v203z",
            }()
        );
    }
}
