#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer scissors() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M505 439q7 7 7 19 0 10-7.5 17.5T486 483t-18-7L285 292l-68 68q7 17 7 40 0 48-32 80t-80 32-80-32-32-80 32-80 80-32q44 0 7"
                    "6 29l61-61-61-61q-32 29-76 29-48 0-80-32T0 112t32-80 80-32 80 32 32 80q0 22-7 40zM371 195q-11 0-18-7."
                    "5t-7-17.5q0-12 7-19L468 36q7-7 18-7t18.5 7 7.5 18-7 18L389 188q-7 7-18 7zm-259-22q26 0 43.5-17.5T173 "
                    "112t-17.5-43.5T112 51 68.5 68.5 51 112t17.5 43.5T112 173zm0 288q26 0 43.5-17.5T173 400t-17.5-43.5T112"
                    " 339t-43.5 17.5T51 400t17.5 43.5T112 461z",
            }()
        );
    }
}
