#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer soccer() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M254.503.998q52.897 0 99.805 19.462t81.84 53.895 55.392 81.34T512 256.5t-20.46 100.304-55.392 80.842-81.84 53.895-99.80"
                    "5 19.462h-9.98q-50.901-5.988-95.813-26.448t-77.848-52.897-51.899-75.852T0 260.491q0-53.895 19.462-101"
                    ".302t53.895-82.34 80.842-55.39T254.503.998zm160.686 125.754q-34.932-41.918-84.834-61.879l-47.907 34.9"
                    "32v79.844l40.92 29.942 71.86-21.957zM183.641 64.873q-50.9 18.963-84.834 61.88l18.963 60.88 71.86 21.9"
                    "58 40.92-29.942V99.805zm1.996 247.517l-18.963-55.891-69.863-21.957-43.914 31.938q0 51.898 31.937 98.8"
                    "07h62.878zm242.527 52.897q28.943-43.915 31.937-98.807l-42.916-31.938-70.861 21.957-17.965 54.893 39.9"
                    "22 53.895h59.883zm-100.803 30.94l-36.928-49.903H224.56l-37.926 52.896 17.965 53.895q13.973 2.994 25.9"
                    "5 4.99t24.951 1.996 25.95-1.996 26.947-4.99z",
            }()
        );
    }
}
