#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer sorting_ranking() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M390 224H122q-11 0-18.5-7.5T96 198q0-8 5-15L236 10q8-10 20-10t20 10l135 173q5 7 5 15 0 11-7.5 18.5T390 224zm-216-51h164"
                    "L256 67zm82 339q-12 0-20-10L101 329q-5-7-5-15 0-11 7.5-18.5T122 288h268q11 0 18.5 7.5T416 314q0 8-5 1"
                    "5L276 502q-8 10-20 10zm-82-173l82 106 82-106H174z",
            }()
        );
    }
}
