#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer sound_loud() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M427 63q40 38 62.5 88T512 256t-22.5 105-62.5 88q-9 7-17 7-11 0-18.5-7.5T384 430t8-19q32-30 50.5-70t18.5-85-18.5-85-50.5"
                    "-70q-8-8-8-19t7.5-18.5T410 56q8 0 17 7zm-179 6q5-5 14-5 11 0 18.5 7t7.5 19v332q0 11-7.5 18.5T262 448q"
                    "-7 0-14-5l-128-91H26q-11 0-18.5-7.5T0 326V186q0-11 7.5-18.5T26 160h94zm92 49q17 0 30.5 16.5t24 39 16 "
                    "46T416 256t-5.5 36-16 45.5-24 39T340 393q-11 0-18.5-6.5T314 370q0-14 15-27 15-14 25.5-37.5T365 256t-1"
                    "0.5-49.5T329 169t-15-27q0-10 7.5-17t18.5-7zm-103 21l-94 67q-5 5-15 5H51v90h77q10 0 15 5l94 67V139z",
            }()
        );
    }
}
