#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer space_navigation() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M384 256q0 47-29 81.5T282 381v105q0 11-7.5 18.5T256 512t-18.5-7.5T230 486V381q-44-9-73-43.5T128 256t29-82 73-43V26q0-11"
                    " 7.5-18.5T256 0t18.5 7.5T282 26v105q44 8 73 43t29 82zm-128 77q32 0 54.5-22.5T333 256t-22.5-54.5T256 1"
                    "79t-54.5 22.5T179 256t22.5 54.5T256 333z",
            }()
        );
    }
}
