#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer switch_classes() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M422 0q38 0 64 26t26 64v300q0 11-7.5 18.5T486 416t-18-7.5-7-18.5V90q0-17-11-28t-28-11H122q-11 0-18.5-7T96 26t7.5-18.5T1"
                    "22 0h300zm-96 96q38 0 64 26t26 64v236q0 38-26 64t-64 26H71q-29 0-50-21T0 441V186q0-38 26-64t64-26h236"
                    "zm39 90q0-17-11-28t-28-11H90q-17 0-28 11t-11 28v255q0 8 6 14t14 6h255q17 0 28-11t11-28V186zM208 288q-"
                    "20 0-34-14t-14-34 14-34 34-14 34 14 14 34-14 34-34 14zm42 32q29 0 49.5 20t20.5 45q0 14-7.5 22.5T294 4"
                    "16H122q-13 0-19.5-8.5T96 385q0-25 20.5-45t49.5-20h84z",
            }()
        );
    }
}
