#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer sys_back_2() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 0q53 0 100 20t81.5 54.5T492 156t20 100-20 100-54.5 81.5T356 492t-100 20-100-20-81.5-54.5T20 356 0 256t20-100 54.5-"
                    "81.5T156 20 256 0zM141 256l74-73q9-11 9-23 0-13-9.5-22.5T192 128q-12 0-23 9l-96 96q-9 10-9 23 0 12 9 "
                    "23l96 96q11 9 23 9 13 0 22.5-9.5T224 352t-9-23zm193 0l74-73q9-11 9-23 0-13-9.5-22.5T385 128q-12 0-23 "
                    "9l-96 96q-9 10-9 23 0 12 9 23l96 96q11 9 23 9 13 0 22.5-9.5T417 352t-9-23z",
            }()
        );
    }
}
