#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer table_view() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M390 32q38 0 64 26t26 64v268q0 38-26 64t-64 26H122q-38 0-64-26t-26-64V122q0-38 26-64t64-26h268zm-89 128V83h-90v77h90zm1"
                    "28-38q0-17-11-28t-28-11h-38v77h77v-38zM122 83q-17 0-28 11t-11 28v38h77V83h-38zm179 218v-90h-90v90h90z"
                    "m-218 0h77v-90H83v90zm269 0h77v-90h-77v90zm-141 51v77h90v-77h-90zM83 390q0 17 11 28t28 11h38v-77H83v3"
                    "8zm307 39q17 0 28-11t11-28v-38h-77v77h38z",
            }()
        );
    }
}
