#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer tag_cloud_chart() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M405 160q23 0 42.5 9.5t33.5 25 22.5 35.5 8.5 42q0 23-8.5 43.5T480 351t-34.5 24-42.5 9H231l-91 89q-9 7-18 7-11 0-18.5-7."
                    "5T96 454v-74q-42-11-69-45T0 256q0-26 9.5-49T38 166q34-29 77-37 18-43 56-70t85-27q28 0 53 9.5t45 27 33"
                    ".5 41T405 160zm-2 173q24 0 41-17.5t17-43.5q0-25-17.5-43T403 211h-21q-11 0-18.5-8.5T356 176t-8-34.5-21"
                    ".5-29.5T295 91t-39-8q-27 0-50 14.5T169 135q14 5 29 15t27.5 23 20.5 28 8 29q0 12-6.5 21t-19.5 9q-20 0-"
                    "26-26-5-21-25-38t-46-17h-3q-32 0-54.5 22.5T51 256q0 30 20 52t45 24q15 1 23 8.5t8 17.5v36l55-54q7-7 18"
                    "-7h183z",
            }()
        );
    }
}
