#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer thing_type() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M422 96q38 0 64 26t26 64v128q0 37-26 63t-64 26H267l-95 101q-8 8-18 8-11 0-18.5-7.5T128 486V337l-86 73q-6 6-16 6-11 0-18"
                    ".5-7.5T0 390V90q0-38 26-64T90 0h204q38 0 64 26t26 64v6h38zM128 270v-84q0-38 26-64t64-26h115v-6q0-17-1"
                    "1-28t-28-11H90q-17 0-28 11T51 90v245zm333-84q0-17-11-28t-28-11H218q-17 0-28 11t-11 28v236l58-62q8-8 1"
                    "9-8h166q17 0 28-11t11-27V186z",
            }()
        );
    }
}
