#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer thumb_up() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M58 512q-24 0-41-17T0 454V250q0-24 17-41t41-17h90l67-175q5-17 30-17 15 0 28.5 6.5t24 17.5T314 49.5t6 31.5v79h103q37 0 6"
                    "3 26t26 63q0 5-.5 10.5T510 270l-41 173q-8 31-32 50t-55 19H58zm89-269v218h235q14 0 24-8t13-22l41-173q1"
                    "-3 1-9 0-15-11.5-26.5T423 211H295q-11 0-18.5-7t-7.5-18V81q0-16-14-25l-65 171q-6 16-24 16h-19zM51 454q"
                    "0 7 7 7h38V243H58q-7 0-7 7v204z",
            }()
        );
    }
}
