#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer timesheet() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M51 201v260h84q11 0 18.5 7t7.5 18-7.5 18.5T135 512H26q-11 0-18.5-7.5T0 486V192q0-10 6-17L149 9q6-9 19-9h190q11 0 18.5 7"
                    ".5T384 26v76q0 11-7.5 18.5T358 128t-18-7.5-7-18.5V51H180l-20 23v67q0 21-15 36t-36 15H59zm301-9q33 0 6"
                    "2.5 12.5t51 34 34 51T512 352t-12.5 62.5-34 51-51 34T352 512t-62.5-12.5-51-34-34-51T192 352t12.5-62.5 "
                    "34-51 51-34T352 192zm0 269q23 0 43-8.5t34.5-23 23-34.5 8.5-43-8.5-43-23-34.5-34.5-23-43-8.5-43 8.5-34"
                    ".5 23-23 34.5-8.5 43 8.5 43 23 34.5 34.5 23 43 8.5zm39-85q7 7 7 18t-7.5 18.5T373 420q-11 0-19-8l-26-2"
                    "7q-8-6-8-18v-66q0-11 7.5-18.5T346 275t18 7.5 7 18.5v56z",
            }()
        );
    }
}
