#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer to_be_reviewed() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 512q-24 0-41-17L17 297Q0 280 0 256t17-41L215 17q17-17 41-17t41 17l198 198q17 17 17 40 0 12-5.5 23.5T493 298L297 49"
                    "5q-17 17-41 17zm0-461q-3 0-4 2L53 251q-2 4-2 5 0 2 2 4l199 199q2 2 4 2 1 0 5-2l198-199q2-1 2-4t-2-5L2"
                    "61 53q-2-2-5-2z",
            }()
        );
    }
}
