#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer travel_itinerary() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M420 293q-5 0-7-1l-157-36v127q0 18-9 26.5T225 423l-73 24q-3 1-8 1-11 0-20-8t-9-21q0-15 13-23l57-37V257L35 292q-2 1-7 1-"
                    "11 0-19.5-8T0 265v-9q0-16 14-24l171-104V36q0-15 10.5-25.5T221 0t25 10.5T256 36v92l178 104q14 8 14 24v"
                    "9q0 12-8.5 20t-19.5 8zm-102 56q14 0 24 9.5t10 23.5-10 24-24 10-23.5-10-9.5-24 9.5-23.5T318 349zm66 41"
                    "q0-11 7.5-18t18.5-7h76q11 0 18.5 7t7.5 18-7.5 18.5T486 416h-76q-11 0-18.5-7.5T384 390zm-66 55q14 0 24"
                    " 9.5t10 23.5-10 24-24 10-23.5-10-9.5-24 9.5-23.5T318 445zm168 16q11 0 18.5 7t7.5 18-7.5 18.5T486 512h"
                    "-76q-11 0-18.5-7.5T384 486t7.5-18 18.5-7h76z",
            }()
        );
    }
}
