#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer trend_down() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M486 256q11 0 18.5 7.5T512 282v108q0 11-7.5 18.5T486 416H378q-11 0-18.5-7.5T352 390t7.5-18 18.5-7h52L281 192l-83 88q-8 "
                    "8-19 8-10 0-17-7L8 140q-8-8-8-18 0-11 7.5-18.5T26 96q10 0 17 7l135 123 85-90q8-8 19-8 12 0 19 9l160 1"
                    "85v-40q0-11 7-18.5t18-7.5z",
            }()
        );
    }
}
