#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer underline_text() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 384q-33 0-62-12.5T143 337t-34.5-51T96 224V58q0-11 7.5-18.5T122 32t18 7.5 7 18.5v166q0 22 8.5 42t23.5 35 35 23.5 42"
                    " 8.5q23 0 42.5-8.5T333 301t23.5-35 8.5-42V58q0-11 7-18.5t18-7.5 18.5 7.5T416 58v166q0 33-12.5 62T369 "
                    "337t-51 34.5-62 12.5zm198 96H58q-11 0-18.5-7.5T32 454t7.5-18 18.5-7h396q11 0 18.5 7t7.5 18-7.5 18.5T4"
                    "54 480z",
            }()
        );
    }
}
