#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer upstacked_chart() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M454 96q-11 0-18-7.5T429 70V58q0-11 7-18.5t18-7.5 18.5 7.5T480 58v12q0 11-7.5 18.5T454 96zM326 224q-11 0-18-7.5t-7-18.5"
                    "v-76q0-11 7-18.5t18-7.5 18.5 7.5T352 122v76q0 11-7.5 18.5T326 224zm128 32q-11 0-18-7.5t-7-18.5v-76q0-"
                    "11 7-18.5t18-7.5 18.5 7.5T480 154v76q0 11-7.5 18.5T454 256zm-268-32q-11 0-18.5-7.5T160 198v-12q0-11 7"
                    ".5-18.5T186 160t18 7.5 7 18.5v12q0 11-7 18.5t-18 7.5zM58 288q-11 0-18.5-7.5T32 262v-12q0-11 7.5-18.5T"
                    "58 224t18 7.5 7 18.5v12q0 11-7 18.5T58 288zm268 32q-11 0-18-7.5t-7-18.5v-12q0-11 7-18.5t18-7.5 18.5 7"
                    ".5T352 282v12q0 11-7.5 18.5T326 320zm-140 0q-11 0-18.5-7.5T160 294t7.5-18 18.5-7 18 7 7 18-7 18.5-18 "
                    "7.5zm268 160q-11 0-18-7.5t-7-18.5V314q0-11 7-18.5t18-7.5 18.5 7.5T480 314v140q0 11-7.5 18.5T454 480zM"
                    "58 384q-11 0-18.5-7.5T32 358t7.5-18 18.5-7 18 7 7 18-7 18.5-18 7.5zm128 96q-11 0-18.5-7.5T160 454v-76"
                    "q0-11 7.5-18.5T186 352t18 7.5 7 18.5v76q0 11-7 18.5t-18 7.5zm140 0q-11 0-18-7.5t-7-18.5v-76q0-11 7-18"
                    ".5t18-7.5 18.5 7.5T352 378v76q0 11-7.5 18.5T326 480zm-268 0q-11 0-18.5-7.5T32 454v-12q0-11 7.5-18.5T5"
                    "8 416t18 7.5 7 18.5v12q0 11-7 18.5T58 480z",
            }()
        );
    }
}
