#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer vertical_stacked_chart() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M282 160q-11 0-18.5-7.5T256 134V58q0-11 7.5-18.5T282 32t18 7.5 7 18.5v76q0 11-7 18.5t-18 7.5zm172 269q11 0 18.5 7t7.5 1"
                    "8-7.5 18.5T454 480H58q-11 0-18.5-7.5T32 454V58q0-11 7.5-18.5T58 32t18 7.5T83 58v371h371zM154 256q-11 "
                    "0-18.5-7.5T128 230V122q0-11 7.5-18.5T154 96t18 7.5 7 18.5v108q0 11-7 18.5t-18 7.5zm262-96q-14 0-23-9t"
                    "-9-23 9-23 23-9 23 9 9 23-9 23-23 9zm6 32q11 0 18.5 7.5T448 218v44q0 11-7.5 18.5T422 288t-18-7.5-7-18"
                    ".5v-44q0-11 7-18.5t18-7.5zm-134 64q-14 0-23-9t-9-23 9-23 23-9 23 9 9 23-9 23-23 9zm-6 128q-11 0-18.5-"
                    "7.5T256 358v-44q0-11 7.5-18.5T282 288t18 7.5 7 18.5v44q0 11-7 18.5t-18 7.5zm-122 0q-14 0-23-9t-9-23 9"
                    "-23 23-9 23 9 9 23-9 23-23 9zm256 0q-14 0-23-9t-9-23 9-23 23-9 23 9 9 23-9 23-23 9z",
            }()
        );
    }
}
