#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer windows_doors() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M486 64q11 0 18.5 7.5T512 90v176q0 11-7.5 18.5T486 292H303q-11 0-18.5-7.5T277 266V90q0-11 7.5-18.5T303 64h183zm-277 0q1"
                    "1 0 18.5 7.5T235 90v332q0 11-7.5 18.5T209 448H26q-11 0-18.5-7.5T0 422V90q0-11 7.5-18.5T26 64h183zm252"
                    " 51h-41v37h41v-37zm-133 0v37h41v-37h-41zm-144 0H51v282h133V115zm144 126h41v-38h-41v38zm133 0v-38h-41v"
                    "38h41zm-324 27q-23 0-23-22t23-22 23 22-23 22z",
            }()
        );
    }
}
