#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer work_history() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M422 77q38 0 64 26t26 63v224q0 38-26 64t-64 26H90q-38 0-64-26T0 390V122q0-38 26-64t64-26h115q9 0 18 7l44 38h155zm39 89q"
                    "0-16-11-27t-28-11H256q-9 0-18-7l-44-38H90q-17 0-28 11t-11 28v268q0 17 11 28t28 11h332q17 0 28-11t11-2"
                    "8V166zm-269 90q-20 0-34-14t-14-34 14-34 34-14 34 14 14 34-14 34-34 14zm198-68q11 0 18.5 7.5T416 214t-"
                    "7.5 18-18.5 7h-44q-11 0-18.5-7t-7.5-18 7.5-18.5T346 188h44zm0 81q11 0 18.5 7.5T416 295t-7.5 18-18.5 7"
                    "h-44q-11 0-18.5-7t-7.5-18 7.5-18.5T346 269h44zm-172 19q29 0 49.5 20t20.5 45q0 14-7.5 22.5T262 384H122"
                    "q-11 0-18.5-8.5T96 353q0-25 20.5-45t49.5-20h52z",
            }()
        );
    }
}
