#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5Icons
{
    inline Nui::ElementRenderer write_new_document() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M51 189v272h19q11 0 18.5 7t7.5 18-7.5 18.5T70 512H26q-11 0-18.5-7.5T0 486V179q0-11 7-17L150 8q6-8 18-8h190q11 0 18.5 7."
                    "5T384 26v76q0 11-7.5 18.5T358 128t-18-7.5-7-18.5V51H179l-3 4v73q0 21-15 36t-35 15H61zm454 23q7 7 7 18"
                    "t-7 18l-25 26q-8 8-19 8-10 0-18-8l-50-51q-7-7-7-18t7-18l25-26q7-7 18-7 12 0 19 7zm-75 77q7 9 7 18t-7 "
                    "18L254 504q-8 8-18 8h-50q-11 0-18.5-7.5T160 486v-51q0-9 7-18l176-179q8-8 18-8 12 0 18 8zm-55 18l-14-1"
                    "4-150 153v15h14z",
            }()
        );
    }
}
