#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer _3d() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M68 188l145 74c8 4 15 12 15 21v172c0 19-22 31-38 22L44 391c-8-4-12-11-12-21V211c0-19 20-32 36-23zm230 74l146-73c16-8 36"
                    " 3 36 22l-1 159c0 10-4 17-12 21l-145 86c-16 9-37-3-37-22V283c0-10 4-17 13-21zM267 5l166 79c19 9 20 35"
                    " 1 46l-167 83c-7 5-15 5-23 0L78 130c-19-11-19-37 0-46L245 5c7-2 15-2 22 0z",
            }()
        );
    }
}
