#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer add_point() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M165.5 310c-83 0-154-71-154-154 0-84 71-155 154-155 84 0 155 71 155 155 0 83-71 154-155 154zm155 104c-15 0-26-13-26-26 "
                    "0-15 11-26 26-26h51v-52c0-15 13-25 26-25 15 0 25 10 25 25v52h52c13 0 26 11 26 26 0 13-13 26-26 26h-52"
                    "v50c0 15-10 26-25 26-13 0-26-11-26-26v-50h-51z",
            }()
        );
    }
}
