#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer answered_change_request() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M395.5 361l57 56V85c0-13-10-24-25-24h-342c-15 0-24 11-24 24v244c0 15 9 25 24 25h293c7 0 13 2 17 7zM85.5 11h342c41 0 72 "
                    "33 72 74v391c0 9-4 18-13 21-11 7-21 2-28-5l-90-90h-283c-43 0-73-32-73-73V85c0-41 30-74 73-74z",
            }()
        );
    }
}
