#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer back_to_search() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M229 379c92 0 165-71 165-165 0-90-73-165-165-165-91 0-165 72-165 165s70 165 165 165zm-33-69c-7 0-12-2-17-7l-72-71c-5-5-"
                    "7-10-7-17 0-8 2-14 7-18l72-71c5-5 10-8 17-8s12 3 17 7c5 5 7 11 7 18 0 6-2 12-7 16l-55 55 55 55c5 5 7 "
                    "10 7 17s-2 13-7 17c-5 5-10 7-17 7zm200 37l93 93c5 5 7 10 7 17s-2 13-7 17c-5 5-11 8-17 8-7 0-13-3-17-7"
                    "l-93-94c-38 31-83 46-133 46-117 0-213-94-213-213C16 96 110 2 229 2c118 0 213 92 213 212 0 51-16 95-46"
                    " 133zm-80-37c-7 0-12-2-17-7l-72-71c-5-5-7-10-7-17 0-8 2-14 7-18l72-71c5-5 10-8 17-8s12 3 17 7c5 5 7 1"
                    "1 7 18 0 6-2 12-7 16l-55 55 55 55c5 5 7 10 7 17s-2 13-7 17c-5 5-10 7-17 7z",
            }()
        );
    }
}
