#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer before_total() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M3.406 54.956c2.997-12.99 15.987-22.981 28.976-22.981h319.745c18.985 0 31.975 12.99 31.975 31.974s-12.99 31.975-31.975 "
                    "31.975H118.314l156.875 134.892c6.994 6.994 12.99 15.987 12.99 24.98 0 10.991-3.997 18.985-12.99 25.98"
                    "L118.314 415.668h233.813c18.985 0 31.975 12.99 31.975 31.974s-12.99 31.975-31.975 31.975H32.382c-12.9"
                    "9 0-25.979-8.993-28.976-21.983-2.998-14.988 0-25.98 9.992-34.972l194.844-166.867L13.398 89.928C.408 7"
                    "9.936-3.59 67.946 3.406 54.956zm442.647 110.912l59.952 57.954c7.993 6.994 7.993 18.984 0 26.978-4.996"
                    " 2.998-8.993 4.996-13.99 4.996s-8.992-1.998-13.988-4.996l-25.98-24.98v106.915c0 10.99-8.992 18.985-19"
                    ".983 18.985s-19.984-7.994-19.984-18.985V225.82L386.1 250.8c-4.996 2.998-8.992 4.996-13.988 4.996s-8.9"
                    "93-1.998-13.99-4.996c-7.993-7.994-7.993-19.984 0-26.978l59.953-57.954c2.997-3.997 7.994-5.995 13.989-"
                    "5.995 4.996 0 9.992 1.998 13.989 5.995z",
            }()
        );
    }
}
