#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer blocked() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M16.5 250c0-132 108-239 240-239s239 107 239 239-107 240-239 240-240-108-240-240zm240-191c-44 0-83 13-116 39l269 266c24-"
                    "32 38-70 38-113 0-105-86-192-191-192zm120 340l-270-267c-27 33-42 73-42 118 0 105 86 192 191 192 47 0 "
                    "88-16 121-43z",
            }()
        );
    }
}
