#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer bullet_chart() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M2 232c0-15 10-26 25-26h314v-28c0-15 10-26 25-26s25 11 25 26v28h96c15 0 26 11 26 26v45c0 15-11 26-26 26h-96v29c0 15-10 "
                    "25-25 25s-25-10-25-25v-29H27c-15 0-25-11-25-26v-45z",
            }()
        );
    }
}
