#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer cell_lock() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M383.5 128v76c44 0 77 33 77 77v153c0 23-7 41-22 55-14 15-32 23-55 23h-255c-23 0-41-8-55-23-15-14-22-32-22-55V281c0-44 3"
                    "3-77 77-77v-76c0-51 29-99 77-118 14-7 31-10 50-10 33 0 68 12 91 37 12 11 21 25 27 40 7 15 10 32 10 51"
                    "zm-204 0v76h153v-76c0-45-32-77-77-77-44 0-76 33-76 77zm230 306V281c0-16-11-25-26-25h-255c-17 0-26 8-2"
                    "6 25v153c0 17 9 26 26 26h255c8 0 14-2 19-7 5-4 7-10 7-19z",
            }()
        );
    }
}
