#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer collected_change_request() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M73.143 313.051l196.023 116.054 169.691-88.747-74.118-43.886-84.846 38.035c-7.802 4.876-15.603 4.876-24.38 0L145.31 269"
                    ".166zM67.29 164.815L267.215 282.82l169.692-87.771L239.909 78.019zm342.309 102.4l90.697 53.638C508.1 3"
                    "26.705 512 333.531 512 342.31s-3.901 16.579-11.703 21.455L283.794 482.743c-7.802 4.876-15.604 4.876-2"
                    "3.405 0L16.579 336.457c-7.802-4.876-11.703-12.678-11.703-22.43 0-8.777 3.901-15.604 11.703-20.48l84.8"
                    "46-51.688-89.722-53.638C3.9 183.345 0 176.518 0 167.741c0-10.728 3.901-17.554 11.703-22.43L228.206 27"
                    ".306c8.777-5.852 16.579-5.852 24.38 0l241.86 145.31c8.777 5.852 13.653 13.653 13.653 22.43 0 7.803-4."
                    "876 14.63-13.653 20.48z",
            }()
        );
    }
}
