#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer column_selected() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M375.5 346V155c0-15-11-23-24-23-15 0-23 8-23 23v191c0 15 8 24 23 24 13 0 24-9 24-24zm-97 0V155c0-15-9-23-24-23-13 0-23 "
                    "8-23 23v191c0 15 10 24 23 24 15 0 24-9 24-24zm-93 0V155c0-15-11-23-24-23-15 0-25 8-25 23v191c0 15 10 "
                    "24 25 24 13 0 24-9 24-24zm71-336c132 0 239 108 239 240s-107 239-239 239-240-107-240-239 108-240 240-2"
                    "40z",
            }()
        );
    }
}
