#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer confirmed() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 2c131 0 239 108 239 239S387 480 256 480 17 372 17 241 125 2 256 2zm0 430c105 0 191-86 191-191S361 50 256 50 65 136"
                    " 65 241s86 191 191 191zm0-45c-80 0-146-66-146-146S176 96 256 96s145 65 145 145-65 146-145 146zm0-207c"
                    "-35 0-61 26-61 61s26 61 61 61 61-26 61-61-26-61-61-61z",
            }()
        );
    }
}
