#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer consumer_switch() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M36.083 259c0-12 9-21 21-21h104V104c0-12 9-22 21-22s21 10 21 22v134h104c12 0 21 9 21 21v94c0 12-9 21-21 21s-22-9-22-21v"
                    "-73h-19v73c0 12-10 21-21 21-12 0-21-9-21-21v-73h-21v73c0 12-9 21-21 21s-21-9-21-21v-73h-19v73c0 12-11"
                    " 21-22 21-12 0-21-9-21-21v-73h-20v73c0 12-9 21-22 21-12 0-21-9-21-21v-94zm346-70c-5-3-8-9-8-17V22c0-1"
                    "2 9-22 21-22s21 10 21 22v139l51 40c11 8 11 22 4 31-3 5-9 8-17 8-5 0-10-2-13-5zm-8 101c0-12 9-22 21-22"
                    "s21 10 21 22v169c0 12-9 21-21 21s-21-9-21-21V290z",
            }()
        );
    }
}
