#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer created() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M64.5 168c0-6 2-11 7-16l144-144c5-5 10-7 16-7h191c14 0 25 10 25 24v431c0 12-8 24-23 24h-336c-15 0-24-12-24-24V168zm58 0"
                    "l-10 10v254h288V49h-159l-10 10v61c0 27-20 48-47 48h-62zm48 119c-11-9-11-24 0-33 5-5 11-7 17-7s12 2 16"
                    " 7l31 32 79-80c5-6 11-8 17-8s13 2 18 8c9 9 9 24 0 35l-97 95c-4 4-10 7-16 7s-12-3-17-7z",
            }()
        );
    }
}
