#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer cross_union() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M477 21c9 9 9 24 0 33L68 463c-5 5-10 7-16 7-5 0-11-2-17-7-9-9-9-24 0-33L443 21c5-5 10-7 17-7s12 2 17 7zm-165 84L61 356c"
                    "-4-4-9-7-12-11-29-29-43-63-43-103C6 161 71 96 151 96c39 0 78 16 105 44 12-13 27-24 46-32zm194 137c0 8"
                    "0-66 146-146 146-39 0-77-15-104-44-13 14-29 25-47 32-3 3-6 1-10 4l252-252 9 8c29 25 46 67 46 106z",
            }()
        );
    }
}
