#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer debit_card() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M1.5 148c0-43 33-76 76-76h357c43 0 76 33 76 76v256c0 43-33 76-76 76h-357c-43 0-76-33-76-76V148zm51 103v153c0 15 10 25 2"
                    "5 25h357c15 0 26-10 26-25V251h-408zm0-78h408v-25c0-15-11-25-26-25h-357c-15 0-25 10-25 25v25z",
            }()
        );
    }
}
