#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer decrease() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M307.154 219.656V65.623c0-11.848-9.114-21.874-22.786-21.874H65.623c-11.848 0-21.874 10.026-21.874 21.874v154.033c0 13.6"
                    "72 10.026 21.875 21.874 21.875h218.745c13.672 0 22.786-8.203 22.786-21.875zm43.75-154.033v154.033c0 3"
                    "7.37-29.167 66.535-66.536 66.535H65.623C29.166 286.191 0 257.025 0 219.656V65.623C0 29.166 29.166 0 6"
                    "5.623 0h218.745c37.37 0 66.535 29.166 66.535 65.623zm154.944 259.76c8.203 8.203 8.203 21.875 0 30.078"
                    "l-75.65 75.649c-.911.911-1.822 1.823-2.734 1.823l-3.646 3.646c-.911.911-3.645.911-8.203.911s-7.291 0-"
                    "9.114-.911c-.911-2.735-3.646-2.735-4.557-3.646-.912 0-1.823-.912-2.734-1.823l-75.65-75.65c-8.203-8.20"
                    "2-8.203-21.874 0-30.077 10.026-10.026 23.698-10.026 31.9 0l38.281 37.37V216.01c0-11.849 8.203-21.875 "
                    "21.874-21.875 11.85 0 20.964 10.026 20.964 21.875v146.741l39.191-37.369c8.203-10.026 21.875-10.026 30"
                    ".078 0z",
            }()
        );
    }
}
