#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer descending_bars() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M307 186c17 0 26 9 26 26v162c0 17-9 26-26 26s-26-9-26-26V212c0-17 9-26 26-26zm104 214c-17 0-26-9-26-26V264c0-17 9-26 26"
                    "-26 18 0 27 9 27 26v110c0 17-9 26-27 26zm-314 0c-17 0-26-9-26-26V28c0-17 9-26 26-26s26 9 26 26v346c0 "
                    "17-9 26-26 26zm105 0c-17 0-26-9-26-26V133c0-17 9-26 26-26s26 9 26 26v241c0 17-9 26-26 26zM65 428h383c"
                    "19 0 28 9 28 26s-9 26-28 26H65c-19 0-29-9-29-26s10-26 29-26z",
            }()
        );
    }
}
