#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer descending_stacked_bars() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M40 456c0-16 8-24 24-24h384c16 0 24 8 24 24s-8 24-24 24H64c-16 0-24-8-24-24zm144-240V73c0-15 10-24 25-24s24 9 24 24v143"
                    "c0 15-9 25-24 25-17 0-25-8-25-25zm0 169v-96c0-16 8-24 25-24 15 0 24 9 24 24v96c0 15-9 24-24 24-17 0-2"
                    "5-8-25-24zm95-239c0-17 8-25 25-25 15 0 24 10 24 25v95c0 15-9 24-24 24s-25-9-25-24v-95zM112 289c-15 0-"
                    "24-9-24-24v-95c0-15 9-24 24-24 16 0 24 8 24 24v95c0 15-9 24-24 24zm167 96v-72c0-16 8-24 25-24 15 0 24"
                    " 9 24 24v72c0 15-9 24-24 24-17 0-25-8-25-24zM88 97V25c0-15 9-24 24-24 16 0 24 8 24 24v72c0 16-8 24-24"
                    " 24-15 0-24-9-24-24zm0 288v-48c0-15 9-24 24-24 16 0 24 8 24 24v48c0 16-8 24-24 24-15 0-24-9-24-24zm28"
                    "8-108v-24c0-17 8-25 24-25s24 8 24 25v24c0 15-9 24-24 24s-24-9-24-24zm0 108v-24c0-16 8-24 24-24s24 8 2"
                    "4 24v24c0 16-8 24-24 24s-24-8-24-24z",
            }()
        );
    }
}
