#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer draw_circle() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M460.5 76c-21 0-38-17-38-38s17-37 38-37 37 16 37 37-16 38-37 38zm-408 1c-21 0-38-17-38-38s17-38 38-38 37 17 37 38-16 38"
                    "-37 38zm205-54c119 0 216 97 216 216s-97 216-216 216-216-97-216-216 97-216 216-216zm166 216c0-92-74-16"
                    "6-166-166s-166 74-166 166 74 166 166 166 166-74 166-166zm-369 163c21 0 38 17 38 38s-17 38-38 38-38-17"
                    "-38-38 17-38 38-38zm368 40c0-21 16-37 37-37s38 16 38 37-17 38-38 38-37-17-37-38z",
            }()
        );
    }
}
