#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer draw_freehand() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M99 357L367 87c9-9 27-9 36 0 11 11 11 26 0 37L135 393c-5 5-11 7-19 7-20 0-33-27-17-43zM458 0c23 0 38 15 38 38 0 21-15 3"
                    "9-38 39-21 0-39-18-39-39 0-23 18-38 39-38zM54 404c21 0 38 17 38 38 0 23-17 38-38 38-23 0-38-15-38-38 "
                    "0-21 15-38 38-38z",
            }()
        );
    }
}
