#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer driver_warning() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M208 241c-66 0-119-53-119-119C89 57 142 2 208 2c65 0 120 55 120 120 0 66-55 119-120 119zm251-119c-16 0-24-8-24-24V26c0-"
                    "15 9-24 24-24s24 9 24 24v72c0 15-9 24-24 24zM208 50c-39 0-71 32-71 72 0 39 32 71 71 71s72-32 72-71c0-"
                    "40-33-72-72-72zm251 179c-20 0-36-16-36-36s16-36 36-36 36 16 36 36-16 36-36 36zm-84 12c65 0 120 53 120"
                    " 119 0 65-55 120-120 120-66 0-119-55-119-120 0-66 53-119 119-119zm-167 72c-72 0-128 51-140 119h139c13"
                    " 0 25 11 25 24s-12 24-25 24H41c-13 0-24-11-24-24 0-105 85-191 191-191 13 0 24 11 24 24s-11 24-24 24zm"
                    "167 119c40 0 72-32 72-72s-32-71-72-71-71 31-71 71 31 72 71 72zm0-113c24 0 42 17 42 41s-18 43-42 43-42"
                    "-19-42-43 18-41 42-41z",
            }()
        );
    }
}
