#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer driver() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M208 240c-66 0-120-54-120-120C88 55 142 0 208 0c67 0 121 55 121 120 0 66-54 120-121 120zm0-192c-39 0-71 32-71 72 0 39 3"
                    "2 72 71 72s72-33 72-72c0-40-33-72-72-72zm168 192c65 0 120 53 120 119 0 67-55 121-120 121-66 0-120-54-"
                    "120-121 0-66 54-119 120-119zm-168 72c-72 0-128 53-141 120h140c13 0 25 9 25 24 0 13-12 24-25 24H40c-13"
                    " 0-24-11-24-24 0-107 85-192 192-192 13 0 24 11 24 24 0 15-11 24-24 24zm168 120c40 0 72-33 72-73s-32-7"
                    "1-72-71c-41 0-72 31-72 71s31 73 72 73zm0-114c24 0 43 17 43 41s-19 43-43 43c-25 0-42-19-42-43s17-41 42"
                    "-41z",
            }()
        );
    }
}
