#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer empty_union() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M342 83c90 0 164 74 164 164 0 91-74 164-164 164-34 0-65-9-93-28-23 13-50 21-79 21C79 404 6 331 6 240 6 150 79 76 170 76"
                    "c35 0 65 10 92 29 25-15 52-22 80-22zM53 240c0 65 52 117 117 117 15 0 29-3 43-8-23-28-35-63-35-102 0-4"
                    "3 17-82 44-111-17-9-35-13-52-13-65 0-117 53-117 117zm289 124c64 0 117-52 117-117 0-64-53-117-117-117-"
                    "16 0-31 3-44 9 23 28 36 62 36 101 0 43-17 81-45 112 16 8 34 12 53 12zm-89-41c21-21 34-51 34-83 0-29-1"
                    "1-55-28-75-23 22-35 49-35 82 0 29 10 55 29 76z",
            }()
        );
    }
}
