#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer event2() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M19 415V114c0-36 29-65 65-65h64V21c0-12 10-22 22-22s21 10 21 22v28h86V21c0-12 10-22 22-22s22 10 22 22v28h64c36 0 65 29 "
                    "65 65v64c0 12-10 22-22 22s-21-10-21-22v-64c0-12-10-22-22-22h-64v29c0 12-10 22-22 22s-22-10-22-22V92h-"
                    "86v29c0 12-9 22-21 22s-22-10-22-22V92H84c-12 0-22 10-22 22v301c0 12 10 22 22 22h129c12 0 21 9 21 21s-"
                    "9 22-21 22H84c-36 0-65-29-65-65zm355 65c-64 0-118-54-118-119 0-64 54-118 118-118 65 0 119 54 119 118 "
                    "0 65-54 119-119 119zm0-194c-43 0-75 32-75 75s32 76 75 76 76-33 76-76-33-75-76-75zm-226-64c-12 0-21-10"
                    "-21-22s9-22 21-22h129c12 0 22 10 22 22s-10 22-22 22H148zm205 145v-40c0-12 9-22 21-22s22 10 22 22v32l1"
                    "6 17c8 9 7 22-2 30-4 4-9 6-14 6-7 0-12-2-16-7l-22-23c-3-3-5-8-5-15zm-205-59c-12 0-21-10-21-22s9-21 21"
                    "-21h64c12 0 21 9 21 21s-9 22-21 22h-64zm-21 64c0-12 9-21 21-21h42c12 0 22 9 22 21s-10 22-22 22h-42c-1"
                    "2 0-21-10-21-22z",
            }()
        );
    }
}
