#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer expand_all() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M145 392l33-33c5-5 11-8 18-8 23 0 34 28 18 44l-77 77c-5 5-11 8-18 8s-13-3-18-8l-77-77c-16-16-5-44 18-44 7 0 13 3 18 8l3"
                    "3 33V94c0-15 11-26 26-26s26 11 26 26v298zm325-273H290c-15 0-26-10-26-25s11-26 26-26h180c15 0 26 11 26"
                    " 26s-11 25-26 25zm-180 65h180c15 0 26 11 26 26s-11 25-26 25H290c-15 0-26-10-26-25s11-26 26-26zm0 129h"
                    "180c15 0 26 10 26 25s-11 26-26 26H290c-15 0-26-11-26-26s11-25 26-25zm0 115h180c15 0 26 11 26 26s-11 2"
                    "6-26 26H290c-15 0-26-11-26-26s11-26 26-26z",
            }()
        );
    }
}
