#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer face_okey_dokey() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 0c132 0 240 108 240 240S388 480 256 480 16 372 16 240 124 0 256 0zm192 240c0-107-85-192-192-192S64 133 64 240s85 1"
                    "92 192 192 192-85 192-192zm-276-24c-20 0-36-16-36-36s16-36 36-36 36 16 36 36-16 36-36 36zm126-14c-10 "
                    "0-17-4-22-13-7-12-2-25 10-32 2 0 44-23 87-2 12 7 19 20 12 32s-20 18-32 11c-11-5-22-6-30-3-5 1-10 2-15"
                    " 4-3 2-6 3-10 3zm75 64c11 5 18 20 13 31-17 41-51 72-98 84s-90 1-125-28c-9-8-12-25-4-34s25-12 34-4c23 "
                    "19 53 27 84 19s54-29 65-56c5-11 20-17 31-12z",
            }()
        );
    }
}
