#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer face_neutral() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 0c132 0 240 108 240 240S388 480 256 480 16 372 16 240 124 0 256 0zm192 240c0-107-85-192-192-192S64 133 64 240s85 1"
                    "92 192 192 192-85 192-192zm-276-24c-20 0-36-16-36-36s16-36 36-36 36 16 36 36-16 36-36 36zm132-36c0-20"
                    " 16-36 36-36s36 16 36 36-16 36-36 36-36-16-36-36zM184 288h144c15 0 24 9 24 24s-9 24-24 24H184c-15 0-2"
                    "4-9-24-24s9-24 24-24z",
            }()
        );
    }
}
