#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer face_very_happy() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M255.5 1c132 0 240 108 240 240s-108 239-240 239-239-107-239-239 107-240 239-240zm192 240c0-105-87-192-192-192s-191 87-1"
                    "91 192 86 191 191 191 192-86 192-191zm-239-60c0 20-16 36-36 36s-36-16-36-36 16-36 36-36 36 16 36 36zm"
                    "131-36c20 0 36 16 36 36s-16 36-36 36-36-16-36-36 16-36 36-36zm-179 143h191c10 0 17 5 22 15 5 7 2 19-3"
                    " 24-27 36-67 57-115 57s-88-21-115-57c-1-3-3-7-4-12-1-3 0-7 2-12 5-7 13-15 22-15z",
            }()
        );
    }
}
