#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer face_very_bad() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 0c132 0 240 108 240 240S388 480 256 480 16 372 16 240 124 0 256 0zm0 432c106 0 192-86 192-192 0-105-86-192-192-192"
                    "-105 0-192 87-192 192 0 106 87 192 192 192zm-48-252c0 20-16 36-36 36s-36-16-36-36 16-36 36-36 36 16 3"
                    "6 36zm132-36c20 0 36 16 36 36s-16 36-36 36-36-16-36-36 16-36 36-36zm-84 120c48 0 89 22 115 58 5 7 8 1"
                    "7 3 24s-12 14-22 14H160c-9 0-17-5-21-14-5-7-3-17 2-24 26-36 67-58 115-58z",
            }()
        );
    }
}
