#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer face_happy() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M256 0c132 0 240 108 240 240S388 480 256 480 16 372 16 240 124 0 256 0zm0 432c107 0 192-85 192-192S363 48 256 48 64 133"
                    " 64 240s85 192 192 192zm-48-252c0 20-16 36-36 36s-36-16-36-36 16-36 36-36 36 16 36 36zm132-36c20 0 36"
                    " 16 36 36s-16 36-36 36-36-16-36-36 16-36 36-36zM137 309c1-7 4-12 9-16 11-7 26-6 33 5 17 24 46 38 77 3"
                    "8s60-14 77-38c7-11 23-12 34-5 3 3 4 5 5 7 5 9 4 18-1 26-27 36-67 58-115 58s-88-22-115-58c-4-5-5-10-4-"
                    "17z",
            }()
        );
    }
}
