#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer face_astonished() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M136 179c0 19 17 36 36 36 20 0 36-17 36-36 0-20-16-36-36-36-19 0-36 16-36 36zm204 36c20 0 36-17 36-36 0-20-16-36-36-36-"
                    "19 0-36 16-36 36 0 19 17 36 36 36zM256-1c132 0 240 108 240 240S388 479 256 479 16 371 16 239 124-1 25"
                    "6-1zm0 432c106 0 192-87 192-192 0-106-86-192-192-192-105 0-192 86-192 192 0 105 87 192 192 192zm-1-16"
                    "9c27 0 49 22 49 49 0 28-22 50-49 50s-49-22-49-50c0-27 22-49 49-49z",
            }()
        );
    }
}
