#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer female() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M231.5 294c-69-13-123-71-123-145 0-81 66-148 147-148s148 67 148 148c0 74-54 132-123 145v51h74c15 0 24 10 24 25s-9 25-24"
                    " 25h-74v73c0 15-10 25-25 25s-24-10-24-25v-73h-74c-15 0-24-10-24-25s9-25 24-25h74v-51zm24-243c-55 0-98"
                    " 43-98 98s43 98 98 98c53 0 99-44 99-98s-46-98-99-98z",
            }()
        );
    }
}
