#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer gas() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M252.962 0c9-2 17 0 23 6 7 7 162 169 158 311-3 97-82 173-177 173-99 0-178-78-178-174 0-53 36-104 75-160 31-44 63-90 82-"
                    "141 3-8 8-13 17-15zm39 161c0 64-17 114-40 114s-40-50-40-114c0-1 1-3 1-4-7 9-12 18-19 27-35 51-66 93-6"
                    "6 132 0 68 57 125 129 125 69 0 125-54 128-126 3-81-58-171-103-227 7 20 10 45 10 73z",
            }()
        );
    }
}
