#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer grid() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M472.038 256c-13 0-24-11-24-24v-71h-102l146 283c7 9 4 21-4 28-5 5-10 7-16 7-3 0-8-1-13-4l-204-135-200 133c-11 7-20 6-28"
                    "-1-9-8-12-17-7-28l137-283h-92v71c0 13-9 24-24 24-13 0-22-11-22-24v-95c0-13 9-24 22-24h139l47-96c5-9 1"
                    "2-13 21-13 11-3 18 4 22 12l50 97h152c15 0 23 11 23 24v95c0 13-8 24-23 24zm-238-143h33l-17-33zm-38 76h"
                    "110l-14-28h-81zm128 47h-142l72 48zm-26 76l110 72-57-110zm-87 0l-56-36-54 109z",
            }()
        );
    }
}
