#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer grip() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M187.5 1c23 0 41 19 41 42s-18 41-41 41-42-18-42-41 19-42 42-42zm137 83c-23 0-42-18-42-41s19-42 42-42 42 19 42 42-19 41-"
                    "42 41zm0 54c23 0 42 19 42 42s-19 42-42 42-42-19-42-42 19-42 42-42zm0 139c23 0 42 19 42 42s-19 42-42 4"
                    "2-42-19-42-42 19-42 42-42zm0 138c23 0 42 18 42 41s-19 42-42 42-42-19-42-42 19-41 42-41zm-137-277c23 0"
                    " 41 19 41 42s-18 42-41 42-42-19-42-42 19-42 42-42zm0 139c23 0 41 19 41 42s-18 42-41 42-42-19-42-42 19"
                    "-42 42-42zm0 138c23 0 41 18 41 41s-18 42-41 42-42-19-42-42 19-41 42-41z",
            }()
        );
    }
}
