#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer heater_treater() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M149 284c0-32 22-63 43-94 16-23 32-46 43-73 2-9 8-14 17-15 9 0 15 0 22 7 5 3 92 93 89 175-3 59-49 104-107 104-59 0-107-"
                    "47-107-104zM17 408v-72c0-15 11-24 24-24s24 9 24 24v72c0 13 11 24 24 24h334c15 0 24-11 24-24v-72c0-15 "
                    "11-24 24-24 15 0 24 9 24 24v72c0 40-32 72-72 72H89c-40 0-72-32-72-72zm0-263V74C17 34 49 2 89 2h334c40"
                    " 0 72 32 72 72v71c0 13-9 24-24 24-13 0-24-11-24-24V74c0-15-9-24-24-24H89c-13 0-24 9-24 24v71c0 13-11 "
                    "24-24 24s-24-11-24-24zm214 73c-19 25-34 47-34 66 0 31 27 56 59 56s58-26 59-58c1-31-19-68-40-99v16c0 3"
                    "5-9 62-21 62-11 0-18-19-21-46-1 1-1 2-2 3z",
            }()
        );
    }
}
