#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer increase_indent() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M482.5 85h-395c-16 0-28-13-28-29s12-28 28-28h395c17 0 29 12 29 28s-12 29-29 29zm-197 141h197c17 0 29 12 29 28s-12 28-29"
                    " 28h-197c-16 0-29-12-29-28s13-28 29-28zm-198 197h395c17 0 29 13 29 29 0 17-12 28-29 28h-395c-16 0-28-"
                    "11-28-28 0-16 12-29 28-29zm111-168c0 3-1 7-2 12-2 2-3 4-4 5s0 1-3 4l-69 69c-6 6-13 9-20 9s-13-3-19-9c"
                    "-12-11-12-29 0-40l20-21h-73c-15 0-28-14-28-29s13-27 28-27h73l-20-22c-12-11-12-28 0-39 11-11 28-11 39 "
                    "0l69 68c4 2 2 5 7 10 1 5 2 9 2 10z",
            }()
        );
    }
}
