#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer keep_segment() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M212.5 317l123-124c9-9 23-9 32 0 9 11 9 24 0 33l-139 139c-9 9-23 9-32 0l-47-46c-9-9-9-23 0-32 11-11 24-11 33 0zm252 93V"
                    "133c0-15-8-24-23-24h-371c-15 0-23 9-23 24v277c0 15 8 23 23 23h371c15 0 23-8 23-23zM70.5 63h371c39 0 7"
                    "0 30 70 70v277c0 40-31 70-70 70h-371c-40 0-70-30-70-70V133c0-40 30-70 70-70z",
            }()
        );
    }
}
