#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer late() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M16.5 276c0-13 11-24 24-24h49c3-5 2-8 3-15h-28c-13 0-24-9-24-24 0-13 11-24 24-24h44c29-61 87-107 159-115V50h-68c-15 0-2"
                    "4-9-24-24 0-13 9-24 24-24h189c13 0 24 11 24 24 0 15-11 24-24 24h-73v24c29 4 56 14 81 29l9-14c5-6 12-9"
                    " 19-9 6 0 11 2 16 5 11 8 11 24 3 35l-9 12c37 37 61 88 61 145 0 112-92 203-204 203-83 0-152-47-184-119"
                    "h-43c-13 0-24-9-24-24 0-13 11-24 24-24h27c-3-4 1-9-2-13h-49c-13 0-24-11-24-24zm120 1c0 86 69 155 155 "
                    "155 85 0 156-69 156-155 0-85-71-156-156-156s-155 71-155 156zm155 19c-15 0-24-11-24-24v-89c0-15 9-24 2"
                    "4-24 13 0 24 9 24 24v65h85c15 0 24 11 24 24s-9 24-24 24h-109z",
            }()
        );
    }
}
