#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer layer() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M252 14l260 160v127L253 467l-126-79L0 306V166zm2 140l76-48-80-50-76 47zm-122 73l86-52-79-50-86 53zm156-51l89 57 80-49-9"
                    "1-56zm-122 74l88 56 87-52-88-56zm-51 11l-82-53v75l82 52v-74zm278 74l86-55v-65l-86 52v68zm-156 5l-89-5"
                    "8v74l89 56v-72zm124-54l-92 54v73l92-58v-69z",
            }()
        );
    }
}
