#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer line_bar_chart() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M447.5 112c15 0 23 8 23 23v237c0 17-8 25-23 25-16 0-24-8-24-25V135c0-15 8-23 24-23zm-191 285c-15 0-22-8-22-25V183c0-16 "
                    "7-24 22-24 17 0 25 8 25 24v189c0 17-8 25-25 25zm96 0c-16 0-24-8-24-25V254c0-16 8-24 24-24s24 8 24 24v"
                    "118c0 17-8 25-24 25zm-190 0c-15 0-24-10-24-25V230c0-15 9-23 24-23s23 8 23 23v142c0 17-8 25-23 25zm-95"
                    " 0c-16 0-24-8-24-25v-71c0-15 8-23 24-23 15 0 23 8 23 23v71c0 17-8 25-23 25zm0 36h380c15 0 23 8 23 23 "
                    "0 16-8 24-23 24h-380c-16 0-24-8-24-24 0-15 8-23 24-23zm0-226c-9 0-16-4-20-11-7-11-5-25 6-32l213-144c9"
                    "-7 23-4 31 4l53 53 69-69c9-9 23-9 34 0 9 11 9 25 0 34l-86 86c-11 9-25 9-34 0l-56-57-197 132c-3 3-8 4-"
                    "13 4z",
            }()
        );
    }
}
