#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer loading_point() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M255 337c-12 0-22-10-22-22s10-23 22-23h46v-92c0-12 11-23 23-23h89c9 0 16 5 21 14l48 115c1 2 1 5 1 8v41c0 39-31 67-68 67"
                    "h-24c-7 33-34 58-67 58-39 0-67-31-67-68 0-39 28-69 67-69 25 0 47 15 59 35h32c12 0 23-11 23-23v-18H255"
                    "zM29 457V163c0-8 3-14 8-18L195 8c4-4 9-5 14-5 6 0 13 3 17 7l96 95c11 9 11 23 0 32-5 5-10 7-16 7-5 0-1"
                    "0-2-16-7l-80-80L75 172v262h68V231c0-12 11-23 23-23h76c12 0 23 11 23 23s-11 23-23 23h-54v203c0 12-10 2"
                    "3-22 23H52c-12 0-23-11-23-23zm368-234h-51v69h81zm-96 189c0 12 11 22 23 22s22-10 22-22-10-23-22-23-23 "
                    "11-23 23z",
            }()
        );
    }
}
