#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer male() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M481.5 45v104c0 15-10 26-25 26s-26-11-26-26v-41l-122 121c22 28 33 60 33 96 0 86-71 155-156 155-86 0-155-69-155-155 0-43"
                    " 17-81 46-110 52-52 135-61 194-21l123-123h-41c-15 0-26-11-26-26s11-26 26-26h104c15 0 25 11 25 26zm-39"
                    "9 280c0 29 10 53 30 73 40 40 107 40 147 0 20-20 30-44 30-73 0-57-47-104-104-104s-103 47-103 104z",
            }()
        );
    }
}
