#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer map_navigation() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M99.81 163l134-152c6-7 14-11 22-11s17 4 23 11l133 152c20 23 6 62-23 62h-266c-28 0-42-39-23-62zm45 137h222l-111 127zm244"
                    "-45h-266c-28 0-42 39-23 62l134 153c6 7 14 10 22 10s16-3 23-10l133-153c20-23 6-62-23-62z",
            }()
        );
    }
}
