#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer match_case() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M132 172l-34 99h99l-34-100c-7-22-12-38-15-49-1 2-2 7-5 15-3 9-6 20-11 35zm318 158c4-9 7-18 7-28v-18l-34 1c-7 1-12 1-17 "
                    "1-24 5-43 9-43 39 0 11 3 19 10 25 6 6 14 9 25 9 23 0 40-10 52-29zM115 80h66l113 316h-55l-27-81H83l-27"
                    " 81H0zm228 312c-24-13-35-38-35-65 0-56 48-77 99-77l50-1v-13c0-15-4-27-12-35-7-8-17-12-31-12-13 0-25 3"
                    "-36 9-11 7-21 15-30 24l-28-33c26-28 58-42 97-42 53 0 93 29 93 86v101c0 11 0 22 1 32 0 11 0 21 1 30h-5"
                    "1c-1-5-1-11-1-17v-18h-2c-18 28-42 39-75 39-15 0-28-3-40-8z",
            }()
        );
    }
}
