#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer medicine_ointment() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M26 66c-11-11-11-27 0-38L45 9c6-6 12-8 19-8 6 0 13 2 18 8l19 19c4 4 4 8 7 12h68c19 0 37 6 53 19l258 223c7 7 10 11 10 19"
                    "s-3 15-9 20L338 472c-7 5-13 8-19 8h-1c-7 0-13-3-19-9L76 212c-13-15-19-33-19-52V91c-5-1-9-3-12-6zm150 "
                    "28h-65v66c0 7 2 13 5 17l204 237 111-110L194 99c-4-3-10-5-18-5zm64 204c-8-8-8-20 0-28l9-9-9-10c-8-8-8-"
                    "20 0-28 5-5 9-7 14-7s10 2 14 7l9 10 10-10c4-4 9-6 14-6s10 2 14 6c9 9 9 19 0 28l-9 10 9 9c9 9 9 19 0 2"
                    "8-5 5-9 7-13 7-5 0-10-2-15-7l-10-9-9 9c-5 5-9 7-14 7s-9-2-14-7z",
            }()
        );
    }
}
