#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer monitor_assembly_sequence() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M42.5 480c-12 0-22-10-22-22V79c0-25 18-44 45-44h45c23 0 43 19 43 44v128h43v-63c0-8 6-17 13-20 3-2 6-2 9-2 5 0 9 1 14 4l"
                    "97 63v-44c0-7 5-16 12-19 3-2 7-3 10-3 4 0 8 1 12 4l120 90c5 5 8 11 8 18v223c0 12-9 22-22 22h-427zm23-"
                    "227v182h383V246l-74-56v39c0 14-12 24-25 24-4 0-7-1-11-4l-96-64v44c0 13-10 24-22 24h-155zm41 153c-11-1"
                    "1-8-23 0-32l28-29-28-29c-9-9-9-23 0-32 5-4 11-6 16-6 6 0 11 2 15 6l44 46c10 10 10 20 0 30l-44 46c-4 4"
                    "-9 6-16 6-6 0-11-2-15-6zm114-90c-9-11-11-23 0-32 4-4 9-6 15-6s11 2 15 6l45 46c9 10 9 20 0 30l-45 46c-"
                    "4 4-9 6-15 6s-11-2-15-6c-11-11-9-23 0-32l27-29zm111 90c-11-11-9-23 0-32l29-29-29-29c-9-9-9-23 0-32 5-"
                    "4 10-6 15-6 6 0 11 2 16 6l44 46c9 8 9 22 0 30l-44 46c-5 4-10 6-16 6s-11-2-15-6zm-266-199h45V79h-45v12"
                    "8z",
            }()
        );
    }
}
