#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer monitor_just_in_time_calls() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M377 268c-72 0-132-59-132-134C245 61 305 0 377 0c74 0 133 61 133 134 0 75-59 134-133 134zm0-224c-48 0-88 41-88 90 0 51 "
                    "40 89 88 89s89-39 89-89c0-49-41-90-89-90zm23 81l15 16c9 9 9 23 0 31-5 5-10 7-15 7s-10-2-16-7l-22-22c-"
                    "4-4-6-9-6-16V90c0-13 8-23 21-23 15 0 23 10 23 23v35zm-332-1h111c14 0 21 7 21 21 0 13-8 23-21 23H68c-1"
                    "2 0-22 8-22 23v222c0 12 10 23 22 23h353c12 0 23-11 23-23V302c0-15 7-23 22-23s22 8 22 23v111c0 39-28 6"
                    "7-67 67H68c-37 0-66-28-66-67V191c0-39 29-67 66-67zm202 144v109c0 15-10 25-25 25-17 0-25-8-25-25V268c0"
                    "-15 10-24 25-24s25 9 25 24zM120 377v-81c0-16 10-25 25-25s26 9 26 25v81c0 15-11 25-26 25s-25-10-25-25z"
                    "m224 25c-16 0-24-8-24-25v-36c0-16 8-24 24-24 17 0 25 8 25 24v36c0 17-8 25-25 25z",
            }()
        );
    }
}
