#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer multi_container() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M142 432h305V263H142v169zm-24-218h353c13 0 24 11 24 24v218c0 13-11 24-24 24H118c-13 0-24-11-24-24V238c0-13 11-24 24-24z"
                    "m269-70V50H65v238c0 13-11 24-24 24s-24-11-24-24V26C17 13 28 2 41 2h368c15 0 24 11 24 24v118c0 13-9 24"
                    "-24 24-13 0-22-11-22-24zM204 413c-15 0-24-9-24-24v-81c0-13 9-24 24-24 13 0 24 11 24 24v81c0 15-11 24-"
                    "24 24zm84-1c-13 0-24-11-24-24v-81c0-15 11-24 24-24s24 9 24 24v81c0 13-11 24-24 24zm83 0c-15 0-24-11-2"
                    "4-24v-81c0-15 9-24 24-24 13 0 24 9 24 24v81c0 13-11 24-24 24zM124 144v-36c0-15 9-24 24-24 13 0 24 9 2"
                    "4 24v36c0 13-11 24-24 24-15 0-24-11-24-24zm84-2v-34c0-15 9-24 24-24 13 0 23 9 23 24v34c0 15-10 24-23 "
                    "24-15 0-24-9-24-24zm83 0v-34c0-15 9-24 24-24 13 0 24 9 24 24v34c0 15-11 24-24 24-15 0-24-9-24-24z",
            }()
        );
    }
}
