#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer network_header() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M16.5 277c0-13 11-24 24-24h150v-48h-126c-13 0-24-11-24-24V26c0-13 11-24 24-24h384c15 0 25 11 25 24v155c0 13-10 24-25 24"
                    "h-125v48h148c15 0 24 11 24 24v179c0 13-9 24-24 24h-431c-13 0-24-11-24-24V277zm48 24v131h383V301h-383z"
                    "m24-251v107h336V50h-336zm28 357c-8 0-15-7-15-15v-51c0-8 7-15 15-15h279c8 0 15 7 15 15v51c0 8-7 15-15 "
                    "15h-279zm3-303c0-11 8-18 17-18h240c11 0 18 7 18 18 0 9-7 18-18 18h-240c-9 0-17-9-17-18z",
            }()
        );
    }
}
