#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer no_time_change() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M257.875 153c-43 0-77-32-77-75s34-77 77-77 75 34 75 77-32 75-75 75zm15 179c-4 3-10 5-17 5-6 0-12-2-17-7l-62-62c-11-11-1"
                    "1-26 0-35 11-11 24-11 35 0l20 18v-52c0-15 11-26 26-26s24 11 24 26v52l20-18c11-11 24-11 35 0 11 9 11 2"
                    "4 0 35l-62 62v1c-1 1-1 1-2 1zm-15 25c43 0 75 32 75 75s-32 77-75 77-77-34-77-77 34-75 77-75zm0 50c-15 "
                    "0-26 10-26 25s11 26 26 26 24-11 24-26-9-25-24-25z",
            }()
        );
    }
}
