#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer not_equal() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M25.888 184.09C11.506 184.09 0 172.584 0 158.202s11.506-25.887 25.888-25.887H319.28l80.54-79.58c5.752-5.754 11.505-7.67"
                    "1 18.216-7.671s13.424 1.917 18.218 7.67c10.546 10.547 10.546 25.888 0 36.435l-44.105 43.146h93.962c14"
                    ".382 0 25.888 11.505 25.888 25.887s-11.506 25.888-25.888 25.888H340.375l-96.84 96.839h242.577c14.382 "
                    "0 25.888 11.505 25.888 25.887s-11.506 24.93-25.888 24.93H192.72l-82.457 82.456c-4.794 4.794-11.505 7."
                    "67-18.217 7.67s-13.423-2.876-18.217-7.67c-10.547-10.547-10.547-25.887 0-36.434l46.022-46.023H25.888C1"
                    "1.506 331.745 0 321.2 0 306.816s11.506-25.887 25.888-25.887h145.737l96.84-96.84H25.887z",
            }()
        );
    }
}
