#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer outdoor() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M67.5 384h377c28 0 51 22 51 50v22c0 13-11 24-24 24h-431c-13 0-24-11-24-24v-22c0-28 23-50 51-50zm21-240c-40 0-72-31-72-7"
                    "1s32-72 72-72 71 32 71 72-31 71-71 71zm27 157l24-42c11-16 31-16 42 0l16 27 75-130c9-16 32-16 41 0l83 "
                    "145c9 16-2 34-21 34h-239c-19 0-30-18-21-34z",
            }()
        );
    }
}
