#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer page_down() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M465 282L278 469c-12 12-30 12-42 0L49 282c-12-12-12-30 0-42s30-12 42 0l165 166 167-166c12-12 30-12 42 0s12 30 0 42zm0-2"
                    "29L278 240c-12 12-30 12-42 0L49 54c-12-12-12-30 0-43C61-1 79-1 91 11l165 166L423 11c12-12 30-12 42 0 "
                    "12 13 12 30 0 42z",
            }()
        );
    }
}
