#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer page_up() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M49 198L236 11c12-12 30-12 42 0l187 187c12 13 12 30 0 42s-30 12-42 0L258 75 91 240c-12 12-30 12-42 0s-12-29 0-42zm0 229"
                    "l187-187c12-12 30-12 42 0l187 186c12 12 12 31 0 43s-30 12-42 0L258 303 91 469c-12 12-30 12-42 0s-12-3"
                    "0 0-42z",
            }()
        );
    }
}
