#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer partially_fixed_cell() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M123 427l258-186H137c-13 0-24 9-24 24v143c0 7 3 14 10 19zm62-307v72h143v-72c0-40-32-71-72-71s-71 31-71 71zm192 0v72c40 "
                    "0 70 33 70 73v143c0 40-30 72-70 72H137c-40 0-72-32-72-72V265c0-40 32-73 72-73v-72C137 55 191 1 256 1c"
                    "67 0 121 54 121 119z",
            }()
        );
    }
}
