#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer phase() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M507.25 267l-87 130c-16 22-37 33-63 33h-329c-10 0-18-4-23-12-6-9-5-18 3-26l91-137-91-138c-5-11-8-18-3-29 5-8 13-12 23-1"
                    "2h329c26 0 47 11 63 33l87 130c6 9 6 19 0 28z",
            }()
        );
    }
}
