#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer recipe() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M425.387 411c-94 94-244 93-337 0-52-52-76-123-69-192h474c7 69-16 140-68 192zm-236-212c-7 0-13-2-17-7l-111-112c-11-11-9-"
                    "23 2-34 9-9 22-9 33 0l110 114c11 11 11 23 0 34-5 4-12 5-17 5z",
            }()
        );
    }
}
