#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer relationship() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M207.5 96c-27 0-48-20-48-47s21-48 48-48 49 21 49 48-22 47-49 47zm237 8c-27 0-48-21-48-48s21-47 48-47 47 20 47 47-20 48-"
                    "47 48zm-91 89c-27 0-48-21-48-48s21-47 48-47 49 20 49 47-22 48-49 48zm-285 287c-27 0-48-21-48-48s21-47"
                    " 48-47 47 20 47 47-20 48-47 48zm90-91c-27 0-47-20-47-47s20-48 47-48 48 21 48 48-21 47-48 47zm147-48c-"
                    "27 0-47-21-47-48s20-47 47-47 48 20 48 47-21 48-48 48z",
            }()
        );
    }
}
