#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer remove_folder() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M56 95c-15-15-17-30-4-44 6-6 12-9 18-9 8 0 17 5 26 14l362 362c16 15 17 30 4 43-6 6-12 9-19 9-8 0-16-4-25-13zM0 184c0-13"
                    " 10-23 23-23h6c12 0 22 10 22 23v220c0 17 9 25 26 25h230c8 0 14 3 18 8 5 5 7 11 7 18 0 17-8 25-25 25H7"
                    "7c-43 0-77-32-77-76V184zM183 83c-29 0-29-51 0-51h23c7 0 12 2 17 7l44 44h168c44 0 77 32 77 76v128c0 8-"
                    "2 14-7 19-4 5-10 7-18 7s-14-2-19-7c-5-6-7-12-7-19V159c0-17-9-25-26-25H257c-7 0-13-3-18-8l-44-43h-12z",
            }()
        );
    }
}
