#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer repeatable() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M197.5 1h239c32 0 59 27 59 59v239c0 15-11 24-24 24s-24-9-24-24V60c0-7-4-11-11-11h-239c-15 0-24-11-24-24s9-24 24-24zm-78"
                    " 79h240c32 0 57 25 57 57v240c0 16-8 24-24 24-13 0-24-9-24-24V137c0-6-3-9-9-9h-240c-15 0-24-11-24-24 0"
                    "-16 8-24 24-24zm-44 77h205c32 0 59 27 59 59v205c0 32-27 59-59 59h-205c-32 0-59-27-59-59V216c0-32 27-5"
                    "9 59-59zm-11 59v205c0 7 4 11 11 11h205c7 0 10-4 10-11V216c0-7-3-10-10-10h-205c-7 0-11 3-11 10z",
            }()
        );
    }
}
