#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer rescheduling2() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M453 165l-63 63c-4 5-10 7-17 7s-13-2-18-7c-11-11-11-26 0-35l19-21H138l19 21c11 9 11 24 0 35-4 5-10 7-17 7s-13-2-18-7l-6"
                    "3-63c-5-4-8-10-8-17s3-15 8-19l63-63c9-11 26-11 35 0 11 9 11 26 0 37l-19 19h236l-19-19c-11-11-11-28 0-"
                    "37 11-11 26-11 35 0l63 63c5 4 7 10 7 19 0 5-2 13-7 17zM77 326c43 0 77 34 77 77s-34 77-77 77-77-34-77-"
                    "77 34-77 77-77zm179 0c43 0 76 34 76 77s-33 77-76 77-77-34-77-77 34-77 77-77zm179 0c43 0 77 34 77 77s-"
                    "34 77-77 77-77-34-77-77 34-77 77-77zM77 429c15 0 26-11 26-26s-11-26-26-26-26 11-26 26 11 26 26 26zm35"
                    "8 0c15 0 26-11 26-26s-11-26-26-26-26 11-26 26 11 26 26 26z",
            }()
        );
    }
}
