#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer row_unselected() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M254.5 11c130 0 241 106 241 238 0 130-106 240-238 240-130 0-240-105-240-237 0-130 105-241 237-241zm193 238c0-106-88-190"
                    "-192-190-106 0-190 88-190 192 0 106 88 190 192 190 106 0 190-88 190-192zm-96-67l-190 1c-13 0-24-11-24"
                    "-24s10-24 23-24l190-1c13 0 24 11 24 24s-10 24-23 24zm-190 49l190-1c13 0 24 11 24 24s-11 24-24 24l-190"
                    " 1c-13 0-24-11-24-24s11-24 24-24zm1 95l190-2c13 0 24 11 24 24s-11 24-24 24l-190 1c-13 0-24-10-24-23s1"
                    "1-24 24-24z",
            }()
        );
    }
}
