#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer separate_segments() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M72.5 308h61c13 0 20 9 20 21 0 13-7 20-20 20h-61c-35 0-62-26-62-61V63c0-35 27-62 62-62h183c35 0 62 27 62 62v20c0 14-7 2"
                    "1-20 21-14 0-21-7-21-21V63c0-12-8-21-21-21h-183c-13 0-21 9-21 21v225c0 13 7 20 21 20zm225-164h142c35 "
                    "0 62 26 62 61v225c0 35-27 62-62 62h-184c-35 0-61-27-61-62V329c0-12 8-21 20-21 13 0 21 9 21 21v101c0 1"
                    "4 7 21 20 21h184c12 0 21-8 21-21V205c0-12-9-20-21-20h-142c-14 0-21-7-21-21 0-13 7-20 21-20zm-55-19c8 "
                    "8 8 20 0 28l-81 83c-8 8-21 8-29 0l-41-41c-8-9-8-21 0-29 9-9 19-9 29 0l26 27 68-68c9-10 18-10 28 0zm49"
                    " 245c-9-9-9-18 0-27l27-28-27-26c-8-8-8-20 0-29 8-8 21-8 29 0l27 26 26-26c9-8 21-8 29 0 9 10 9 20 0 29"
                    "l-27 26 27 28c9 9 9 18 0 27-8 8-20 8-29 0l-26-26-27 26c-8 8-21 8-29 0z",
            }()
        );
    }
}
