#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer side_top_panel_layout() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M88 480c-40 0-72-32-72-72V72C16 32 48 0 88 0h336c40 0 72 32 72 72v336c0 40-32 72-72 72H88zm96-312v264h240c13 0 24-11 24"
                    "-24V168H184zM64 72v336c0 13 11 24 24 24h48V48H88c-13 0-24 11-24 24zm120 48h264V72c0-13-11-24-24-24H18"
                    "4v72z",
            }()
        );
    }
}
