#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer side_panel_left_layout() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M16.5 75c0-41 32-74 72-74h335c40 0 72 33 72 74v330c0 41-32 75-72 75h-335c-40 0-72-34-72-75V75zm168 357h239c13 0 24-12 2"
                    "4-27V75c0-15-11-26-24-26h-239v383zm-96-383c-13 0-24 11-24 26v330c0 15 11 27 24 27h48V49h-48z",
            }()
        );
    }
}
