#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer software_item() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M30.35 443c-15-27-16-54-3-81 5-8 12-13 21-13 3 0 7 1 11 3 12 5 16 20 11 32-5 11-5 22 1 33 3 4 10 15 25 15h323c15 0 21-1"
                    "1 24-15 7-11 8-22 1-33l-160-318c-8-15-20-16-27-16-5 0-17 1-25 16-3 8-12 13-21 13-5 0-9-1-13-3-12-5-14"
                    "-20-9-32 15-29 37-43 68-43s55 16 70 43l160 318c15 27 13 54-2 81-15 23-39 37-66 37h-323c-29 0-51-12-66"
                    "-37zm108-345c66 0 119 53 119 119 0 65-53 120-119 120-65 0-120-55-120-120 0-66 55-119 120-119zm0 36v48"
                    "c20 0 35 15 35 35h48c0-47-36-83-83-83zm0 166v-47c-20 0-36-16-36-36h-48c0 45 39 83 84 83z",
            }()
        );
    }
}
