#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer source() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M457 329c15 0 26 10 26 25v50c0 43-32 76-75 76H105c-43 0-76-33-76-76v-50c0-15 10-25 25-25s26 10 26 25v50c0 15 10 25 25 2"
                    "5h303c15 0 24-10 24-25v-50c0-15 10-25 25-25zM231 87l-59 57c-11 12-23 12-35 0-11-12-11-24 0-35l99-97c7"
                    "-7 10-11 21-11s13 2 18 9l99 99c12 11 12 23 0 35-11 11-23 11-34 0l-59-57v242c0 15-9 25-24 25s-26-10-26"
                    "-25V87z",
            }()
        );
    }
}
