#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer stages_warning() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M216 295l-98-97c-23-23-23-60 0-83l98-97c21-21 59-21 82 0l97 97c11 11 16 25 16 42s-5 30-16 41l-97 97c-12 12-26 18-42 18s"
                    "-29-6-40-18zm145-146l-97-97c-3-3-7-3-8-3-3 0-5 1-7 3l-97 97c-5 5-5 10 0 15l97 97c5 5 10 5 15 0l97-97c"
                    "2-2 3-4 3-7 0-1 0-5-3-8zm-81-39v31c0 15-9 24-24 24-13 0-24-9-24-24v-31c0-15 11-23 24-23 15 0 24 8 24 "
                    "23zm-24 72c15 0 24 9 24 22 0 15-9 25-24 25-13 0-24-10-24-25 0-13 11-22 24-22zm168 155c39 0 71 32 71 7"
                    "1 0 40-32 72-71 72-40 0-72-32-72-72 0-39 32-71 72-71zm-96 71c0 40-33 72-72 72s-72-32-72-72c0-39 33-71"
                    " 72-71s72 32 72 71zm-311 0c0-39 32-71 72-71 39 0 71 32 71 71 0 40-32 72-71 72-40 0-72-32-72-72zm96 0c"
                    "0-13-11-24-24-24-15 0-25 11-25 24 0 15 10 25 25 25 13 0 24-10 24-25zm119 0c0 15 11 25 24 25 15 0 24-1"
                    "0 24-25 0-13-9-24-24-24-13 0-24 11-24 24z",
            }()
        );
    }
}
