#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer stock_warehouse() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M19 172c0-4 1-6 1-7 1-3 2-5 5-8 1-3 3-5 5-6L216 27c13-8 27-12 41-12s28 4 39 12l186 125c4 4 8 6 9 9 1 4 2 7 2 11v285c0 1"
                    "3-8 23-23 23s-23-10-23-23V197c-127 0-253 0-380-2v262c0 13-10 23-25 23-13 0-23-10-23-23V172zm166-48c0 "
                    "13 9 23 24 23h95c13 0 23-10 23-23 0-15-10-24-23-24h-95c-15 0-24 9-24 24zm0 297c0-7 4-12 11-12h48c7 0 "
                    "13 5 13 12v47c0 7-6 12-13 12h-48c-7 0-11-5-11-12v-47zm106 59c-7 0-11-5-11-12v-47c0-7 4-12 11-12h48c7 "
                    "0 13 5 13 12v47c0 7-6 12-13 12h-48zm-95-95c-7 0-11-5-11-12v-47c0-7 4-12 11-12h48c7 0 13 5 13 12v47c0 "
                    "7-6 12-13 12h-48zM90 326c0-7 5-12 12-12h48c7 0 12 5 12 12v47c0 7-5 12-12 12h-48c-7 0-12-5-12-12v-47zm"
                    "12 154c-7 0-12-5-12-12v-47c0-7 5-12 12-12h48c7 0 12 5 12 12v47c0 7-5 12-12 12h-48zM90 278v-47c0-7 5-1"
                    "2 12-12h48c7 0 12 5 12 12v47c0 7-5 12-12 12h-48c-7 0-12-5-12-12z",
            }()
        );
    }
}
