#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer storage() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M17 312c0-15 11-24 24-24h430c13 0 24 9 24 24 0 13-11 24-24 24H280v120c0 13-11 24-24 24s-24-11-24-24V336H41c-13 0-24-11-"
                    "24-24zm0-142c0-13 11-24 24-24h191V26c0-13 11-24 24-24s24 11 24 24v120h191c13 0 24 11 24 24 0 15-11 24"
                    "-24 24H41c-13 0-24-9-24-24z",
            }()
        );
    }
}
