#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer stratification() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M40.5 265c-13 0-24-10-24-25 0-13 11-24 24-24h191V25c0-13 10-24 25-24 13 0 24 11 24 24v191h191c13 0 24 11 24 24 0 15-11 "
                    "25-24 25h-191v191c0 13-11 24-24 24-15 0-25-11-25-24V265h-191zm402-162c-27 0-49-22-49-49 0-25 22-46 49"
                    "-46 25 0 46 21 46 46 0 27-21 49-46 49zm-419 323c0-25 20-48 47-48 25 0 48 23 48 48 0 27-23 47-48 47-27"
                    " 0-47-20-47-47zm377-42c-25 0-47-22-47-47 0-27 22-47 47-47 27 0 47 20 47 47 0 25-20 47-47 47zm-95-240c"
                    "0-25 22-48 47-48s47 23 47 48-22 47-47 47-47-22-47-47zm-146 47c-25 0-47-22-47-47s22-47 47-47c27 0 47 2"
                    "2 47 47s-20 47-47 47z",
            }()
        );
    }
}
