#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer subclass() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M65 145c-27 0-48-20-48-47V50C17 23 38 2 65 2h239c27 0 48 21 48 48v48c0 27-21 47-48 47H113v72h47c0-27 21-48 48-48h239c27"
                    " 0 48 21 48 48v48c0 27-21 48-48 48H208c-27 0-48-21-48-48h-47v119h47c0-27 21-47 48-47h239c27 0 48 20 4"
                    "8 47v48c0 27-21 48-48 48H208c-27 0-48-21-48-48H89c-13 0-24-11-24-24V145zm239-95H65v48h239V50z",
            }()
        );
    }
}
