#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer target_to_date() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M62.5 202c-12 0-21-10-21-22v-64c0-36 28-65 64-65h64V22c0-12 10-21 22-21s21 9 21 21v29h86V22c0-12 9-21 21-21s22 9 22 21v"
                    "29h64c36 0 65 29 65 65v300c0 36-29 64-65 64h-300c-36 0-64-28-64-64v-46c0-3 0-6 1-9 1-2 3-4 4-5l2-2c3-"
                    "3 8-5 14-5 12 0 19 9 22 20v47c0 12 9 21 21 21h300c12 0 21-9 21-21V116c0-12-9-21-21-21h-64v28c0 12-10 "
                    "21-22 21s-21-9-21-21V95h-86v28c0 12-9 21-21 21s-22-9-22-21V95h-64c-12 0-21 9-21 21v64c0 12-10 22-22 2"
                    "2zm-21 76c0-12 9-21 21-21h144l-38-38c-8-8-8-23 0-31 4-4 10-6 16-6 5 0 11 2 15 6l75 77c1 1 1 4 4 5 1 2"
                    " 1 5 1 8s0 6-1 8c0 1-1 2-3 4l-76 78c-3 3-8 5-15 5-5 0-12-1-16-5-8-8-8-23 0-31l38-38h-144c-12 0-21-9-2"
                    "1-21z",
            }()
        );
    }
}
