#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer target_filter() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M17.406 280c-1-6 1-9 8-9h134c5 0 7 2 8 5 11 25 28 42 53 53 3 1 5 3 5 8v134c0 7-2 8-9 8-103-19-180-96-199-199zm8-71c-7 0"
                    "-9-3-8-9 19-103 96-180 199-199 7 0 9 2 9 9v134c0 3-2 6-5 8-25 9-42 27-53 52-1 3-3 5-8 5h-134zm262 262"
                    "V337c0-5 2-7 5-8 25-11 43-28 52-53 2-3 5-5 8-5h134c7 0 10 3 9 9-19 103-96 180-199 199-7 0-9-1-9-8zm0-"
                    "327V10c0-7 2-9 9-9 101 19 180 97 199 199 1 6-2 9-9 9h-134c-3 0-6-2-8-5-9-25-27-43-52-52-3-2-5-5-5-8z",
            }()
        );
    }
}
