#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer thumb_sideway_filled() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M497 117v161c0 39-31 73-71 73l-201 3h-1c-21 0-39-8-54-24l-17-19c-3-3-4-4-8-5l-82-35c-17-7-29-19-37-38l-4-8c-14-30 6-67 "
                    "43-67l107-2 6-89c3-21 14-41 31-53 10-7 21-11 34-12 7-3 13 3 13 10v96c0 23 14 42 30 42s30-19 30-42V30c"
                    "0-8 7-12 15-11l27 7c6 1 9 5 9 12v70c0 23 14 42 30 42s31-19 31-42V55c0-3-2-5 1-6 1-1 3-2 5-2h3c35 7 60"
                    " 35 60 70zm-47 363H217c-13 0-24-11-24-24v-48c0-15 11-23 24-23h233c15 0 25 8 25 23v48c0 13-10 24-25 24"
                    "z",
            }()
        );
    }
}
