#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer thumb_down_filled() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M134.5 2l160-1c39 0 72 31 72 71l3 199v2c0 20-9 40-24 53l-18 16c-3 3-4 7-7 10l-33 80c-7 17-21 29-37 37l-9 4c-15 7-32 6-4"
                    "5-2-14-9-21-22-21-41l-3-105-88-8c-23-2-41-12-53-30-6-9-10-19-12-32-1-9 2-13 11-13h95c23 0 42-15 42-31"
                    "s-19-29-42-29h-78c-8 0-13-7-10-15l6-27c3-6 6-9 11-9h71c23 0 42-14 42-30s-19-29-42-29h-52c-5 0-7-1-8-3"
                    "-1-3-2-4-2-5v-2c7-35 36-60 71-60zm359 47v230c0 15-8 24-23 24h-48c-13 0-24-9-24-24V49c0-13 11-24 24-24"
                    "h48c15 0 23 11 23 24z",
            }()
        );
    }
}
