#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer transformer() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M89 312c0-26 5-50 16-72-11-22-16-46-16-73C89 75 164 0 257 0c92 0 166 75 166 167 0 27-5 51-16 73 11 22 16 46 16 72 0 93-"
                    "74 168-166 168-93 0-168-75-168-168zm291-114c3-11 3-20 3-31 0-69-57-127-126-127-70 0-128 58-128 127 0 "
                    "11 1 20 4 31 31-35 77-53 124-53s92 18 123 53zm-123-14c-43 0-81 21-105 56 24 35 62 55 105 55 41 0 80-2"
                    "0 104-55-24-35-63-56-104-56zm0 256c69 0 126-58 126-128 0-11 0-21-3-32-31 35-76 55-123 55s-93-20-124-5"
                    "5c-3 11-4 21-4 32 0 70 58 128 128 128z",
            }()
        );
    }
}
