#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer truck_unload() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M17 258c0-13 11-24 24-24h263v-97c0-15 11-24 24-24h94c10 0 17 5 21 14l51 122c1 2 1 5 1 9v43c0 35-25 62-58 69 7 12 10 25 "
                    "10 38 0 40-30 72-71 72-40 0-72-32-72-72 0-15 3-27 10-36H199c6 10 9 22 9 36 0 40-31 72-71 72s-72-32-72"
                    "-72c0-14 4-27 11-38-35-7-59-34-59-69v-43zm48 43c0 13 11 23 24 23h334c15 0 24-10 24-23v-19H65v19zm20-2"
                    "00c-9-11-9-25 0-34l59-59c4-4 9-6 16-6s13 2 17 6l59 59c9 9 9 23 0 34-4 4-10 8-17 8s-11-4-16-8l-19-18v7"
                    "0c0 13-11 24-24 24s-24-11-24-24V83l-17 18c-4 5-9 8-16 8s-13-4-18-8zm267 133h83l-29-73h-54v73zM113 408"
                    "c0 13 11 24 24 24 15 0 23-11 23-24 0-15-8-24-23-24-13 0-24 9-24 24zm239 0c0 13 10 24 23 24s24-11 24-2"
                    "4c0-15-11-24-24-24s-23 9-23 24z",
            }()
        );
    }
}
