#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer underline() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M71 428h370c21 0 31 10 31 31 0 19-12 30-31 30H71c-19 0-31-11-31-30 0-21 10-31 31-31zm186-46c-88 0-156-68-156-155V43c0-1"
                    "9 12-32 31-32s31 13 31 32v184c0 52 41 93 94 93 52 0 92-41 92-93V43c0-19 12-32 31-32s30 13 30 32v184c0"
                    " 87-68 155-153 155z",
            }()
        );
    }
}
