#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer variant_configuration() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M81.218 432h142c13 0 24 11 24 24s-11 24-24 24h-142c-40 0-72-32-72-72V73c0-40 32-72 72-72h142c13 0 24 11 24 24 0 15-11 2"
                    "4-24 24h-142c-13 0-24 11-24 24v335c0 13 11 24 24 24zm312-329l83 48c12 7 16 20 9 32l-144 249c-7 12-20 "
                    "16-32 9l-83-48c-13-8-17-19-10-32l145-249c7-12 20-16 32-9zm-1-83l99 57c26 15 4 57-25 42l-98-58c-3-1-2 "
                    "0-5 0 1 0 0 1-2 3l-105 181c-4 8-13 12-21 12-3 0-7-1-12-4-12-7-15-20-8-33l104-180c15-27 46-36 73-20z",
            }()
        );
    }
}
