#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer vessel() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M2.017 232c-2-7-1-15 4-23 5-7 12-10 21-10h26v-51c0-15 10-26 25-26h102c15 0 25 11 25 26v51h26c15 0 25 10 25 25h147l16-16"
                    "c4-6 10-9 19-9h48c9 0 16 3 21 10 5 8 6 16 4 23l-25 73v72c0 15-10 26-25 26h-383c-11 0-22-6-25-17zm60 1"
                    "8l34 102h339v-51c0-1 1-4 2-8l14-43h-2l-15 17c-5 5-12 8-19 8h-184c-15 0-26-10-26-25h-143zm42-51h50v-26"
                    "h-50v26z",
            }()
        );
    }
}
