#pragma once
// This file was generated by xml-to-nui. Do not edit manually.

#include <nui/frontend/elements.hpp>
#include <nui/frontend/attributes.hpp>
#include <nui/frontend/svg_elements.hpp>
#include <nui/frontend/svg_attributes.hpp>

namespace Ui5BusinessSuite
{
    inline Nui::ElementRenderer warehouse() {
        using namespace Nui::Attributes::Literals;
        namespace se = Nui::Elements::Svg;
        namespace sa = Nui::Attributes::Svg;
        namespace nuie = Nui::Elements;
        namespace nuia = Nui::Attributes;

        return se::svg{
            "xmlns"_attr = "http://www.w3.org/2000/svg",
            sa::viewBox = "0 0 512 512",
        }(
            se::path{
                sa::d = "M51 480c-28 0-51-23-51-51V275c0-28 23-51 51-51h410c28 0 51 23 51 51v154c0 28-23 51-51 51H51zm0-51h32v-77c0-25 20-44 45-"
                    "44s44 19 44 44v77h38v-77c0-25 21-44 46-44s44 19 44 44v77h38v-77c0-25 20-44 45-44s44 19 44 44v77h34V27"
                    "5H51v154zm145-242c-9 0-13-4-13-12v-67c0-8 6-13 13-13 2 0 5 1 7 2l110 66c11 7 7 24-6 24H196zm159-12v-6"
                    "7c0-8 5-13 12-13 2 0 5 1 7 2l111 66c11 7 6 24-7 24H368c-9 0-13-4-13-12zM25 187c-9 0-13-4-13-12v-67c0-"
                    "8 6-13 12-13 3 0 5 1 7 2l111 66c11 7 5 24-8 24H25z",
            }()
        );
    }
}
